include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        BUNDLE: "gnome-clocks-dev.flatpak"
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.clocks.json"
        MESON_ARGS: "-Dprofile=development"
        FLATPAK_MODULE: "gnome-clocks"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.clocksDevel"
    extends: ".flatpak"

lint:
  image: "valalang/lint:latest"
  stage: ".pre"
  script:
    - io.elementary.vala-lint src
