/* application.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from application.vala, do not modify */

/*
 * Copyright (C) 2013  Paolo Borelli <pborelli@gnome.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include "config.h"
#include <gdk/gdk.h>
#include <libgweather/gweather.h>

#define CLOCKS_TYPE_APPLICATION (clocks_application_get_type ())
#define CLOCKS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplication))
#define CLOCKS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))
#define CLOCKS_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))

typedef struct _ClocksApplication ClocksApplication;
typedef struct _ClocksApplicationClass ClocksApplicationClass;
typedef struct _ClocksApplicationPrivate ClocksApplicationPrivate;

#define CLOCKS_TYPE_SEARCH_PROVIDER (clocks_search_provider_get_type ())
#define CLOCKS_SEARCH_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_SEARCH_PROVIDER, ClocksSearchProvider))
#define CLOCKS_SEARCH_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_SEARCH_PROVIDER, ClocksSearchProviderClass))
#define CLOCKS_IS_SEARCH_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_SEARCH_PROVIDER))
#define CLOCKS_IS_SEARCH_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_SEARCH_PROVIDER))
#define CLOCKS_SEARCH_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_SEARCH_PROVIDER, ClocksSearchProviderClass))

typedef struct _ClocksSearchProvider ClocksSearchProvider;
typedef struct _ClocksSearchProviderClass ClocksSearchProviderClass;

#define CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS (clocks_world_shell_world_clocks_get_type ())
#define CLOCKS_WORLD_SHELL_WORLD_CLOCKS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS, ClocksWorldShellWorldClocks))
#define CLOCKS_WORLD_SHELL_WORLD_CLOCKS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS, ClocksWorldShellWorldClocksClass))
#define CLOCKS_WORLD_IS_SHELL_WORLD_CLOCKS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS))
#define CLOCKS_WORLD_IS_SHELL_WORLD_CLOCKS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS))
#define CLOCKS_WORLD_SHELL_WORLD_CLOCKS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_WORLD_TYPE_SHELL_WORLD_CLOCKS, ClocksWorldShellWorldClocksClass))

typedef struct _ClocksWorldShellWorldClocks ClocksWorldShellWorldClocks;
typedef struct _ClocksWorldShellWorldClocksClass ClocksWorldShellWorldClocksClass;

#define CLOCKS_TYPE_WINDOW (clocks_window_get_type ())
#define CLOCKS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_WINDOW, ClocksWindow))
#define CLOCKS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_WINDOW, ClocksWindowClass))
#define CLOCKS_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_WINDOW))
#define CLOCKS_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_WINDOW))
#define CLOCKS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_WINDOW, ClocksWindowClass))

typedef struct _ClocksWindow ClocksWindow;
typedef struct _ClocksWindowClass ClocksWindowClass;
enum  {
	CLOCKS_APPLICATION_0_PROPERTY,
	CLOCKS_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* clocks_application_properties[CLOCKS_APPLICATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Block4Data Block4Data;
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _gweather_location_unref0(var) ((var == NULL) ? NULL : (var = (gweather_location_unref (var), NULL)))

struct _ClocksApplication {
	GtkApplication parent_instance;
	ClocksApplicationPrivate * priv;
};

struct _ClocksApplicationClass {
	GtkApplicationClass parent_class;
};

struct _ClocksApplicationPrivate {
	ClocksSearchProvider* search_provider;
	guint search_provider_id;
	ClocksWorldShellWorldClocks* world_clocks;
	guint world_clocks_id;
	ClocksWindow* window;
	GList* system_notifications;
};

struct _Block4Data {
	int _ref_count_;
	ClocksApplication* self;
	GtkSettings* settings;
};

static gint ClocksApplication_private_offset;
static gpointer clocks_application_parent_class = NULL;

GType clocks_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksApplication, g_object_unref)
GType clocks_search_provider_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksSearchProvider, g_object_unref)
guint clocks_search_provider_register_object (void* object,
                                              GDBusConnection* connection,
                                              const gchar* path,
                                              GError** error);
GType clocks_world_shell_world_clocks_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksWorldShellWorldClocks, g_object_unref)
guint clocks_world_shell_world_clocks_register_object (void* object,
                                                       GDBusConnection* connection,
                                                       const gchar* path,
                                                       GError** error);
GType clocks_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksWindow, g_object_unref)
static void _g_free0_ (gpointer var);
static inline void _g_list_free__g_free0_ (GList* self);
static void clocks_application_on_quit_activate (ClocksApplication* self);
static void _clocks_application_on_quit_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                            GVariant* parameter,
                                                                            gpointer self);
void clocks_application_on_add_location_activate (ClocksApplication* self,
                                                  GSimpleAction* action,
                                                  GVariant* parameter);
static void _clocks_application_on_add_location_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                                    GVariant* parameter,
                                                                                    gpointer self);
static void clocks_application_ensure_window (ClocksApplication* self);
ClocksWindow* clocks_window_new (ClocksApplication* app);
ClocksWindow* clocks_window_construct (GType object_type,
                                       ClocksApplication* app);
static void ___lambda60_ (ClocksApplication* self);
static void ____lambda60__gtk_widget_destroy (GtkWidget* _sender,
                                       gpointer self);
ClocksApplication* clocks_application_new (void);
ClocksApplication* clocks_application_construct (GType object_type);
ClocksSearchProvider* clocks_search_provider_new (void);
ClocksSearchProvider* clocks_search_provider_construct (GType object_type);
static void __lambda61_ (ClocksApplication* self,
                  guint32 timestamp);
void clocks_window_show_world (ClocksWindow* self);
static void ___lambda61__clocks_search_provider_activate (ClocksSearchProvider* _sender,
                                                   guint32 timestamp,
                                                   gpointer self);
static gboolean clocks_application_real_dbus_register (GApplication* base,
                                                GDBusConnection* connection,
                                                const gchar* object_path,
                                                GError** error);
ClocksWorldShellWorldClocks* clocks_world_shell_world_clocks_new (GDBusConnection* connection,
                                                                  const gchar* object_path);
ClocksWorldShellWorldClocks* clocks_world_shell_world_clocks_construct (GType object_type,
                                                                        GDBusConnection* connection,
                                                                        const gchar* object_path);
static void clocks_application_real_dbus_unregister (GApplication* base,
                                              GDBusConnection* connection,
                                              const gchar* object_path);
static void clocks_application_real_activate (GApplication* base);
static gboolean __lambda62_ (ClocksApplication* self);
static void clocks_application_withdraw_notifications (ClocksApplication* self);
static gboolean ___lambda62__gtk_widget_focus_in_event (GtkWidget* _sender,
                                                 GdkEventFocus* event,
                                                 gpointer self);
static void clocks_application_update_theme (ClocksApplication* self,
                                      GtkSettings* settings);
void clocks_utils_load_theme_css (const gchar* theme_name);
static void clocks_application_real_startup (GApplication* base);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
void clocks_utils_load_main_css (void);
static void __lambda63_ (Block4Data* _data4_);
static void ___lambda63__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static gint clocks_application_real_handle_local_options (GApplication* base,
                                                   GVariantDict* options);
void clocks_window_add_world_location (ClocksWindow* self,
                                       GWeatherLocation* location);
void clocks_application_send_notification (ClocksApplication* self,
                                           const gchar* notification_id,
                                           GNotification* notification);
static void clocks_application_real_shutdown (GApplication* base);
static void clocks_application_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const GOptionEntry CLOCKS_APPLICATION_option_entries[2] = {{"version", 'v', 0, G_OPTION_ARG_NONE, NULL, N_ ("Print version information and exit"), NULL}, {NULL}};
static const GActionEntry CLOCKS_APPLICATION_action_entries[4] = {{"stop-alarm", NULL, "s"}, {"snooze-alarm", NULL, "s"}, {"quit", _clocks_application_on_quit_activate_gsimple_action_activate_callback}, {"add-location", _clocks_application_on_add_location_activate_gsimple_action_activate_callback, "v"}};

static inline gpointer
clocks_application_get_instance_private (ClocksApplication* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksApplication_private_offset);
}

static void
_g_free0_ (gpointer var)
{
#line 39 "../src/application.vala"
	var = (g_free (var), NULL);
#line 217 "application.c"
}

static inline void
_g_list_free__g_free0_ (GList* self)
{
#line 39 "../src/application.vala"
	g_list_free_full (self, (GDestroyNotify) _g_free0_);
#line 225 "application.c"
}

static void
_clocks_application_on_quit_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                       GVariant* parameter,
                                                                       gpointer self)
{
#line 27 "../src/application.vala"
	clocks_application_on_quit_activate ((ClocksApplication*) self);
#line 235 "application.c"
}

static void
_clocks_application_on_add_location_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                               GVariant* parameter,
                                                                               gpointer self)
{
#line 27 "../src/application.vala"
	clocks_application_on_add_location_activate ((ClocksApplication*) self, action, parameter);
#line 245 "application.c"
}

static void
___lambda60_ (ClocksApplication* self)
{
#line 45 "../src/application.vala"
	_g_object_unref0 (self->priv->window);
#line 45 "../src/application.vala"
	self->priv->window = NULL;
#line 255 "application.c"
}

static void
____lambda60__gtk_widget_destroy (GtkWidget* _sender,
                                  gpointer self)
{
#line 44 "../src/application.vala"
	___lambda60_ ((ClocksApplication*) self);
#line 264 "application.c"
}

static void
clocks_application_ensure_window (ClocksApplication* self)
{
	ClocksWindow* _tmp0_;
#line 41 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 42 "../src/application.vala"
	_tmp0_ = self->priv->window;
#line 42 "../src/application.vala"
	if (_tmp0_ == NULL) {
#line 277 "application.c"
		ClocksWindow* _tmp1_;
		ClocksWindow* _tmp2_;
#line 43 "../src/application.vala"
		_tmp1_ = clocks_window_new (self);
#line 43 "../src/application.vala"
		g_object_ref_sink (_tmp1_);
#line 43 "../src/application.vala"
		_g_object_unref0 (self->priv->window);
#line 43 "../src/application.vala"
		self->priv->window = _tmp1_;
#line 44 "../src/application.vala"
		_tmp2_ = self->priv->window;
#line 44 "../src/application.vala"
		g_signal_connect_object ((GtkWidget*) _tmp2_, "destroy", (GCallback) ____lambda60__gtk_widget_destroy, self, 0);
#line 292 "application.c"
	}
}

static void
__lambda61_ (ClocksApplication* self,
             guint32 timestamp)
{
	ClocksWindow* _tmp0_;
	ClocksWindow* _tmp1_;
#line 60 "../src/application.vala"
	clocks_application_ensure_window (self);
#line 61 "../src/application.vala"
	_tmp0_ = self->priv->window;
#line 61 "../src/application.vala"
	clocks_window_show_world (_tmp0_);
#line 62 "../src/application.vala"
	_tmp1_ = self->priv->window;
#line 62 "../src/application.vala"
	gtk_window_present_with_time ((GtkWindow*) _tmp1_, timestamp);
#line 312 "application.c"
}

static void
___lambda61__clocks_search_provider_activate (ClocksSearchProvider* _sender,
                                              guint32 timestamp,
                                              gpointer self)
{
#line 59 "../src/application.vala"
	__lambda61_ ((ClocksApplication*) self, timestamp);
#line 322 "application.c"
}

ClocksApplication*
clocks_application_construct (GType object_type)
{
	ClocksApplication * self = NULL;
	ClocksSearchProvider* _tmp0_;
	ClocksSearchProvider* _tmp1_;
#line 51 "../src/application.vala"
	self = (ClocksApplication*) g_object_new (object_type, "application-id", APP_ID, NULL);
#line 53 "../src/application.vala"
	gtk_window_set_default_icon_name (APP_ID);
#line 55 "../src/application.vala"
	g_application_add_main_option_entries ((GApplication*) self, CLOCKS_APPLICATION_option_entries);
#line 56 "../src/application.vala"
	g_action_map_add_action_entries ((GActionMap*) self, CLOCKS_APPLICATION_action_entries, (gint) G_N_ELEMENTS (CLOCKS_APPLICATION_action_entries), self);
#line 58 "../src/application.vala"
	_tmp0_ = clocks_search_provider_new ();
#line 58 "../src/application.vala"
	_g_object_unref0 (self->priv->search_provider);
#line 58 "../src/application.vala"
	self->priv->search_provider = _tmp0_;
#line 59 "../src/application.vala"
	_tmp1_ = self->priv->search_provider;
#line 59 "../src/application.vala"
	g_signal_connect_object (_tmp1_, "activate", (GCallback) ___lambda61__clocks_search_provider_activate, self, 0);
#line 65 "../src/application.vala"
	(self->priv->system_notifications == NULL) ? NULL : (self->priv->system_notifications = (_g_list_free__g_free0_ (self->priv->system_notifications), NULL));
#line 65 "../src/application.vala"
	self->priv->system_notifications = NULL;
#line 50 "../src/application.vala"
	return self;
#line 355 "application.c"
}

ClocksApplication*
clocks_application_new (void)
{
#line 50 "../src/application.vala"
	return clocks_application_construct (CLOCKS_TYPE_APPLICATION);
#line 363 "application.c"
}

static gboolean
clocks_application_real_dbus_register (GApplication* base,
                                       GDBusConnection* connection,
                                       const gchar* object_path,
                                       GError** error)
{
	ClocksApplication * self;
	GError* _inner_error0_ = NULL;
	gboolean result = FALSE;
#line 68 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 68 "../src/application.vala"
	g_return_val_if_fail (connection != NULL, FALSE);
#line 68 "../src/application.vala"
	g_return_val_if_fail (object_path != NULL, FALSE);
#line 381 "application.c"
	{
		guint _tmp0_ = 0U;
		gchar* _tmp1_;
		gchar* _tmp2_;
		ClocksSearchProvider* _tmp3_;
		guint _tmp4_;
		guint _tmp5_;
#line 70 "../src/application.vala"
		_tmp1_ = g_strconcat (object_path, "/SearchProvider", NULL);
#line 70 "../src/application.vala"
		_tmp2_ = _tmp1_;
#line 70 "../src/application.vala"
		_tmp3_ = self->priv->search_provider;
#line 70 "../src/application.vala"
		_tmp4_ = clocks_search_provider_register_object (_tmp3_, connection, _tmp2_, &_inner_error0_);
#line 70 "../src/application.vala"
		_tmp5_ = _tmp4_;
#line 70 "../src/application.vala"
		_g_free0 (_tmp2_);
#line 70 "../src/application.vala"
		_tmp0_ = _tmp5_;
#line 70 "../src/application.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 405 "application.c"
			gboolean _tmp6_ = FALSE;
#line 70 "../src/application.vala"
			if (_inner_error0_->domain == G_IO_ERROR) {
#line 409 "application.c"
				goto __catch0_g_io_error;
			}
#line 70 "../src/application.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 70 "../src/application.vala"
			g_clear_error (&_inner_error0_);
#line 70 "../src/application.vala"
			return _tmp6_;
#line 418 "application.c"
		}
#line 70 "../src/application.vala"
		self->priv->search_provider_id = _tmp0_;
#line 422 "application.c"
	}
	goto __finally0;
	__catch0_g_io_error:
	{
		GError* _error_ = NULL;
		GError* _tmp7_;
		const gchar* _tmp8_;
#line 69 "../src/application.vala"
		_error_ = _inner_error0_;
#line 69 "../src/application.vala"
		_inner_error0_ = NULL;
#line 72 "../src/application.vala"
		_tmp7_ = _error_;
#line 72 "../src/application.vala"
		_tmp8_ = _tmp7_->message;
#line 72 "../src/application.vala"
		g_printerr ("Could not register search provider service: %s\n", _tmp8_);
#line 69 "../src/application.vala"
		_g_error_free0 (_error_);
#line 442 "application.c"
	}
	__finally0:
#line 69 "../src/application.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 447 "application.c"
		gboolean _tmp9_ = FALSE;
#line 69 "../src/application.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 69 "../src/application.vala"
		g_clear_error (&_inner_error0_);
#line 69 "../src/application.vala"
		return _tmp9_;
#line 455 "application.c"
	}
	{
		ClocksWorldShellWorldClocks* _tmp10_;
		guint _tmp11_ = 0U;
		ClocksWorldShellWorldClocks* _tmp12_;
		guint _tmp13_;
#line 76 "../src/application.vala"
		_tmp10_ = clocks_world_shell_world_clocks_new (connection, object_path);
#line 76 "../src/application.vala"
		_g_object_unref0 (self->priv->world_clocks);
#line 76 "../src/application.vala"
		self->priv->world_clocks = _tmp10_;
#line 77 "../src/application.vala"
		_tmp12_ = self->priv->world_clocks;
#line 77 "../src/application.vala"
		_tmp13_ = clocks_world_shell_world_clocks_register_object (_tmp12_, connection, object_path, &_inner_error0_);
#line 77 "../src/application.vala"
		_tmp11_ = _tmp13_;
#line 77 "../src/application.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 476 "application.c"
			gboolean _tmp14_ = FALSE;
#line 77 "../src/application.vala"
			if (_inner_error0_->domain == G_IO_ERROR) {
#line 480 "application.c"
				goto __catch1_g_io_error;
			}
#line 77 "../src/application.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 77 "../src/application.vala"
			g_clear_error (&_inner_error0_);
#line 77 "../src/application.vala"
			return _tmp14_;
#line 489 "application.c"
		}
#line 77 "../src/application.vala"
		self->priv->world_clocks_id = _tmp11_;
#line 493 "application.c"
	}
	goto __finally1;
	__catch1_g_io_error:
	{
		GError* _error_ = NULL;
		GError* _tmp15_;
		const gchar* _tmp16_;
#line 75 "../src/application.vala"
		_error_ = _inner_error0_;
#line 75 "../src/application.vala"
		_inner_error0_ = NULL;
#line 79 "../src/application.vala"
		_tmp15_ = _error_;
#line 79 "../src/application.vala"
		_tmp16_ = _tmp15_->message;
#line 79 "../src/application.vala"
		g_printerr ("Could not register world clocks service: %s\n", _tmp16_);
#line 75 "../src/application.vala"
		_g_error_free0 (_error_);
#line 513 "application.c"
	}
	__finally1:
#line 75 "../src/application.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 518 "application.c"
		gboolean _tmp17_ = FALSE;
#line 75 "../src/application.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 75 "../src/application.vala"
		g_clear_error (&_inner_error0_);
#line 75 "../src/application.vala"
		return _tmp17_;
#line 526 "application.c"
	}
#line 82 "../src/application.vala"
	result = TRUE;
#line 82 "../src/application.vala"
	return result;
#line 532 "application.c"
}

static void
clocks_application_real_dbus_unregister (GApplication* base,
                                         GDBusConnection* connection,
                                         const gchar* object_path)
{
	ClocksApplication * self;
#line 85 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 85 "../src/application.vala"
	g_return_if_fail (connection != NULL);
#line 85 "../src/application.vala"
	g_return_if_fail (object_path != NULL);
#line 86 "../src/application.vala"
	if (self->priv->search_provider_id != ((guint) 0)) {
#line 87 "../src/application.vala"
		g_dbus_connection_unregister_object (connection, self->priv->search_provider_id);
#line 88 "../src/application.vala"
		self->priv->search_provider_id = (guint) 0;
#line 553 "application.c"
	}
#line 91 "../src/application.vala"
	if (self->priv->world_clocks_id != ((guint) 0)) {
#line 92 "../src/application.vala"
		g_dbus_connection_unregister_object (connection, self->priv->world_clocks_id);
#line 93 "../src/application.vala"
		self->priv->world_clocks_id = (guint) 0;
#line 561 "application.c"
	}
}

static gboolean
__lambda62_ (ClocksApplication* self)
{
	gboolean result = FALSE;
#line 104 "../src/application.vala"
	clocks_application_withdraw_notifications (self);
#line 106 "../src/application.vala"
	result = FALSE;
#line 106 "../src/application.vala"
	return result;
#line 575 "application.c"
}

static gboolean
___lambda62__gtk_widget_focus_in_event (GtkWidget* _sender,
                                        GdkEventFocus* event,
                                        gpointer self)
{
	gboolean result;
	result = __lambda62_ ((ClocksApplication*) self);
#line 103 "../src/application.vala"
	return result;
#line 587 "application.c"
}

static void
clocks_application_real_activate (GApplication* base)
{
	ClocksApplication * self;
	ClocksWindow* _tmp0_;
	ClocksWindow* _tmp1_;
#line 97 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 98 "../src/application.vala"
	G_APPLICATION_CLASS (clocks_application_parent_class)->activate ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 100 "../src/application.vala"
	clocks_application_ensure_window (self);
#line 101 "../src/application.vala"
	_tmp0_ = self->priv->window;
#line 101 "../src/application.vala"
	gtk_window_present ((GtkWindow*) _tmp0_);
#line 103 "../src/application.vala"
	_tmp1_ = self->priv->window;
#line 103 "../src/application.vala"
	g_signal_connect_object ((GtkWidget*) _tmp1_, "focus-in-event", (GCallback) ___lambda62__gtk_widget_focus_in_event, self, 0);
#line 610 "application.c"
}

static void
clocks_application_update_theme (ClocksApplication* self,
                                 GtkSettings* settings)
{
	gchar* theme_name = NULL;
	gchar* _tmp0_ = NULL;
#line 110 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 110 "../src/application.vala"
	g_return_if_fail (settings != NULL);
#line 113 "../src/application.vala"
	g_object_get ((GObject*) settings, "gtk-theme-name", &_tmp0_, NULL);
#line 113 "../src/application.vala"
	_g_free0 (theme_name);
#line 113 "../src/application.vala"
	theme_name = _tmp0_;
#line 114 "../src/application.vala"
	clocks_utils_load_theme_css (theme_name);
#line 110 "../src/application.vala"
	_g_free0 (theme_name);
#line 633 "application.c"
}

static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
#line 117 "../src/application.vala"
	g_atomic_int_inc (&_data4_->_ref_count_);
#line 117 "../src/application.vala"
	return _data4_;
#line 643 "application.c"
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
#line 117 "../src/application.vala"
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
#line 653 "application.c"
		ClocksApplication* self;
#line 117 "../src/application.vala"
		self = _data4_->self;
#line 117 "../src/application.vala"
		_g_object_unref0 (_data4_->settings);
#line 117 "../src/application.vala"
		_g_object_unref0 (self);
#line 117 "../src/application.vala"
		g_slice_free (Block4Data, _data4_);
#line 663 "application.c"
	}
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 121 "../src/application.vala"
	return self ? g_object_ref (self) : NULL;
#line 672 "application.c"
}

static void
__lambda63_ (Block4Data* _data4_)
{
	ClocksApplication* self;
#line 125 "../src/application.vala"
	self = _data4_->self;
#line 126 "../src/application.vala"
	clocks_application_update_theme (self, _data4_->settings);
#line 683 "application.c"
}

static void
___lambda63__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 125 "../src/application.vala"
	__lambda63_ (self);
#line 693 "application.c"
}

static void
clocks_application_real_startup (GApplication* base)
{
	ClocksApplication * self;
	Block4Data* _data4_;
	GtkIconTheme* theme = NULL;
	GtkIconTheme* _tmp0_;
	GtkIconTheme* _tmp1_;
	GtkSettings* _tmp2_;
	GtkSettings* _tmp3_;
	gchar* _tmp4_;
	gchar** _tmp5_;
	gchar** _tmp6_;
	gint _tmp6__length1;
	gchar* _tmp7_;
	gchar** _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar* _tmp10_;
	gchar** _tmp11_;
	gchar** _tmp12_;
	gint _tmp12__length1;
	gchar* _tmp13_;
	gchar** _tmp14_;
	gchar** _tmp15_;
	gint _tmp15__length1;
	gchar* _tmp16_;
	gchar** _tmp17_;
	gchar** _tmp18_;
	gint _tmp18__length1;
	gchar* _tmp19_;
	gchar** _tmp20_;
	gchar** _tmp21_;
	gint _tmp21__length1;
#line 117 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 117 "../src/application.vala"
	_data4_ = g_slice_new0 (Block4Data);
#line 117 "../src/application.vala"
	_data4_->_ref_count_ = 1;
#line 117 "../src/application.vala"
	_data4_->self = g_object_ref (self);
#line 118 "../src/application.vala"
	G_APPLICATION_CLASS (clocks_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 120 "../src/application.vala"
	clocks_utils_load_main_css ();
#line 121 "../src/application.vala"
	_tmp0_ = gtk_icon_theme_get_default ();
#line 121 "../src/application.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 121 "../src/application.vala"
	theme = _tmp1_;
#line 122 "../src/application.vala"
	gtk_icon_theme_add_resource_path (theme, "/org/gnome/clocks/icons");
#line 124 "../src/application.vala"
	_tmp2_ = gtk_settings_get_default ();
#line 124 "../src/application.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 124 "../src/application.vala"
	_data4_->settings = _tmp3_;
#line 125 "../src/application.vala"
	g_signal_connect_data ((GObject*) _data4_->settings, "notify::gtk-theme-name", (GCallback) ___lambda63__g_object_notify, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 128 "../src/application.vala"
	clocks_application_update_theme (self, _data4_->settings);
#line 130 "../src/application.vala"
	_tmp4_ = g_strdup ("<Primary>n");
#line 130 "../src/application.vala"
	_tmp5_ = g_new0 (gchar*, 1 + 1);
#line 130 "../src/application.vala"
	_tmp5_[0] = _tmp4_;
#line 130 "../src/application.vala"
	_tmp6_ = _tmp5_;
#line 130 "../src/application.vala"
	_tmp6__length1 = 1;
#line 130 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.new", _tmp6_);
#line 130 "../src/application.vala"
	_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) g_free), NULL);
#line 131 "../src/application.vala"
	_tmp7_ = g_strdup ("<Primary>a");
#line 131 "../src/application.vala"
	_tmp8_ = g_new0 (gchar*, 1 + 1);
#line 131 "../src/application.vala"
	_tmp8_[0] = _tmp7_;
#line 131 "../src/application.vala"
	_tmp9_ = _tmp8_;
#line 131 "../src/application.vala"
	_tmp9__length1 = 1;
#line 131 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.select-all", _tmp9_);
#line 131 "../src/application.vala"
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
#line 132 "../src/application.vala"
	_tmp10_ = g_strdup ("F10");
#line 132 "../src/application.vala"
	_tmp11_ = g_new0 (gchar*, 1 + 1);
#line 132 "../src/application.vala"
	_tmp11_[0] = _tmp10_;
#line 132 "../src/application.vala"
	_tmp12_ = _tmp11_;
#line 132 "../src/application.vala"
	_tmp12__length1 = 1;
#line 132 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.show-primary-menu", _tmp12_);
#line 132 "../src/application.vala"
	_tmp12_ = (_vala_array_free (_tmp12_, _tmp12__length1, (GDestroyNotify) g_free), NULL);
#line 133 "../src/application.vala"
	_tmp13_ = g_strdup ("<Primary>F10");
#line 133 "../src/application.vala"
	_tmp14_ = g_new0 (gchar*, 1 + 1);
#line 133 "../src/application.vala"
	_tmp14_[0] = _tmp13_;
#line 133 "../src/application.vala"
	_tmp15_ = _tmp14_;
#line 133 "../src/application.vala"
	_tmp15__length1 = 1;
#line 133 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.show-help-overlay", _tmp15_);
#line 133 "../src/application.vala"
	_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
#line 134 "../src/application.vala"
	_tmp16_ = g_strdup ("F1");
#line 134 "../src/application.vala"
	_tmp17_ = g_new0 (gchar*, 1 + 1);
#line 134 "../src/application.vala"
	_tmp17_[0] = _tmp16_;
#line 134 "../src/application.vala"
	_tmp18_ = _tmp17_;
#line 134 "../src/application.vala"
	_tmp18__length1 = 1;
#line 134 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.help", _tmp18_);
#line 134 "../src/application.vala"
	_tmp18_ = (_vala_array_free (_tmp18_, _tmp18__length1, (GDestroyNotify) g_free), NULL);
#line 135 "../src/application.vala"
	_tmp19_ = g_strdup ("<Primary>q");
#line 135 "../src/application.vala"
	_tmp20_ = g_new0 (gchar*, 1 + 1);
#line 135 "../src/application.vala"
	_tmp20_[0] = _tmp19_;
#line 135 "../src/application.vala"
	_tmp21_ = _tmp20_;
#line 135 "../src/application.vala"
	_tmp21__length1 = 1;
#line 135 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit", _tmp21_);
#line 135 "../src/application.vala"
	_tmp21_ = (_vala_array_free (_tmp21_, _tmp21__length1, (GDestroyNotify) g_free), NULL);
#line 117 "../src/application.vala"
	_g_object_unref0 (theme);
#line 117 "../src/application.vala"
	block4_data_unref (_data4_);
#line 117 "../src/application.vala"
	_data4_ = NULL;
#line 850 "application.c"
}

static gint
clocks_application_real_handle_local_options (GApplication* base,
                                              GVariantDict* options)
{
	ClocksApplication * self;
	gint result = 0;
#line 138 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 138 "../src/application.vala"
	g_return_val_if_fail (options != NULL, 0);
#line 139 "../src/application.vala"
	if (g_variant_dict_contains (options, "version")) {
#line 865 "application.c"
		const gchar* _tmp0_;
#line 140 "../src/application.vala"
		_tmp0_ = g_get_application_name ();
#line 140 "../src/application.vala"
		g_print ("%s %s\n", _tmp0_, VERSION);
#line 141 "../src/application.vala"
		result = 0;
#line 141 "../src/application.vala"
		return result;
#line 875 "application.c"
	}
#line 144 "../src/application.vala"
	result = -1;
#line 144 "../src/application.vala"
	return result;
#line 881 "application.c"
}

static gpointer
_gweather_location_ref0 (gpointer self)
{
#line 156 "../src/application.vala"
	return self ? gweather_location_ref (self) : NULL;
#line 889 "application.c"
}

void
clocks_application_on_add_location_activate (ClocksApplication* self,
                                             GSimpleAction* action,
                                             GVariant* parameter)
{
	ClocksWindow* _tmp0_;
	ClocksWindow* _tmp1_;
	GWeatherLocation* world = NULL;
	GWeatherLocation* _tmp2_;
	GWeatherLocation* _tmp3_;
	GWeatherLocation* location = NULL;
	GWeatherLocation* _tmp4_;
	GVariant* _tmp5_;
	GVariant* _tmp6_;
	GWeatherLocation* _tmp7_;
	GWeatherLocation* _tmp8_;
	GWeatherLocation* _tmp9_;
#line 147 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 147 "../src/application.vala"
	g_return_if_fail (action != NULL);
#line 148 "../src/application.vala"
	if (parameter == NULL) {
#line 149 "../src/application.vala"
		return;
#line 917 "application.c"
	}
#line 152 "../src/application.vala"
	clocks_application_ensure_window (self);
#line 153 "../src/application.vala"
	_tmp0_ = self->priv->window;
#line 153 "../src/application.vala"
	clocks_window_show_world (_tmp0_);
#line 154 "../src/application.vala"
	_tmp1_ = self->priv->window;
#line 154 "../src/application.vala"
	gtk_window_present ((GtkWindow*) _tmp1_);
#line 156 "../src/application.vala"
	_tmp2_ = gweather_location_get_world ();
#line 156 "../src/application.vala"
	_tmp3_ = _gweather_location_ref0 (_tmp2_);
#line 156 "../src/application.vala"
	world = _tmp3_;
#line 157 "../src/application.vala"
	_tmp4_ = world;
#line 157 "../src/application.vala"
	_tmp5_ = g_variant_get_child_value (parameter, (gsize) 0);
#line 157 "../src/application.vala"
	_tmp6_ = _tmp5_;
#line 157 "../src/application.vala"
	_tmp7_ = gweather_location_deserialize (_tmp4_, _tmp6_);
#line 157 "../src/application.vala"
	_tmp8_ = _tmp7_;
#line 157 "../src/application.vala"
	_g_variant_unref0 (_tmp6_);
#line 157 "../src/application.vala"
	location = _tmp8_;
#line 158 "../src/application.vala"
	_tmp9_ = location;
#line 158 "../src/application.vala"
	if (_tmp9_ != NULL) {
#line 953 "application.c"
		ClocksWindow* _tmp10_;
		GWeatherLocation* _tmp11_;
#line 159 "../src/application.vala"
		_tmp10_ = self->priv->window;
#line 159 "../src/application.vala"
		_tmp11_ = location;
#line 159 "../src/application.vala"
		clocks_window_add_world_location (_tmp10_, _tmp11_);
#line 962 "application.c"
	}
#line 147 "../src/application.vala"
	_gweather_location_unref0 (location);
#line 147 "../src/application.vala"
	_gweather_location_unref0 (world);
#line 968 "application.c"
}

void
clocks_application_send_notification (ClocksApplication* self,
                                      const gchar* notification_id,
                                      GNotification* notification)
{
	gchar* _tmp0_;
#line 163 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 163 "../src/application.vala"
	g_return_if_fail (notification_id != NULL);
#line 163 "../src/application.vala"
	g_return_if_fail (notification != NULL);
#line 164 "../src/application.vala"
	g_application_send_notification ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication), notification_id, notification);
#line 166 "../src/application.vala"
	_tmp0_ = g_strdup (notification_id);
#line 166 "../src/application.vala"
	self->priv->system_notifications = g_list_append (self->priv->system_notifications, _tmp0_);
#line 989 "application.c"
}

static void
clocks_application_withdraw_notifications (ClocksApplication* self)
{
	GList* _tmp0_;
#line 169 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 170 "../src/application.vala"
	_tmp0_ = self->priv->system_notifications;
#line 1000 "application.c"
	{
		GList* notification_collection = NULL;
		GList* notification_it = NULL;
#line 170 "../src/application.vala"
		notification_collection = _tmp0_;
#line 170 "../src/application.vala"
		for (notification_it = notification_collection; notification_it != NULL; notification_it = notification_it->next) {
#line 1008 "application.c"
			gchar* _tmp1_;
			gchar* notification = NULL;
#line 170 "../src/application.vala"
			_tmp1_ = g_strdup ((const gchar*) notification_it->data);
#line 170 "../src/application.vala"
			notification = _tmp1_;
#line 1015 "application.c"
			{
				const gchar* _tmp2_;
#line 171 "../src/application.vala"
				_tmp2_ = notification;
#line 171 "../src/application.vala"
				g_application_withdraw_notification ((GApplication*) self, _tmp2_);
#line 170 "../src/application.vala"
				_g_free0 (notification);
#line 1024 "application.c"
			}
		}
	}
}

static void
clocks_application_real_shutdown (GApplication* base)
{
	ClocksApplication * self;
#line 175 "../src/application.vala"
	self = (ClocksApplication*) base;
#line 176 "../src/application.vala"
	G_APPLICATION_CLASS (clocks_application_parent_class)->shutdown ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 178 "../src/application.vala"
	clocks_application_withdraw_notifications (self);
#line 1040 "application.c"
}

static void
clocks_application_on_quit_activate (ClocksApplication* self)
{
#line 181 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 182 "../src/application.vala"
	g_application_quit ((GApplication*) self);
#line 1050 "application.c"
}

static void
clocks_application_class_init (ClocksApplicationClass * klass,
                               gpointer klass_data)
{
#line 21 "../src/application.vala"
	clocks_application_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/application.vala"
	g_type_class_adjust_private_offset (klass, &ClocksApplication_private_offset);
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->dbus_register = (gboolean (*) (GApplication*, GDBusConnection*, const gchar*, GError**)) clocks_application_real_dbus_register;
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->dbus_unregister = (void (*) (GApplication*, GDBusConnection*, const gchar*)) clocks_application_real_dbus_unregister;
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) clocks_application_real_activate;
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->startup = (void (*) (GApplication*)) clocks_application_real_startup;
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->handle_local_options = (gint (*) (GApplication*, GVariantDict*)) clocks_application_real_handle_local_options;
#line 21 "../src/application.vala"
	((GApplicationClass *) klass)->shutdown = (void (*) (GApplication*)) clocks_application_real_shutdown;
#line 21 "../src/application.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_application_finalize;
#line 1075 "application.c"
}

static void
clocks_application_instance_init (ClocksApplication * self,
                                  gpointer klass)
{
#line 21 "../src/application.vala"
	self->priv = clocks_application_get_instance_private (self);
#line 35 "../src/application.vala"
	self->priv->search_provider_id = (guint) 0;
#line 37 "../src/application.vala"
	self->priv->world_clocks_id = (guint) 0;
#line 1088 "application.c"
}

static void
clocks_application_finalize (GObject * obj)
{
	ClocksApplication * self;
#line 21 "../src/application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_TYPE_APPLICATION, ClocksApplication);
#line 34 "../src/application.vala"
	_g_object_unref0 (self->priv->search_provider);
#line 36 "../src/application.vala"
	_g_object_unref0 (self->priv->world_clocks);
#line 38 "../src/application.vala"
	_g_object_unref0 (self->priv->window);
#line 39 "../src/application.vala"
	(self->priv->system_notifications == NULL) ? NULL : (self->priv->system_notifications = (_g_list_free__g_free0_ (self->priv->system_notifications), NULL));
#line 21 "../src/application.vala"
	G_OBJECT_CLASS (clocks_application_parent_class)->finalize (obj);
#line 1107 "application.c"
}

GType
clocks_application_get_type (void)
{
	static volatile gsize clocks_application_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksApplication), 0, (GInstanceInitFunc) clocks_application_instance_init, NULL };
		GType clocks_application_type_id;
		clocks_application_type_id = g_type_register_static (gtk_application_get_type (), "ClocksApplication", &g_define_type_info, 0);
		ClocksApplication_private_offset = g_type_add_instance_private (clocks_application_type_id, sizeof (ClocksApplicationPrivate));
		g_once_init_leave (&clocks_application_type_id__volatile, clocks_application_type_id);
	}
	return clocks_application_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

