/* geocoding.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from geocoding.vala, do not modify */

/*
 * Copyright (C) 2013  Evgeny Bobkin <evgen.ibqn@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <glib-object.h>
#include <geoclue.h>
#include <libgweather/gweather.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include "config.h"
#include <geocode-glib/geocode-glib.h>

#define CLOCKS_GEO_TYPE_INFO (clocks_geo_info_get_type ())
#define CLOCKS_GEO_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_GEO_TYPE_INFO, ClocksGeoInfo))
#define CLOCKS_GEO_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_GEO_TYPE_INFO, ClocksGeoInfoClass))
#define CLOCKS_GEO_IS_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_GEO_TYPE_INFO))
#define CLOCKS_GEO_IS_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_GEO_TYPE_INFO))
#define CLOCKS_GEO_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_GEO_TYPE_INFO, ClocksGeoInfoClass))

typedef struct _ClocksGeoInfo ClocksGeoInfo;
typedef struct _ClocksGeoInfoClass ClocksGeoInfoClass;
typedef struct _ClocksGeoInfoPrivate ClocksGeoInfoPrivate;
enum  {
	CLOCKS_GEO_INFO_0_PROPERTY,
	CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY,
	CLOCKS_GEO_INFO_NUM_PROPERTIES
};
static GParamSpec* clocks_geo_info_properties[CLOCKS_GEO_INFO_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gweather_location_unref0(var) ((var == NULL) ? NULL : (var = (gweather_location_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ClocksGeoInfoSeekData ClocksGeoInfoSeekData;
typedef struct _ClocksGeoInfoOnLocationUpdatedData ClocksGeoInfoOnLocationUpdatedData;
typedef struct _ClocksGeoInfoSeekCountryCodeData ClocksGeoInfoSeekCountryCodeData;
typedef struct _ClocksGeoInfoSearchLocationsData ClocksGeoInfoSearchLocationsData;
#define _gweather_timezone_unref0(var) ((var == NULL) ? NULL : (var = (gweather_timezone_unref (var), NULL)))
enum  {
	CLOCKS_GEO_INFO_LOCATION_CHANGED_SIGNAL,
	CLOCKS_GEO_INFO_NUM_SIGNALS
};
static guint clocks_geo_info_signals[CLOCKS_GEO_INFO_NUM_SIGNALS] = {0};

struct _ClocksGeoInfo {
	GObject parent_instance;
	ClocksGeoInfoPrivate * priv;
};

struct _ClocksGeoInfoClass {
	GObjectClass parent_class;
};

struct _ClocksGeoInfoPrivate {
	GClueLocation* _geo_location;
	GWeatherLocation* found_location;
	gchar* country_code;
	GClueSimple* simple;
	gdouble minimal_distance;
};

struct _ClocksGeoInfoSeekData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ClocksGeoInfo* self;
	GClueSimple* _tmp0_;
	GClueSimple* _tmp1_;
	GClueSimple* _tmp2_;
	GError* e;
	GError* _tmp3_;
	const gchar* _tmp4_;
	GClueSimple* _tmp5_;
	GError* _inner_error0_;
};

struct _ClocksGeoInfoOnLocationUpdatedData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ClocksGeoInfo* self;
	GClueSimple* _tmp0_;
	GClueLocationProxy* _tmp1_;
	GWeatherLocation* _tmp2_;
	GWeatherLocation* _tmp3_;
	GWeatherLocation* _tmp4_;
};

struct _ClocksGeoInfoSeekCountryCodeData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ClocksGeoInfo* self;
	GeocodeLocation* location;
	GClueLocation* _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_;
	GClueLocation* _tmp3_;
	gdouble _tmp4_;
	gdouble _tmp5_;
	GeocodeLocation* _tmp6_;
	GeocodeReverse* reverse;
	GeocodeReverse* _tmp7_;
	GeocodePlace* place;
	GeocodePlace* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	GError* e;
	GError* _tmp11_;
	const gchar* _tmp12_;
	GError* _inner_error0_;
};

struct _ClocksGeoInfoSearchLocationsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ClocksGeoInfo* self;
	GWeatherLocation* location;
	const gchar* _tmp0_;
	gchar* loc_country_code;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GWeatherLocation** locations;
	GWeatherLocation** _tmp6_;
	GWeatherLocation** _tmp7_;
	GWeatherLocation** _tmp8_;
	gint _tmp8__length1;
	gint locations_length1;
	gint _locations_size_;
	GWeatherLocation** _tmp9_;
	gint _tmp9__length1;
	gint i;
	gboolean _tmp10_;
	gint _tmp11_;
	GWeatherLocation** _tmp12_;
	gint _tmp12__length1;
	GWeatherLocation** _tmp13_;
	gint _tmp13__length1;
	GWeatherLocation* _tmp14_;
	GWeatherLocation** _tmp15_;
	gint _tmp15__length1;
	GWeatherLocation* _tmp16_;
	gdouble latitude;
	gdouble longitude;
	gdouble distance;
	GWeatherLocation** _tmp17_;
	gint _tmp17__length1;
	GWeatherLocation* _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	GClueLocation* _tmp21_;
	gdouble _tmp22_;
	gdouble _tmp23_;
	GClueLocation* _tmp24_;
	gdouble _tmp25_;
	gdouble _tmp26_;
	GWeatherLocation** _tmp27_;
	gint _tmp27__length1;
	GWeatherLocation* _tmp28_;
	GWeatherLocation* _tmp29_;
	GWeatherLocation** _tmp30_;
	gint _tmp30__length1;
	GWeatherLocation* _tmp31_;
};

static gint ClocksGeoInfo_private_offset;
static gpointer clocks_geo_info_parent_class = NULL;

GType clocks_geo_info_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksGeoInfo, g_object_unref)
ClocksGeoInfo* clocks_geo_info_new (void);
ClocksGeoInfo* clocks_geo_info_construct (GType object_type);
static void clocks_geo_info_seek_data_free (gpointer _data);
void clocks_geo_info_seek (ClocksGeoInfo* self,
                           GAsyncReadyCallback _callback_,
                           gpointer _user_data_);
void clocks_geo_info_seek_finish (ClocksGeoInfo* self,
                                  GAsyncResult* _res_);
static gboolean clocks_geo_info_seek_co (ClocksGeoInfoSeekData* _data_);
static void clocks_geo_info_seek_ready (GObject* source_object,
                                 GAsyncResult* _res_,
                                 gpointer _user_data_);
static void __lambda23_ (ClocksGeoInfo* self);
void clocks_geo_info_on_location_updated (ClocksGeoInfo* self,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
void clocks_geo_info_on_location_updated_finish (ClocksGeoInfo* self,
                                                 GAsyncResult* _res_);
static void ___lambda23__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void clocks_geo_info_on_location_updated_data_free (gpointer _data);
static gboolean clocks_geo_info_on_location_updated_co (ClocksGeoInfoOnLocationUpdatedData* _data_);
static void clocks_geo_info_set_geo_location (ClocksGeoInfo* self,
                                       GClueLocation* value);
static void clocks_geo_info_seek_country_code (ClocksGeoInfo* self,
                                        GAsyncReadyCallback _callback_,
                                        gpointer _user_data_);
static void clocks_geo_info_seek_country_code_finish (ClocksGeoInfo* self,
                                               GAsyncResult* _res_);
static void clocks_geo_info_on_location_updated_ready (GObject* source_object,
                                                GAsyncResult* _res_,
                                                gpointer _user_data_);
static void clocks_geo_info_search_locations (ClocksGeoInfo* self,
                                       GWeatherLocation* location,
                                       GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
static void clocks_geo_info_search_locations_finish (ClocksGeoInfo* self,
                                              GAsyncResult* _res_);
static void clocks_geo_info_seek_country_code_data_free (gpointer _data);
static gboolean clocks_geo_info_seek_country_code_co (ClocksGeoInfoSeekCountryCodeData* _data_);
GClueLocation* clocks_geo_info_get_geo_location (ClocksGeoInfo* self);
static void clocks_geo_info_seek_country_code_ready (GObject* source_object,
                                              GAsyncResult* _res_,
                                              gpointer _user_data_);
static gdouble clocks_geo_info_deg_to_rad (ClocksGeoInfo* self,
                                    gdouble deg);
static gdouble clocks_geo_info_get_distance (ClocksGeoInfo* self,
                                      gdouble latitude1,
                                      gdouble longitude1,
                                      gdouble latitude2,
                                      gdouble longitude2);
static void clocks_geo_info_search_locations_data_free (gpointer _data);
static gboolean clocks_geo_info_search_locations_co (ClocksGeoInfoSearchLocationsData* _data_);
static GWeatherLocation** _vala_array_dup1 (GWeatherLocation** self,
                                     int length);
static void clocks_geo_info_search_locations_ready (GObject* source_object,
                                             GAsyncResult* _res_,
                                             gpointer _user_data_);
gboolean clocks_geo_info_is_location_similar (ClocksGeoInfo* self,
                                              GWeatherLocation* location);
static void clocks_geo_info_finalize (GObject * obj);
static void _vala_clocks_geo_info_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec);
static void _vala_clocks_geo_info_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static inline gpointer
clocks_geo_info_get_instance_private (ClocksGeoInfo* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksGeoInfo_private_offset);
}

ClocksGeoInfo*
clocks_geo_info_construct (GType object_type)
{
	ClocksGeoInfo * self = NULL;
#line 32 "../src/geocoding.vala"
	self = (ClocksGeoInfo*) g_object_new (object_type, NULL);
#line 33 "../src/geocoding.vala"
	_g_free0 (self->priv->country_code);
#line 33 "../src/geocoding.vala"
	self->priv->country_code = NULL;
#line 34 "../src/geocoding.vala"
	_gweather_location_unref0 (self->priv->found_location);
#line 34 "../src/geocoding.vala"
	self->priv->found_location = NULL;
#line 35 "../src/geocoding.vala"
	self->priv->minimal_distance = 1000.0;
#line 32 "../src/geocoding.vala"
	return self;
#line 302 "geocoding.c"
}

ClocksGeoInfo*
clocks_geo_info_new (void)
{
#line 32 "../src/geocoding.vala"
	return clocks_geo_info_construct (CLOCKS_GEO_TYPE_INFO);
#line 310 "geocoding.c"
}

static void
clocks_geo_info_seek_data_free (gpointer _data)
{
	ClocksGeoInfoSeekData* _data_;
	_data_ = _data;
#line 22 "../src/geocoding.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/geocoding.vala"
	g_slice_free (ClocksGeoInfoSeekData, _data_);
#line 322 "geocoding.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "../src/geocoding.vala"
	return self ? g_object_ref (self) : NULL;
#line 330 "geocoding.c"
}

void
clocks_geo_info_seek (ClocksGeoInfo* self,
                      GAsyncReadyCallback _callback_,
                      gpointer _user_data_)
{
	ClocksGeoInfoSeekData* _data_;
	ClocksGeoInfo* _tmp0_;
#line 22 "../src/geocoding.vala"
	_data_ = g_slice_new0 (ClocksGeoInfoSeekData);
#line 22 "../src/geocoding.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/geocoding.vala"
	g_task_set_task_data (_data_->_async_result, _data_, clocks_geo_info_seek_data_free);
#line 22 "../src/geocoding.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/geocoding.vala"
	_data_->self = _tmp0_;
#line 22 "../src/geocoding.vala"
	clocks_geo_info_seek_co (_data_);
#line 352 "geocoding.c"
}

void
clocks_geo_info_seek_finish (ClocksGeoInfo* self,
                             GAsyncResult* _res_)
{
	ClocksGeoInfoSeekData* _data_;
#line 22 "../src/geocoding.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 362 "geocoding.c"
}

static void
clocks_geo_info_seek_ready (GObject* source_object,
                            GAsyncResult* _res_,
                            gpointer _user_data_)
{
	ClocksGeoInfoSeekData* _data_;
#line 40 "../src/geocoding.vala"
	_data_ = _user_data_;
#line 40 "../src/geocoding.vala"
	_data_->_source_object_ = source_object;
#line 40 "../src/geocoding.vala"
	_data_->_res_ = _res_;
#line 40 "../src/geocoding.vala"
	clocks_geo_info_seek_co (_data_);
#line 379 "geocoding.c"
}

static void
__lambda23_ (ClocksGeoInfo* self)
{
#line 47 "../src/geocoding.vala"
	clocks_geo_info_on_location_updated (self, NULL, NULL);
#line 387 "geocoding.c"
}

static void
___lambda23__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 46 "../src/geocoding.vala"
	__lambda23_ ((ClocksGeoInfo*) self);
#line 397 "geocoding.c"
}

static gboolean
clocks_geo_info_seek_co (ClocksGeoInfoSeekData* _data_)
{
#line 38 "../src/geocoding.vala"
	switch (_data_->_state_) {
#line 38 "../src/geocoding.vala"
		case 0:
#line 407 "geocoding.c"
		goto _state_0;
#line 38 "../src/geocoding.vala"
		case 1:
#line 411 "geocoding.c"
		goto _state_1;
		default:
#line 38 "../src/geocoding.vala"
		g_assert_not_reached ();
#line 416 "geocoding.c"
	}
	_state_0:
	{
#line 40 "../src/geocoding.vala"
		_data_->_state_ = 1;
#line 40 "../src/geocoding.vala"
		gclue_simple_new (APP_ID, GCLUE_ACCURACY_LEVEL_CITY, NULL, clocks_geo_info_seek_ready, _data_);
#line 40 "../src/geocoding.vala"
		return FALSE;
#line 426 "geocoding.c"
		_state_1:
#line 40 "../src/geocoding.vala"
		_data_->_tmp1_ = gclue_simple_new_finish (_data_->_res_, &_data_->_inner_error0_);
#line 40 "../src/geocoding.vala"
		_data_->_tmp0_ = _data_->_tmp1_;
#line 40 "../src/geocoding.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 434 "geocoding.c"
			goto __catch2_g_error;
		}
#line 40 "../src/geocoding.vala"
		_data_->_tmp2_ = _data_->_tmp0_;
#line 40 "../src/geocoding.vala"
		_data_->_tmp0_ = NULL;
#line 40 "../src/geocoding.vala"
		_g_object_unref0 (_data_->self->priv->simple);
#line 40 "../src/geocoding.vala"
		_data_->self->priv->simple = _data_->_tmp2_;
#line 39 "../src/geocoding.vala"
		_g_object_unref0 (_data_->_tmp0_);
#line 447 "geocoding.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
#line 39 "../src/geocoding.vala"
		_data_->e = _data_->_inner_error0_;
#line 39 "../src/geocoding.vala"
		_data_->_inner_error0_ = NULL;
#line 42 "../src/geocoding.vala"
		_data_->_tmp3_ = _data_->e;
#line 42 "../src/geocoding.vala"
		_data_->_tmp4_ = _data_->_tmp3_->message;
#line 42 "../src/geocoding.vala"
		g_warning ("geocoding.vala:42: Failed to connect to GeoClue2 service: %s", _data_->_tmp4_);
#line 43 "../src/geocoding.vala"
		_g_error_free0 (_data_->e);
#line 43 "../src/geocoding.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 43 "../src/geocoding.vala"
		if (_data_->_state_ != 0) {
#line 43 "../src/geocoding.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 43 "../src/geocoding.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 472 "geocoding.c"
			}
		}
#line 43 "../src/geocoding.vala"
		g_object_unref (_data_->_async_result);
#line 43 "../src/geocoding.vala"
		return FALSE;
#line 479 "geocoding.c"
	}
	__finally2:
#line 39 "../src/geocoding.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 39 "../src/geocoding.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 39 "../src/geocoding.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 39 "../src/geocoding.vala"
		g_object_unref (_data_->_async_result);
#line 39 "../src/geocoding.vala"
		return FALSE;
#line 492 "geocoding.c"
	}
#line 46 "../src/geocoding.vala"
	_data_->_tmp5_ = _data_->self->priv->simple;
#line 46 "../src/geocoding.vala"
	g_signal_connect_object ((GObject*) _data_->_tmp5_, "notify::location", (GCallback) ___lambda23__g_object_notify, _data_->self, 0);
#line 50 "../src/geocoding.vala"
	clocks_geo_info_on_location_updated (_data_->self, NULL, NULL);
#line 38 "../src/geocoding.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 38 "../src/geocoding.vala"
	if (_data_->_state_ != 0) {
#line 38 "../src/geocoding.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 38 "../src/geocoding.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 508 "geocoding.c"
		}
	}
#line 38 "../src/geocoding.vala"
	g_object_unref (_data_->_async_result);
#line 38 "../src/geocoding.vala"
	return FALSE;
#line 515 "geocoding.c"
}

static void
clocks_geo_info_on_location_updated_data_free (gpointer _data)
{
	ClocksGeoInfoOnLocationUpdatedData* _data_;
	_data_ = _data;
#line 22 "../src/geocoding.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/geocoding.vala"
	g_slice_free (ClocksGeoInfoOnLocationUpdatedData, _data_);
#line 527 "geocoding.c"
}

void
clocks_geo_info_on_location_updated (ClocksGeoInfo* self,
                                     GAsyncReadyCallback _callback_,
                                     gpointer _user_data_)
{
	ClocksGeoInfoOnLocationUpdatedData* _data_;
	ClocksGeoInfo* _tmp0_;
#line 22 "../src/geocoding.vala"
	_data_ = g_slice_new0 (ClocksGeoInfoOnLocationUpdatedData);
#line 22 "../src/geocoding.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/geocoding.vala"
	g_task_set_task_data (_data_->_async_result, _data_, clocks_geo_info_on_location_updated_data_free);
#line 22 "../src/geocoding.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/geocoding.vala"
	_data_->self = _tmp0_;
#line 22 "../src/geocoding.vala"
	clocks_geo_info_on_location_updated_co (_data_);
#line 549 "geocoding.c"
}

void
clocks_geo_info_on_location_updated_finish (ClocksGeoInfo* self,
                                            GAsyncResult* _res_)
{
	ClocksGeoInfoOnLocationUpdatedData* _data_;
#line 22 "../src/geocoding.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 559 "geocoding.c"
}

static void
clocks_geo_info_on_location_updated_ready (GObject* source_object,
                                           GAsyncResult* _res_,
                                           gpointer _user_data_)
{
	ClocksGeoInfoOnLocationUpdatedData* _data_;
#line 56 "../src/geocoding.vala"
	_data_ = _user_data_;
#line 56 "../src/geocoding.vala"
	_data_->_source_object_ = source_object;
#line 56 "../src/geocoding.vala"
	_data_->_res_ = _res_;
#line 56 "../src/geocoding.vala"
	clocks_geo_info_on_location_updated_co (_data_);
#line 576 "geocoding.c"
}

static gboolean
clocks_geo_info_on_location_updated_co (ClocksGeoInfoOnLocationUpdatedData* _data_)
{
#line 53 "../src/geocoding.vala"
	switch (_data_->_state_) {
#line 53 "../src/geocoding.vala"
		case 0:
#line 586 "geocoding.c"
		goto _state_0;
#line 53 "../src/geocoding.vala"
		case 1:
#line 590 "geocoding.c"
		goto _state_1;
#line 53 "../src/geocoding.vala"
		case 2:
#line 594 "geocoding.c"
		goto _state_2;
		default:
#line 53 "../src/geocoding.vala"
		g_assert_not_reached ();
#line 599 "geocoding.c"
	}
	_state_0:
#line 54 "../src/geocoding.vala"
	_data_->_tmp0_ = _data_->self->priv->simple;
#line 54 "../src/geocoding.vala"
	_data_->_tmp1_ = gclue_simple_get_location (_data_->_tmp0_);
#line 54 "../src/geocoding.vala"
	clocks_geo_info_set_geo_location (_data_->self, (GClueLocation*) _data_->_tmp1_);
#line 56 "../src/geocoding.vala"
	_data_->_state_ = 1;
#line 56 "../src/geocoding.vala"
	clocks_geo_info_seek_country_code (_data_->self, clocks_geo_info_on_location_updated_ready, _data_);
#line 56 "../src/geocoding.vala"
	return FALSE;
#line 614 "geocoding.c"
	_state_1:
#line 56 "../src/geocoding.vala"
	clocks_geo_info_seek_country_code_finish (_data_->self, _data_->_res_);
#line 58 "../src/geocoding.vala"
	_data_->_tmp2_ = gweather_location_get_world ();
#line 58 "../src/geocoding.vala"
	_data_->_state_ = 2;
#line 58 "../src/geocoding.vala"
	clocks_geo_info_search_locations (_data_->self, _data_->_tmp2_, clocks_geo_info_on_location_updated_ready, _data_);
#line 58 "../src/geocoding.vala"
	return FALSE;
#line 626 "geocoding.c"
	_state_2:
#line 58 "../src/geocoding.vala"
	clocks_geo_info_search_locations_finish (_data_->self, _data_->_res_);
#line 60 "../src/geocoding.vala"
	_data_->_tmp3_ = _data_->self->priv->found_location;
#line 60 "../src/geocoding.vala"
	if (_data_->_tmp3_ != NULL) {
#line 61 "../src/geocoding.vala"
		_data_->_tmp4_ = _data_->self->priv->found_location;
#line 61 "../src/geocoding.vala"
		g_signal_emit (_data_->self, clocks_geo_info_signals[CLOCKS_GEO_INFO_LOCATION_CHANGED_SIGNAL], 0, _data_->_tmp4_);
#line 638 "geocoding.c"
	}
#line 53 "../src/geocoding.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 53 "../src/geocoding.vala"
	if (_data_->_state_ != 0) {
#line 53 "../src/geocoding.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 53 "../src/geocoding.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 648 "geocoding.c"
		}
	}
#line 53 "../src/geocoding.vala"
	g_object_unref (_data_->_async_result);
#line 53 "../src/geocoding.vala"
	return FALSE;
#line 655 "geocoding.c"
}

static void
clocks_geo_info_seek_country_code_data_free (gpointer _data)
{
	ClocksGeoInfoSeekCountryCodeData* _data_;
	_data_ = _data;
#line 22 "../src/geocoding.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/geocoding.vala"
	g_slice_free (ClocksGeoInfoSeekCountryCodeData, _data_);
#line 667 "geocoding.c"
}

static void
clocks_geo_info_seek_country_code (ClocksGeoInfo* self,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_)
{
	ClocksGeoInfoSeekCountryCodeData* _data_;
	ClocksGeoInfo* _tmp0_;
#line 22 "../src/geocoding.vala"
	_data_ = g_slice_new0 (ClocksGeoInfoSeekCountryCodeData);
#line 22 "../src/geocoding.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/geocoding.vala"
	g_task_set_task_data (_data_->_async_result, _data_, clocks_geo_info_seek_country_code_data_free);
#line 22 "../src/geocoding.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/geocoding.vala"
	_data_->self = _tmp0_;
#line 22 "../src/geocoding.vala"
	clocks_geo_info_seek_country_code_co (_data_);
#line 689 "geocoding.c"
}

static void
clocks_geo_info_seek_country_code_finish (ClocksGeoInfo* self,
                                          GAsyncResult* _res_)
{
	ClocksGeoInfoSeekCountryCodeData* _data_;
#line 22 "../src/geocoding.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 699 "geocoding.c"
}

static void
clocks_geo_info_seek_country_code_ready (GObject* source_object,
                                         GAsyncResult* _res_,
                                         gpointer _user_data_)
{
	ClocksGeoInfoSeekCountryCodeData* _data_;
#line 70 "../src/geocoding.vala"
	_data_ = _user_data_;
#line 70 "../src/geocoding.vala"
	_data_->_source_object_ = source_object;
#line 70 "../src/geocoding.vala"
	_data_->_res_ = _res_;
#line 70 "../src/geocoding.vala"
	clocks_geo_info_seek_country_code_co (_data_);
#line 716 "geocoding.c"
}

static gboolean
clocks_geo_info_seek_country_code_co (ClocksGeoInfoSeekCountryCodeData* _data_)
{
#line 65 "../src/geocoding.vala"
	switch (_data_->_state_) {
#line 65 "../src/geocoding.vala"
		case 0:
#line 726 "geocoding.c"
		goto _state_0;
#line 65 "../src/geocoding.vala"
		case 1:
#line 730 "geocoding.c"
		goto _state_1;
		default:
#line 65 "../src/geocoding.vala"
		g_assert_not_reached ();
#line 735 "geocoding.c"
	}
	_state_0:
#line 66 "../src/geocoding.vala"
	_data_->_tmp0_ = _data_->self->priv->_geo_location;
#line 66 "../src/geocoding.vala"
	g_object_get (_data_->_tmp0_, "latitude", &_data_->_tmp1_, NULL);
#line 66 "../src/geocoding.vala"
	_data_->_tmp2_ = _data_->_tmp1_;
#line 66 "../src/geocoding.vala"
	_data_->_tmp3_ = _data_->self->priv->_geo_location;
#line 66 "../src/geocoding.vala"
	g_object_get (_data_->_tmp3_, "longitude", &_data_->_tmp4_, NULL);
#line 66 "../src/geocoding.vala"
	_data_->_tmp5_ = _data_->_tmp4_;
#line 66 "../src/geocoding.vala"
	_data_->_tmp6_ = geocode_location_new (_data_->_tmp2_, _data_->_tmp5_, (gdouble) GEOCODE_LOCATION_ACCURACY_UNKNOWN);
#line 66 "../src/geocoding.vala"
	_data_->location = _data_->_tmp6_;
#line 67 "../src/geocoding.vala"
	_data_->_tmp7_ = geocode_reverse_new_for_location (_data_->location);
#line 67 "../src/geocoding.vala"
	_data_->reverse = _data_->_tmp7_;
#line 758 "geocoding.c"
	{
#line 70 "../src/geocoding.vala"
		_data_->_state_ = 1;
#line 70 "../src/geocoding.vala"
		geocode_reverse_resolve_async (_data_->reverse, NULL, clocks_geo_info_seek_country_code_ready, _data_);
#line 70 "../src/geocoding.vala"
		return FALSE;
#line 766 "geocoding.c"
		_state_1:
#line 70 "../src/geocoding.vala"
		_data_->_tmp8_ = geocode_reverse_resolve_finish (_data_->reverse, _data_->_res_, &_data_->_inner_error0_);
#line 70 "../src/geocoding.vala"
		_data_->place = _data_->_tmp8_;
#line 70 "../src/geocoding.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 774 "geocoding.c"
			goto __catch3_g_error;
		}
#line 72 "../src/geocoding.vala"
		_data_->_tmp9_ = geocode_place_get_country_code (_data_->place);
#line 72 "../src/geocoding.vala"
		_data_->_tmp10_ = g_strdup (_data_->_tmp9_);
#line 72 "../src/geocoding.vala"
		_g_free0 (_data_->self->priv->country_code);
#line 72 "../src/geocoding.vala"
		_data_->self->priv->country_code = _data_->_tmp10_;
#line 69 "../src/geocoding.vala"
		_g_object_unref0 (_data_->place);
#line 787 "geocoding.c"
	}
	goto __finally3;
	__catch3_g_error:
	{
#line 69 "../src/geocoding.vala"
		_data_->e = _data_->_inner_error0_;
#line 69 "../src/geocoding.vala"
		_data_->_inner_error0_ = NULL;
#line 74 "../src/geocoding.vala"
		_data_->_tmp11_ = _data_->e;
#line 74 "../src/geocoding.vala"
		_data_->_tmp12_ = _data_->_tmp11_->message;
#line 74 "../src/geocoding.vala"
		g_warning ("geocoding.vala:74: Failed to obtain country code: %s", _data_->_tmp12_);
#line 69 "../src/geocoding.vala"
		_g_error_free0 (_data_->e);
#line 804 "geocoding.c"
	}
	__finally3:
#line 69 "../src/geocoding.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 69 "../src/geocoding.vala"
		_g_object_unref0 (_data_->reverse);
#line 69 "../src/geocoding.vala"
		_g_object_unref0 (_data_->location);
#line 69 "../src/geocoding.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 69 "../src/geocoding.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 69 "../src/geocoding.vala"
		g_object_unref (_data_->_async_result);
#line 69 "../src/geocoding.vala"
		return FALSE;
#line 821 "geocoding.c"
	}
#line 65 "../src/geocoding.vala"
	_g_object_unref0 (_data_->reverse);
#line 65 "../src/geocoding.vala"
	_g_object_unref0 (_data_->location);
#line 65 "../src/geocoding.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 65 "../src/geocoding.vala"
	if (_data_->_state_ != 0) {
#line 65 "../src/geocoding.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 65 "../src/geocoding.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 835 "geocoding.c"
		}
	}
#line 65 "../src/geocoding.vala"
	g_object_unref (_data_->_async_result);
#line 65 "../src/geocoding.vala"
	return FALSE;
#line 842 "geocoding.c"
}

static gdouble
clocks_geo_info_deg_to_rad (ClocksGeoInfo* self,
                            gdouble deg)
{
	gdouble result = 0.0;
#line 78 "../src/geocoding.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 79 "../src/geocoding.vala"
	result = (G_PI / 180.0) * deg;
#line 79 "../src/geocoding.vala"
	return result;
#line 856 "geocoding.c"
}

static gdouble
clocks_geo_info_get_distance (ClocksGeoInfo* self,
                              gdouble latitude1,
                              gdouble longitude1,
                              gdouble latitude2,
                              gdouble longitude2)
{
#line 83 "../src/geocoding.vala"
	static const gdouble earth_radius = 6372.795;
#line 868 "geocoding.c"
	gdouble lat1 = 0.0;
	gdouble lat2 = 0.0;
	gdouble lon1 = 0.0;
	gdouble lon2 = 0.0;
	gdouble result = 0.0;
#line 82 "../src/geocoding.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 85 "../src/geocoding.vala"
	lat1 = clocks_geo_info_deg_to_rad (self, latitude1);
#line 86 "../src/geocoding.vala"
	lat2 = clocks_geo_info_deg_to_rad (self, latitude2);
#line 87 "../src/geocoding.vala"
	lon1 = clocks_geo_info_deg_to_rad (self, longitude1);
#line 88 "../src/geocoding.vala"
	lon2 = clocks_geo_info_deg_to_rad (self, longitude2);
#line 90 "../src/geocoding.vala"
	result = acos (((cos (lat1) * cos (lat2)) * cos (lon1 - lon2)) + (sin (lat1) * sin (lat2))) * earth_radius;
#line 90 "../src/geocoding.vala"
	return result;
#line 888 "geocoding.c"
}

static void
clocks_geo_info_search_locations_data_free (gpointer _data)
{
	ClocksGeoInfoSearchLocationsData* _data_;
	_data_ = _data;
#line 22 "../src/geocoding.vala"
	_gweather_location_unref0 (_data_->location);
#line 22 "../src/geocoding.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/geocoding.vala"
	g_slice_free (ClocksGeoInfoSearchLocationsData, _data_);
#line 902 "geocoding.c"
}

static gpointer
_gweather_location_ref0 (gpointer self)
{
#line 22 "../src/geocoding.vala"
	return self ? gweather_location_ref (self) : NULL;
#line 910 "geocoding.c"
}

static void
clocks_geo_info_search_locations (ClocksGeoInfo* self,
                                  GWeatherLocation* location,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_)
{
	ClocksGeoInfoSearchLocationsData* _data_;
	ClocksGeoInfo* _tmp0_;
	GWeatherLocation* _tmp1_;
#line 22 "../src/geocoding.vala"
	_data_ = g_slice_new0 (ClocksGeoInfoSearchLocationsData);
#line 22 "../src/geocoding.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/geocoding.vala"
	g_task_set_task_data (_data_->_async_result, _data_, clocks_geo_info_search_locations_data_free);
#line 22 "../src/geocoding.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/geocoding.vala"
	_data_->self = _tmp0_;
#line 22 "../src/geocoding.vala"
	_tmp1_ = _gweather_location_ref0 (location);
#line 22 "../src/geocoding.vala"
	_gweather_location_unref0 (_data_->location);
#line 22 "../src/geocoding.vala"
	_data_->location = _tmp1_;
#line 22 "../src/geocoding.vala"
	clocks_geo_info_search_locations_co (_data_);
#line 940 "geocoding.c"
}

static void
clocks_geo_info_search_locations_finish (ClocksGeoInfo* self,
                                         GAsyncResult* _res_)
{
	ClocksGeoInfoSearchLocationsData* _data_;
#line 22 "../src/geocoding.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 950 "geocoding.c"
}

static GWeatherLocation**
_vala_array_dup1 (GWeatherLocation** self,
                  int length)
{
	GWeatherLocation** result;
	int i;
#line 104 "../src/geocoding.vala"
	result = g_new0 (GWeatherLocation*, length + 1);
#line 104 "../src/geocoding.vala"
	for (i = 0; i < length; i++) {
#line 963 "geocoding.c"
		GWeatherLocation* _tmp0_;
#line 104 "../src/geocoding.vala"
		_tmp0_ = _gweather_location_ref0 (self[i]);
#line 104 "../src/geocoding.vala"
		result[i] = _tmp0_;
#line 969 "geocoding.c"
	}
#line 104 "../src/geocoding.vala"
	return result;
#line 973 "geocoding.c"
}

static void
clocks_geo_info_search_locations_ready (GObject* source_object,
                                        GAsyncResult* _res_,
                                        gpointer _user_data_)
{
	ClocksGeoInfoSearchLocationsData* _data_;
#line 121 "../src/geocoding.vala"
	_data_ = _user_data_;
#line 121 "../src/geocoding.vala"
	_data_->_source_object_ = source_object;
#line 121 "../src/geocoding.vala"
	_data_->_res_ = _res_;
#line 121 "../src/geocoding.vala"
	clocks_geo_info_search_locations_co (_data_);
#line 990 "geocoding.c"
}

static gboolean
clocks_geo_info_search_locations_co (ClocksGeoInfoSearchLocationsData* _data_)
{
#line 94 "../src/geocoding.vala"
	switch (_data_->_state_) {
#line 94 "../src/geocoding.vala"
		case 0:
#line 1000 "geocoding.c"
		goto _state_0;
#line 94 "../src/geocoding.vala"
		case 1:
#line 1004 "geocoding.c"
		goto _state_1;
		default:
#line 94 "../src/geocoding.vala"
		g_assert_not_reached ();
#line 1009 "geocoding.c"
	}
	_state_0:
#line 95 "../src/geocoding.vala"
	_data_->_tmp0_ = _data_->self->priv->country_code;
#line 95 "../src/geocoding.vala"
	if (_data_->_tmp0_ != NULL) {
#line 96 "../src/geocoding.vala"
		_data_->_tmp1_ = gweather_location_get_country (_data_->location);
#line 96 "../src/geocoding.vala"
		_data_->_tmp2_ = g_strdup (_data_->_tmp1_);
#line 96 "../src/geocoding.vala"
		_data_->loc_country_code = _data_->_tmp2_;
#line 97 "../src/geocoding.vala"
		_data_->_tmp3_ = _data_->loc_country_code;
#line 97 "../src/geocoding.vala"
		if (_data_->_tmp3_ != NULL) {
#line 98 "../src/geocoding.vala"
			_data_->_tmp4_ = _data_->loc_country_code;
#line 98 "../src/geocoding.vala"
			_data_->_tmp5_ = _data_->self->priv->country_code;
#line 98 "../src/geocoding.vala"
			if (g_strcmp0 (_data_->_tmp4_, _data_->_tmp5_) != 0) {
#line 99 "../src/geocoding.vala"
				_g_free0 (_data_->loc_country_code);
#line 99 "../src/geocoding.vala"
				g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 99 "../src/geocoding.vala"
				if (_data_->_state_ != 0) {
#line 99 "../src/geocoding.vala"
					while (!g_task_get_completed (_data_->_async_result)) {
#line 99 "../src/geocoding.vala"
						g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 1042 "geocoding.c"
					}
				}
#line 99 "../src/geocoding.vala"
				g_object_unref (_data_->_async_result);
#line 99 "../src/geocoding.vala"
				return FALSE;
#line 1049 "geocoding.c"
			}
		}
#line 95 "../src/geocoding.vala"
		_g_free0 (_data_->loc_country_code);
#line 1054 "geocoding.c"
	}
#line 104 "../src/geocoding.vala"
	_data_->_tmp7_ = _data_->_tmp6_ = gweather_location_get_children (_data_->location);
#line 104 "../src/geocoding.vala"
	_data_->_tmp8_ = (_data_->_tmp7_ != NULL) ? _vala_array_dup1 (_data_->_tmp7_, _vala_array_length (_data_->_tmp6_)) : ((gpointer) _data_->_tmp7_);
#line 104 "../src/geocoding.vala"
	_data_->_tmp8__length1 = _vala_array_length (_data_->_tmp6_);
#line 104 "../src/geocoding.vala"
	_data_->locations = _data_->_tmp8_;
#line 104 "../src/geocoding.vala"
	_data_->locations_length1 = _data_->_tmp8__length1;
#line 104 "../src/geocoding.vala"
	_data_->_locations_size_ = _data_->locations_length1;
#line 105 "../src/geocoding.vala"
	_data_->_tmp9_ = _data_->locations;
#line 105 "../src/geocoding.vala"
	_data_->_tmp9__length1 = _data_->locations_length1;
#line 105 "../src/geocoding.vala"
	if (_data_->_tmp9_ != NULL) {
#line 1074 "geocoding.c"
		{
#line 106 "../src/geocoding.vala"
			_data_->i = 0;
#line 1078 "geocoding.c"
			{
#line 106 "../src/geocoding.vala"
				_data_->_tmp10_ = TRUE;
#line 106 "../src/geocoding.vala"
				while (TRUE) {
#line 106 "../src/geocoding.vala"
					if (!_data_->_tmp10_) {
#line 106 "../src/geocoding.vala"
						_data_->_tmp11_ = _data_->i;
#line 106 "../src/geocoding.vala"
						_data_->i = _data_->_tmp11_ + 1;
#line 1090 "geocoding.c"
					}
#line 106 "../src/geocoding.vala"
					_data_->_tmp10_ = FALSE;
#line 106 "../src/geocoding.vala"
					_data_->_tmp12_ = _data_->locations;
#line 106 "../src/geocoding.vala"
					_data_->_tmp12__length1 = _data_->locations_length1;
#line 106 "../src/geocoding.vala"
					if (!(_data_->i < _data_->_tmp12__length1)) {
#line 106 "../src/geocoding.vala"
						break;
#line 1102 "geocoding.c"
					}
#line 107 "../src/geocoding.vala"
					_data_->_tmp13_ = _data_->locations;
#line 107 "../src/geocoding.vala"
					_data_->_tmp13__length1 = _data_->locations_length1;
#line 107 "../src/geocoding.vala"
					_data_->_tmp14_ = _data_->_tmp13_[_data_->i];
#line 107 "../src/geocoding.vala"
					if (gweather_location_get_level (_data_->_tmp14_) == GWEATHER_LOCATION_CITY) {
#line 108 "../src/geocoding.vala"
						_data_->_tmp15_ = _data_->locations;
#line 108 "../src/geocoding.vala"
						_data_->_tmp15__length1 = _data_->locations_length1;
#line 108 "../src/geocoding.vala"
						_data_->_tmp16_ = _data_->_tmp15_[_data_->i];
#line 108 "../src/geocoding.vala"
						if (gweather_location_has_coords (_data_->_tmp16_)) {
#line 111 "../src/geocoding.vala"
							_data_->_tmp17_ = _data_->locations;
#line 111 "../src/geocoding.vala"
							_data_->_tmp17__length1 = _data_->locations_length1;
#line 111 "../src/geocoding.vala"
							_data_->_tmp18_ = _data_->_tmp17_[_data_->i];
#line 111 "../src/geocoding.vala"
							_data_->_tmp19_ = 0.0;
#line 111 "../src/geocoding.vala"
							_data_->_tmp20_ = 0.0;
#line 111 "../src/geocoding.vala"
							gweather_location_get_coords (_data_->_tmp18_, &_data_->_tmp19_, &_data_->_tmp20_);
#line 111 "../src/geocoding.vala"
							_data_->latitude = _data_->_tmp19_;
#line 111 "../src/geocoding.vala"
							_data_->longitude = _data_->_tmp20_;
#line 112 "../src/geocoding.vala"
							_data_->_tmp21_ = _data_->self->priv->_geo_location;
#line 112 "../src/geocoding.vala"
							g_object_get (_data_->_tmp21_, "latitude", &_data_->_tmp22_, NULL);
#line 112 "../src/geocoding.vala"
							_data_->_tmp23_ = _data_->_tmp22_;
#line 112 "../src/geocoding.vala"
							_data_->_tmp24_ = _data_->self->priv->_geo_location;
#line 112 "../src/geocoding.vala"
							g_object_get (_data_->_tmp24_, "longitude", &_data_->_tmp25_, NULL);
#line 112 "../src/geocoding.vala"
							_data_->_tmp26_ = _data_->_tmp25_;
#line 112 "../src/geocoding.vala"
							_data_->distance = clocks_geo_info_get_distance (_data_->self, _data_->_tmp23_, _data_->_tmp26_, _data_->latitude, _data_->longitude);
#line 114 "../src/geocoding.vala"
							if (_data_->distance < _data_->self->priv->minimal_distance) {
#line 115 "../src/geocoding.vala"
								_data_->_tmp27_ = _data_->locations;
#line 115 "../src/geocoding.vala"
								_data_->_tmp27__length1 = _data_->locations_length1;
#line 115 "../src/geocoding.vala"
								_data_->_tmp28_ = _data_->_tmp27_[_data_->i];
#line 115 "../src/geocoding.vala"
								_data_->_tmp29_ = _gweather_location_ref0 (_data_->_tmp28_);
#line 115 "../src/geocoding.vala"
								_gweather_location_unref0 (_data_->self->priv->found_location);
#line 115 "../src/geocoding.vala"
								_data_->self->priv->found_location = _data_->_tmp29_;
#line 116 "../src/geocoding.vala"
								_data_->self->priv->minimal_distance = _data_->distance;
#line 1166 "geocoding.c"
							}
						}
					}
#line 121 "../src/geocoding.vala"
					_data_->_tmp30_ = _data_->locations;
#line 121 "../src/geocoding.vala"
					_data_->_tmp30__length1 = _data_->locations_length1;
#line 121 "../src/geocoding.vala"
					_data_->_tmp31_ = _data_->_tmp30_[_data_->i];
#line 121 "../src/geocoding.vala"
					_data_->_state_ = 1;
#line 121 "../src/geocoding.vala"
					clocks_geo_info_search_locations (_data_->self, _data_->_tmp31_, clocks_geo_info_search_locations_ready, _data_);
#line 121 "../src/geocoding.vala"
					return FALSE;
#line 1182 "geocoding.c"
					_state_1:
#line 121 "../src/geocoding.vala"
					clocks_geo_info_search_locations_finish (_data_->self, _data_->_res_);
#line 1186 "geocoding.c"
				}
			}
		}
	}
#line 94 "../src/geocoding.vala"
	_data_->locations = (_vala_array_free (_data_->locations, _data_->locations_length1, (GDestroyNotify) gweather_location_unref), NULL);
#line 94 "../src/geocoding.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 94 "../src/geocoding.vala"
	if (_data_->_state_ != 0) {
#line 94 "../src/geocoding.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 94 "../src/geocoding.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 1201 "geocoding.c"
		}
	}
#line 94 "../src/geocoding.vala"
	g_object_unref (_data_->_async_result);
#line 94 "../src/geocoding.vala"
	return FALSE;
#line 1208 "geocoding.c"
}

static gpointer
_gweather_timezone_ref0 (gpointer self)
{
#line 131 "../src/geocoding.vala"
	return self ? gweather_timezone_ref (self) : NULL;
#line 1216 "geocoding.c"
}

gboolean
clocks_geo_info_is_location_similar (ClocksGeoInfo* self,
                                     GWeatherLocation* location)
{
	GWeatherLocation* _tmp0_;
	gboolean result = FALSE;
#line 126 "../src/geocoding.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 126 "../src/geocoding.vala"
	g_return_val_if_fail (location != NULL, FALSE);
#line 127 "../src/geocoding.vala"
	_tmp0_ = self->priv->found_location;
#line 127 "../src/geocoding.vala"
	if (_tmp0_ != NULL) {
#line 1233 "geocoding.c"
		gchar* country_code = NULL;
		const gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* found_country_code = NULL;
		GWeatherLocation* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gboolean _tmp6_ = FALSE;
		const gchar* _tmp7_;
#line 128 "../src/geocoding.vala"
		_tmp1_ = gweather_location_get_country (location);
#line 128 "../src/geocoding.vala"
		_tmp2_ = g_strdup (_tmp1_);
#line 128 "../src/geocoding.vala"
		country_code = _tmp2_;
#line 129 "../src/geocoding.vala"
		_tmp3_ = self->priv->found_location;
#line 129 "../src/geocoding.vala"
		_tmp4_ = gweather_location_get_country (_tmp3_);
#line 129 "../src/geocoding.vala"
		_tmp5_ = g_strdup (_tmp4_);
#line 129 "../src/geocoding.vala"
		found_country_code = _tmp5_;
#line 130 "../src/geocoding.vala"
		_tmp7_ = country_code;
#line 130 "../src/geocoding.vala"
		if (_tmp7_ != NULL) {
#line 1261 "geocoding.c"
			const gchar* _tmp8_;
			const gchar* _tmp9_;
#line 130 "../src/geocoding.vala"
			_tmp8_ = country_code;
#line 130 "../src/geocoding.vala"
			_tmp9_ = found_country_code;
#line 130 "../src/geocoding.vala"
			_tmp6_ = g_strcmp0 (_tmp8_, _tmp9_) == 0;
#line 1270 "geocoding.c"
		} else {
#line 130 "../src/geocoding.vala"
			_tmp6_ = FALSE;
#line 1274 "geocoding.c"
		}
#line 130 "../src/geocoding.vala"
		if (_tmp6_) {
#line 1278 "geocoding.c"
			GWeatherTimezone* timezone = NULL;
			GWeatherTimezone* _tmp10_;
			GWeatherTimezone* _tmp11_;
			GWeatherTimezone* found_timezone = NULL;
			GWeatherLocation* _tmp12_;
			GWeatherTimezone* _tmp13_;
			GWeatherTimezone* _tmp14_;
			gboolean _tmp15_ = FALSE;
			GWeatherTimezone* _tmp16_;
#line 131 "../src/geocoding.vala"
			_tmp10_ = gweather_location_get_timezone (location);
#line 131 "../src/geocoding.vala"
			_tmp11_ = _gweather_timezone_ref0 (_tmp10_);
#line 131 "../src/geocoding.vala"
			timezone = _tmp11_;
#line 132 "../src/geocoding.vala"
			_tmp12_ = self->priv->found_location;
#line 132 "../src/geocoding.vala"
			_tmp13_ = gweather_location_get_timezone (_tmp12_);
#line 132 "../src/geocoding.vala"
			_tmp14_ = _gweather_timezone_ref0 (_tmp13_);
#line 132 "../src/geocoding.vala"
			found_timezone = _tmp14_;
#line 134 "../src/geocoding.vala"
			_tmp16_ = timezone;
#line 134 "../src/geocoding.vala"
			if (_tmp16_ != NULL) {
#line 1306 "geocoding.c"
				GWeatherTimezone* _tmp17_;
#line 134 "../src/geocoding.vala"
				_tmp17_ = found_timezone;
#line 134 "../src/geocoding.vala"
				_tmp15_ = _tmp17_ != NULL;
#line 1312 "geocoding.c"
			} else {
#line 134 "../src/geocoding.vala"
				_tmp15_ = FALSE;
#line 1316 "geocoding.c"
			}
#line 134 "../src/geocoding.vala"
			if (_tmp15_) {
#line 1320 "geocoding.c"
				gchar* tzid = NULL;
				GWeatherTimezone* _tmp18_;
				const gchar* _tmp19_;
				gchar* _tmp20_;
				gchar* found_tzid = NULL;
				GWeatherTimezone* _tmp21_;
				const gchar* _tmp22_;
				gchar* _tmp23_;
				const gchar* _tmp24_;
				const gchar* _tmp25_;
#line 135 "../src/geocoding.vala"
				_tmp18_ = timezone;
#line 135 "../src/geocoding.vala"
				_tmp19_ = gweather_timezone_get_tzid (_tmp18_);
#line 135 "../src/geocoding.vala"
				_tmp20_ = g_strdup (_tmp19_);
#line 135 "../src/geocoding.vala"
				tzid = _tmp20_;
#line 136 "../src/geocoding.vala"
				_tmp21_ = found_timezone;
#line 136 "../src/geocoding.vala"
				_tmp22_ = gweather_timezone_get_tzid (_tmp21_);
#line 136 "../src/geocoding.vala"
				_tmp23_ = g_strdup (_tmp22_);
#line 136 "../src/geocoding.vala"
				found_tzid = _tmp23_;
#line 137 "../src/geocoding.vala"
				_tmp24_ = tzid;
#line 137 "../src/geocoding.vala"
				_tmp25_ = found_tzid;
#line 137 "../src/geocoding.vala"
				if (g_strcmp0 (_tmp24_, _tmp25_) == 0) {
#line 138 "../src/geocoding.vala"
					result = TRUE;
#line 138 "../src/geocoding.vala"
					_g_free0 (found_tzid);
#line 138 "../src/geocoding.vala"
					_g_free0 (tzid);
#line 138 "../src/geocoding.vala"
					_gweather_timezone_unref0 (found_timezone);
#line 138 "../src/geocoding.vala"
					_gweather_timezone_unref0 (timezone);
#line 138 "../src/geocoding.vala"
					_g_free0 (found_country_code);
#line 138 "../src/geocoding.vala"
					_g_free0 (country_code);
#line 138 "../src/geocoding.vala"
					return result;
#line 1369 "geocoding.c"
				}
#line 134 "../src/geocoding.vala"
				_g_free0 (found_tzid);
#line 134 "../src/geocoding.vala"
				_g_free0 (tzid);
#line 1375 "geocoding.c"
			}
#line 130 "../src/geocoding.vala"
			_gweather_timezone_unref0 (found_timezone);
#line 130 "../src/geocoding.vala"
			_gweather_timezone_unref0 (timezone);
#line 1381 "geocoding.c"
		}
#line 127 "../src/geocoding.vala"
		_g_free0 (found_country_code);
#line 127 "../src/geocoding.vala"
		_g_free0 (country_code);
#line 1387 "geocoding.c"
	}
#line 144 "../src/geocoding.vala"
	result = FALSE;
#line 144 "../src/geocoding.vala"
	return result;
#line 1393 "geocoding.c"
}

GClueLocation*
clocks_geo_info_get_geo_location (ClocksGeoInfo* self)
{
	GClueLocation* result;
	GClueLocation* _tmp0_;
#line 23 "../src/geocoding.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "../src/geocoding.vala"
	_tmp0_ = self->priv->_geo_location;
#line 23 "../src/geocoding.vala"
	result = _tmp0_;
#line 23 "../src/geocoding.vala"
	return result;
#line 1409 "geocoding.c"
}

static void
clocks_geo_info_set_geo_location (ClocksGeoInfo* self,
                                  GClueLocation* value)
{
#line 23 "../src/geocoding.vala"
	g_return_if_fail (self != NULL);
#line 23 "../src/geocoding.vala"
	if (clocks_geo_info_get_geo_location (self) != value) {
#line 1420 "geocoding.c"
		GClueLocation* _tmp0_;
#line 23 "../src/geocoding.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 23 "../src/geocoding.vala"
		_g_object_unref0 (self->priv->_geo_location);
#line 23 "../src/geocoding.vala"
		self->priv->_geo_location = _tmp0_;
#line 23 "../src/geocoding.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_geo_info_properties[CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY]);
#line 1430 "geocoding.c"
	}
}

static void
clocks_geo_info_class_init (ClocksGeoInfoClass * klass,
                            gpointer klass_data)
{
#line 22 "../src/geocoding.vala"
	clocks_geo_info_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/geocoding.vala"
	g_type_class_adjust_private_offset (klass, &ClocksGeoInfo_private_offset);
#line 22 "../src/geocoding.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_clocks_geo_info_get_property;
#line 22 "../src/geocoding.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_clocks_geo_info_set_property;
#line 22 "../src/geocoding.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_geo_info_finalize;
#line 22 "../src/geocoding.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY, clocks_geo_info_properties[CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY] = g_param_spec_object ("geo-location", "geo-location", "geo-location", gclue_location_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 22 "../src/geocoding.vala"
	clocks_geo_info_signals[CLOCKS_GEO_INFO_LOCATION_CHANGED_SIGNAL] = g_signal_new ("location-changed", CLOCKS_GEO_TYPE_INFO, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, gweather_location_get_type ());
#line 1452 "geocoding.c"
}

static void
clocks_geo_info_instance_init (ClocksGeoInfo * self,
                               gpointer klass)
{
#line 22 "../src/geocoding.vala"
	self->priv = clocks_geo_info_get_instance_private (self);
#line 23 "../src/geocoding.vala"
	self->priv->_geo_location = NULL;
#line 1463 "geocoding.c"
}

static void
clocks_geo_info_finalize (GObject * obj)
{
	ClocksGeoInfo * self;
#line 22 "../src/geocoding.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_GEO_TYPE_INFO, ClocksGeoInfo);
#line 23 "../src/geocoding.vala"
	_g_object_unref0 (self->priv->_geo_location);
#line 25 "../src/geocoding.vala"
	_gweather_location_unref0 (self->priv->found_location);
#line 26 "../src/geocoding.vala"
	_g_free0 (self->priv->country_code);
#line 27 "../src/geocoding.vala"
	_g_object_unref0 (self->priv->simple);
#line 22 "../src/geocoding.vala"
	G_OBJECT_CLASS (clocks_geo_info_parent_class)->finalize (obj);
#line 1482 "geocoding.c"
}

GType
clocks_geo_info_get_type (void)
{
	static volatile gsize clocks_geo_info_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_geo_info_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksGeoInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_geo_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksGeoInfo), 0, (GInstanceInitFunc) clocks_geo_info_instance_init, NULL };
		GType clocks_geo_info_type_id;
		clocks_geo_info_type_id = g_type_register_static (G_TYPE_OBJECT, "ClocksGeoInfo", &g_define_type_info, 0);
		ClocksGeoInfo_private_offset = g_type_add_instance_private (clocks_geo_info_type_id, sizeof (ClocksGeoInfoPrivate));
		g_once_init_leave (&clocks_geo_info_type_id__volatile, clocks_geo_info_type_id);
	}
	return clocks_geo_info_type_id__volatile;
}

static void
_vala_clocks_geo_info_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec)
{
	ClocksGeoInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_GEO_TYPE_INFO, ClocksGeoInfo);
#line 22 "../src/geocoding.vala"
	switch (property_id) {
#line 22 "../src/geocoding.vala"
		case CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY:
#line 22 "../src/geocoding.vala"
		g_value_set_object (value, clocks_geo_info_get_geo_location (self));
#line 22 "../src/geocoding.vala"
		break;
#line 1515 "geocoding.c"
		default:
#line 22 "../src/geocoding.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "../src/geocoding.vala"
		break;
#line 1521 "geocoding.c"
	}
}

static void
_vala_clocks_geo_info_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec)
{
	ClocksGeoInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_GEO_TYPE_INFO, ClocksGeoInfo);
#line 22 "../src/geocoding.vala"
	switch (property_id) {
#line 22 "../src/geocoding.vala"
		case CLOCKS_GEO_INFO_GEO_LOCATION_PROPERTY:
#line 22 "../src/geocoding.vala"
		clocks_geo_info_set_geo_location (self, g_value_get_object (value));
#line 22 "../src/geocoding.vala"
		break;
#line 1541 "geocoding.c"
		default:
#line 22 "../src/geocoding.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "../src/geocoding.vala"
		break;
#line 1547 "geocoding.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gint
_vala_array_length (gpointer array)
{
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

