/* main.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from main.vala, do not modify */

/*
 * Copyright (C) 2013  Paolo Borelli <pborelli@gnome.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include "config.h"
#include <handy.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>

#define CLOCKS_TYPE_APPLICATION (clocks_application_get_type ())
#define CLOCKS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplication))
#define CLOCKS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))
#define CLOCKS_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))

typedef struct _ClocksApplication ClocksApplication;
typedef struct _ClocksApplicationClass ClocksApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

gint _vala_main (gchar** args,
                 gint args_length1);
GType clocks_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksApplication, g_object_unref)
ClocksApplication* clocks_application_new (void);
ClocksApplication* clocks_application_construct (GType object_type);

gint
_vala_main (gchar** args,
            gint args_length1)
{
	ClocksApplication* app = NULL;
	ClocksApplication* _tmp0_;
	gint result = 0;
#line 20 "../src/main.vala"
	bindtextdomain (GETTEXT_PACKAGE, GNOMELOCALEDIR);
#line 21 "../src/main.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 22 "../src/main.vala"
	textdomain (GETTEXT_PACKAGE);
#line 24 "../src/main.vala"
	hdy_init ((gint*) (&args_length1), &args);
#line 26 "../src/main.vala"
	_tmp0_ = clocks_application_new ();
#line 26 "../src/main.vala"
	app = _tmp0_;
#line 27 "../src/main.vala"
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
#line 27 "../src/main.vala"
	_g_object_unref0 (app);
#line 27 "../src/main.vala"
	return result;
#line 76 "main.c"
}

int
main (int argc,
      char ** argv)
{
#line 19 "../src/main.vala"
	return _vala_main (argv, argc);
#line 85 "main.c"
}

