/* stopwatch.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from stopwatch.vala, do not modify */

/*
 * Copyright (C) 2013  Paolo Borelli <pborelli@gnome.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>

#define CLOCKS_STOPWATCH_TYPE_LAPS_ROW (clocks_stopwatch_laps_row_get_type ())
#define CLOCKS_STOPWATCH_LAPS_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_STOPWATCH_TYPE_LAPS_ROW, ClocksStopwatchLapsRow))
#define CLOCKS_STOPWATCH_LAPS_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_STOPWATCH_TYPE_LAPS_ROW, ClocksStopwatchLapsRowClass))
#define CLOCKS_STOPWATCH_IS_LAPS_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_STOPWATCH_TYPE_LAPS_ROW))
#define CLOCKS_STOPWATCH_IS_LAPS_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_STOPWATCH_TYPE_LAPS_ROW))
#define CLOCKS_STOPWATCH_LAPS_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_STOPWATCH_TYPE_LAPS_ROW, ClocksStopwatchLapsRowClass))

typedef struct _ClocksStopwatchLapsRow ClocksStopwatchLapsRow;
typedef struct _ClocksStopwatchLapsRowClass ClocksStopwatchLapsRowClass;
typedef struct _ClocksStopwatchLapsRowPrivate ClocksStopwatchLapsRowPrivate;
enum  {
	CLOCKS_STOPWATCH_LAPS_ROW_0_PROPERTY,
	CLOCKS_STOPWATCH_LAPS_ROW_NUM_PROPERTIES
};
static GParamSpec* clocks_stopwatch_laps_row_properties[CLOCKS_STOPWATCH_LAPS_ROW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CLOCKS_TYPE_CLOCK (clocks_clock_get_type ())
#define CLOCKS_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_CLOCK, ClocksClock))
#define CLOCKS_IS_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_CLOCK))
#define CLOCKS_CLOCK_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CLOCKS_TYPE_CLOCK, ClocksClockIface))

typedef struct _ClocksClock ClocksClock;
typedef struct _ClocksClockIface ClocksClockIface;

#define CLOCKS_TYPE_HEADER_BAR (clocks_header_bar_get_type ())
#define CLOCKS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBar))
#define CLOCKS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBarClass))
#define CLOCKS_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_HEADER_BAR))
#define CLOCKS_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_HEADER_BAR))
#define CLOCKS_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBarClass))

typedef struct _ClocksHeaderBar ClocksHeaderBar;
typedef struct _ClocksHeaderBarClass ClocksHeaderBarClass;
typedef enum  {
	CLOCKS_PANEL_ID_WORLD,
	CLOCKS_PANEL_ID_ALARM,
	CLOCKS_PANEL_ID_STOPWATCH,
	CLOCKS_PANEL_ID_TIMER
} ClocksPanelId;

#define CLOCKS_TYPE_PANEL_ID (clocks_panel_id_get_type ())

#define CLOCKS_STOPWATCH_TYPE_FACE (clocks_stopwatch_face_get_type ())
#define CLOCKS_STOPWATCH_FACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace))
#define CLOCKS_STOPWATCH_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFaceClass))
#define CLOCKS_STOPWATCH_IS_FACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_STOPWATCH_TYPE_FACE))
#define CLOCKS_STOPWATCH_IS_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_STOPWATCH_TYPE_FACE))
#define CLOCKS_STOPWATCH_FACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFaceClass))

typedef struct _ClocksStopwatchFace ClocksStopwatchFace;
typedef struct _ClocksStopwatchFaceClass ClocksStopwatchFaceClass;
typedef struct _ClocksStopwatchFacePrivate ClocksStopwatchFacePrivate;
typedef enum  {
	CLOCKS_STOPWATCH_FACE_STATE_RESET,
	CLOCKS_STOPWATCH_FACE_STATE_RUNNING,
	CLOCKS_STOPWATCH_FACE_STATE_STOPPED
} ClocksStopwatchFaceState;

#define CLOCKS_STOPWATCH_FACE_TYPE_STATE (clocks_stopwatch_face_state_get_type ())
enum  {
	CLOCKS_STOPWATCH_FACE_0_PROPERTY,
	CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY,
	CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY,
	CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY,
	CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY,
	CLOCKS_STOPWATCH_FACE_STATE_PROPERTY,
	CLOCKS_STOPWATCH_FACE_NUM_PROPERTIES
};
static GParamSpec* clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_NUM_PROPERTIES];
typedef enum  {
	CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_LAP,
	CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_SPLIT,
	CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_TOTAL
} ClocksStopwatchFaceLapsColumn;

#define CLOCKS_STOPWATCH_FACE_TYPE_LAPS_COLUMN (clocks_stopwatch_face_laps_column_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_timer_destroy0(var) ((var == NULL) ? NULL : (var = (g_timer_destroy (var), NULL)))

struct _ClocksStopwatchLapsRow {
	GtkListBoxRow parent_instance;
	ClocksStopwatchLapsRowPrivate * priv;
};

struct _ClocksStopwatchLapsRowClass {
	GtkListBoxRowClass parent_class;
};

struct _ClocksStopwatchLapsRowPrivate {
	GtkRevealer* slider;
	GtkLabel* num_label;
	GtkLabel* split_label;
	GtkLabel* tot_label;
};

struct _ClocksClockIface {
	GTypeInterface parent_iface;
	void (*activate_new) (ClocksClock* self);
	void (*activate_select_all) (ClocksClock* self);
	void (*activate_select_none) (ClocksClock* self);
	gboolean (*escape_pressed) (ClocksClock* self);
	void (*back) (ClocksClock* self);
	void (*update_header_bar) (ClocksClock* self);
	const gchar* (*get_label) (ClocksClock* self);
	void (*set_label) (ClocksClock* self, const gchar* value);
	const gchar* (*get_icon_name) (ClocksClock* self);
	void (*set_icon_name) (ClocksClock* self, const gchar* value);
	ClocksHeaderBar* (*get_header_bar) (ClocksClock* self);
	void (*set_header_bar) (ClocksClock* self, ClocksHeaderBar* value);
	ClocksPanelId (*get_panel_id) (ClocksClock* self);
	void (*set_panel_id) (ClocksClock* self, ClocksPanelId value);
};

struct _ClocksStopwatchFace {
	GtkBox parent_instance;
	ClocksStopwatchFacePrivate * priv;
};

struct _ClocksStopwatchFaceClass {
	GtkBoxClass parent_class;
};

struct _ClocksStopwatchFacePrivate {
	gchar* _label;
	gchar* _icon_name;
	ClocksHeaderBar* _header_bar;
	ClocksPanelId _panel_id;
	ClocksStopwatchFaceState _state;
	GTimer* timer;
	guint tick_id;
	gint current_lap;
	gdouble last_lap_time;
	GtkLabel* time_label;
	GtkButton* left_button;
	GtkButton* right_button;
	GtkScrolledWindow* laps_scrollwin;
	GtkListBox* laps_list;
};

static gint ClocksStopwatchLapsRow_private_offset;
static gpointer clocks_stopwatch_laps_row_parent_class = NULL;
static gint ClocksStopwatchFace_private_offset;
static gpointer clocks_stopwatch_face_parent_class = NULL;
static ClocksClockIface * clocks_stopwatch_face_clocks_clock_parent_iface = NULL;

GType clocks_stopwatch_laps_row_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksStopwatchLapsRow, g_object_unref)
ClocksStopwatchLapsRow* clocks_stopwatch_laps_row_new (const gchar* n,
                                                       const gchar* split,
                                                       const gchar* tot);
ClocksStopwatchLapsRow* clocks_stopwatch_laps_row_construct (GType object_type,
                                                             const gchar* n,
                                                             const gchar* split,
                                                             const gchar* tot);
void clocks_stopwatch_laps_row_slide_in (ClocksStopwatchLapsRow* self);
static void clocks_stopwatch_laps_row_finalize (GObject * obj);
GType clocks_header_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksHeaderBar, g_object_unref)
GType clocks_panel_id_get_type (void) G_GNUC_CONST;
GType clocks_clock_get_type (void) G_GNUC_CONST;
GType clocks_stopwatch_face_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksStopwatchFace, g_object_unref)
GType clocks_stopwatch_face_state_get_type (void) G_GNUC_CONST;
static GType clocks_stopwatch_face_laps_column_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
ClocksStopwatchFace* clocks_stopwatch_face_new (ClocksHeaderBar* header_bar);
ClocksStopwatchFace* clocks_stopwatch_face_construct (GType object_type,
                                                      ClocksHeaderBar* header_bar);
static void __lambda45_ (ClocksStopwatchFace* self,
                  GtkWidget* w);
ClocksStopwatchFaceState clocks_stopwatch_face_get_state (ClocksStopwatchFace* self);
static gboolean clocks_stopwatch_face_update_time_label (ClocksStopwatchFace* self);
static void clocks_stopwatch_face_add_tick (ClocksStopwatchFace* self);
static void ___lambda45__gtk_widget_map (GtkWidget* _sender,
                                  gpointer self);
static void __lambda47_ (ClocksStopwatchFace* self,
                  GtkListBoxRow* before,
                  GtkListBoxRow* after);
static void ___lambda47__gtk_list_box_update_header_func (GtkListBoxRow* row,
                                                   GtkListBoxRow* before,
                                                   gpointer self);
static void __lambda48_ (ClocksStopwatchFace* self,
                  GtkWidget* w);
static void clocks_stopwatch_face_remove_tick (ClocksStopwatchFace* self);
static void ___lambda48__gtk_widget_unmap (GtkWidget* _sender,
                                    gpointer self);
static void clocks_stopwatch_face_reset (ClocksStopwatchFace* self);
static void clocks_stopwatch_face_on_left_button_clicked (ClocksStopwatchFace* self,
                                                   GtkButton* button);
static void clocks_stopwatch_face_start (ClocksStopwatchFace* self);
static void clocks_stopwatch_face_stop (ClocksStopwatchFace* self);
static void _clocks_stopwatch_face_on_left_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                       gpointer self);
static void clocks_stopwatch_face_on_right_button_clicked (ClocksStopwatchFace* self,
                                                    GtkButton* button);
static void clocks_stopwatch_face_lap (ClocksStopwatchFace* self);
static void _clocks_stopwatch_face_on_right_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                        gpointer self);
static void clocks_stopwatch_face_set_state (ClocksStopwatchFace* self,
                                      ClocksStopwatchFaceState value);
void clocks_utils_time_to_hms (gdouble t,
                               gint* h,
                               gint* m,
                               gint* s,
                               gdouble* remainder);
static gboolean ___lambda46_ (ClocksStopwatchFace* self,
                       GtkWidget* c);
static gboolean ____lambda46__gtk_tick_callback (GtkWidget* widget,
                                          GdkFrameClock* frame_clock,
                                          gpointer self);
static void clocks_stopwatch_face_real_grab_focus (GtkWidget* base);
static gboolean clocks_stopwatch_face_real_escape_pressed (ClocksClock* base);
static void clocks_stopwatch_face_finalize (GObject * obj);
const gchar* clocks_clock_get_label (ClocksClock* self);
const gchar* clocks_clock_get_icon_name (ClocksClock* self);
ClocksHeaderBar* clocks_clock_get_header_bar (ClocksClock* self);
ClocksPanelId clocks_clock_get_panel_id (ClocksClock* self);
static void _vala_clocks_stopwatch_face_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec);
void clocks_clock_set_label (ClocksClock* self,
                             const gchar* value);
void clocks_clock_set_icon_name (ClocksClock* self,
                                 const gchar* value);
void clocks_clock_set_header_bar (ClocksClock* self,
                                  ClocksHeaderBar* value);
void clocks_clock_set_panel_id (ClocksClock* self,
                                ClocksPanelId value);
static void _vala_clocks_stopwatch_face_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec);

static inline gpointer
clocks_stopwatch_laps_row_get_instance_private (ClocksStopwatchLapsRow* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksStopwatchLapsRow_private_offset);
}

ClocksStopwatchLapsRow*
clocks_stopwatch_laps_row_construct (GType object_type,
                                     const gchar* n,
                                     const gchar* split,
                                     const gchar* tot)
{
	ClocksStopwatchLapsRow * self = NULL;
	GtkLabel* _tmp0_;
	GtkLabel* _tmp1_;
	GtkLabel* _tmp2_;
#line 33 "../src/stopwatch.vala"
	g_return_val_if_fail (n != NULL, NULL);
#line 33 "../src/stopwatch.vala"
	g_return_val_if_fail (split != NULL, NULL);
#line 33 "../src/stopwatch.vala"
	g_return_val_if_fail (tot != NULL, NULL);
#line 33 "../src/stopwatch.vala"
	self = (ClocksStopwatchLapsRow*) g_object_new (object_type, NULL);
#line 34 "../src/stopwatch.vala"
	_tmp0_ = self->priv->num_label;
#line 34 "../src/stopwatch.vala"
	gtk_label_set_label (_tmp0_, n);
#line 35 "../src/stopwatch.vala"
	_tmp1_ = self->priv->split_label;
#line 35 "../src/stopwatch.vala"
	gtk_label_set_label (_tmp1_, split);
#line 36 "../src/stopwatch.vala"
	_tmp2_ = self->priv->tot_label;
#line 36 "../src/stopwatch.vala"
	gtk_label_set_label (_tmp2_, tot);
#line 33 "../src/stopwatch.vala"
	return self;
#line 305 "stopwatch.c"
}

ClocksStopwatchLapsRow*
clocks_stopwatch_laps_row_new (const gchar* n,
                               const gchar* split,
                               const gchar* tot)
{
#line 33 "../src/stopwatch.vala"
	return clocks_stopwatch_laps_row_construct (CLOCKS_STOPWATCH_TYPE_LAPS_ROW, n, split, tot);
#line 315 "stopwatch.c"
}

void
clocks_stopwatch_laps_row_slide_in (ClocksStopwatchLapsRow* self)
{
	GtkRevealer* _tmp0_;
#line 39 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 40 "../src/stopwatch.vala"
	_tmp0_ = self->priv->slider;
#line 40 "../src/stopwatch.vala"
	gtk_revealer_set_reveal_child (_tmp0_, TRUE);
#line 328 "stopwatch.c"
}

static void
clocks_stopwatch_laps_row_class_init (ClocksStopwatchLapsRowClass * klass,
                                      gpointer klass_data)
{
#line 23 "../src/stopwatch.vala"
	clocks_stopwatch_laps_row_parent_class = g_type_class_peek_parent (klass);
#line 23 "../src/stopwatch.vala"
	g_type_class_adjust_private_offset (klass, &ClocksStopwatchLapsRow_private_offset);
#line 23 "../src/stopwatch.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_stopwatch_laps_row_finalize;
#line 23 "../src/stopwatch.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/clocks/ui/stopwatchlapsrow.ui");
#line 23 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "slider", FALSE, ClocksStopwatchLapsRow_private_offset + G_STRUCT_OFFSET (ClocksStopwatchLapsRowPrivate, slider));
#line 23 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "num_label", FALSE, ClocksStopwatchLapsRow_private_offset + G_STRUCT_OFFSET (ClocksStopwatchLapsRowPrivate, num_label));
#line 23 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "split_label", FALSE, ClocksStopwatchLapsRow_private_offset + G_STRUCT_OFFSET (ClocksStopwatchLapsRowPrivate, split_label));
#line 23 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "tot_label", FALSE, ClocksStopwatchLapsRow_private_offset + G_STRUCT_OFFSET (ClocksStopwatchLapsRowPrivate, tot_label));
#line 351 "stopwatch.c"
}

static void
clocks_stopwatch_laps_row_instance_init (ClocksStopwatchLapsRow * self,
                                         gpointer klass)
{
#line 23 "../src/stopwatch.vala"
	self->priv = clocks_stopwatch_laps_row_get_instance_private (self);
#line 23 "../src/stopwatch.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 362 "stopwatch.c"
}

static void
clocks_stopwatch_laps_row_finalize (GObject * obj)
{
	ClocksStopwatchLapsRow * self;
#line 23 "../src/stopwatch.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_STOPWATCH_TYPE_LAPS_ROW, ClocksStopwatchLapsRow);
#line 25 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->slider);
#line 27 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->num_label);
#line 29 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->split_label);
#line 31 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->tot_label);
#line 23 "../src/stopwatch.vala"
	G_OBJECT_CLASS (clocks_stopwatch_laps_row_parent_class)->finalize (obj);
#line 381 "stopwatch.c"
}

GType
clocks_stopwatch_laps_row_get_type (void)
{
	static volatile gsize clocks_stopwatch_laps_row_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_stopwatch_laps_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksStopwatchLapsRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_stopwatch_laps_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksStopwatchLapsRow), 0, (GInstanceInitFunc) clocks_stopwatch_laps_row_instance_init, NULL };
		GType clocks_stopwatch_laps_row_type_id;
		clocks_stopwatch_laps_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "ClocksStopwatchLapsRow", &g_define_type_info, 0);
		ClocksStopwatchLapsRow_private_offset = g_type_add_instance_private (clocks_stopwatch_laps_row_type_id, sizeof (ClocksStopwatchLapsRowPrivate));
		g_once_init_leave (&clocks_stopwatch_laps_row_type_id__volatile, clocks_stopwatch_laps_row_type_id);
	}
	return clocks_stopwatch_laps_row_type_id__volatile;
}

static inline gpointer
clocks_stopwatch_face_get_instance_private (ClocksStopwatchFace* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksStopwatchFace_private_offset);
}

GType
clocks_stopwatch_face_state_get_type (void)
{
	static volatile gsize clocks_stopwatch_face_state_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_stopwatch_face_state_type_id__volatile)) {
		static const GEnumValue values[] = {{CLOCKS_STOPWATCH_FACE_STATE_RESET, "CLOCKS_STOPWATCH_FACE_STATE_RESET", "reset"}, {CLOCKS_STOPWATCH_FACE_STATE_RUNNING, "CLOCKS_STOPWATCH_FACE_STATE_RUNNING", "running"}, {CLOCKS_STOPWATCH_FACE_STATE_STOPPED, "CLOCKS_STOPWATCH_FACE_STATE_STOPPED", "stopped"}, {0, NULL, NULL}};
		GType clocks_stopwatch_face_state_type_id;
		clocks_stopwatch_face_state_type_id = g_enum_register_static ("ClocksStopwatchFaceState", values);
		g_once_init_leave (&clocks_stopwatch_face_state_type_id__volatile, clocks_stopwatch_face_state_type_id);
	}
	return clocks_stopwatch_face_state_type_id__volatile;
}

static GType
clocks_stopwatch_face_laps_column_get_type (void)
{
	static volatile gsize clocks_stopwatch_face_laps_column_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_stopwatch_face_laps_column_type_id__volatile)) {
		static const GEnumValue values[] = {{CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_LAP, "CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_LAP", "lap"}, {CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_SPLIT, "CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_SPLIT", "split"}, {CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_TOTAL, "CLOCKS_STOPWATCH_FACE_LAPS_COLUMN_TOTAL", "total"}, {0, NULL, NULL}};
		GType clocks_stopwatch_face_laps_column_type_id;
		clocks_stopwatch_face_laps_column_type_id = g_enum_register_static ("ClocksStopwatchFaceLapsColumn", values);
		g_once_init_leave (&clocks_stopwatch_face_laps_column_type_id__volatile, clocks_stopwatch_face_laps_column_type_id);
	}
	return clocks_stopwatch_face_laps_column_type_id__volatile;
}

static void
__lambda45_ (ClocksStopwatchFace* self,
             GtkWidget* w)
{
	ClocksStopwatchFaceState _tmp0_;
#line 89 "../src/stopwatch.vala"
	g_return_if_fail (w != NULL);
#line 90 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 90 "../src/stopwatch.vala"
	if (_tmp0_ == CLOCKS_STOPWATCH_FACE_STATE_RUNNING) {
#line 91 "../src/stopwatch.vala"
		clocks_stopwatch_face_update_time_label (self);
#line 92 "../src/stopwatch.vala"
		clocks_stopwatch_face_add_tick (self);
#line 445 "stopwatch.c"
	}
}

static void
___lambda45__gtk_widget_map (GtkWidget* _sender,
                             gpointer self)
{
#line 89 "../src/stopwatch.vala"
	__lambda45_ ((ClocksStopwatchFace*) self, _sender);
#line 455 "stopwatch.c"
}

static void
__lambda47_ (ClocksStopwatchFace* self,
             GtkListBoxRow* before,
             GtkListBoxRow* after)
{
#line 96 "../src/stopwatch.vala"
	g_return_if_fail (before != NULL);
#line 97 "../src/stopwatch.vala"
	if (after != NULL) {
#line 467 "stopwatch.c"
		GtkSeparator* separator = NULL;
		GtkSeparator* _tmp0_;
		GtkSeparator* _tmp1_;
		GtkSeparator* _tmp2_;
#line 98 "../src/stopwatch.vala"
		_tmp0_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 98 "../src/stopwatch.vala"
		g_object_ref_sink (_tmp0_);
#line 98 "../src/stopwatch.vala"
		separator = _tmp0_;
#line 99 "../src/stopwatch.vala"
		_tmp1_ = separator;
#line 99 "../src/stopwatch.vala"
		gtk_widget_show ((GtkWidget*) _tmp1_);
#line 100 "../src/stopwatch.vala"
		_tmp2_ = separator;
#line 100 "../src/stopwatch.vala"
		gtk_list_box_row_set_header (before, (GtkWidget*) _tmp2_);
#line 97 "../src/stopwatch.vala"
		_g_object_unref0 (separator);
#line 488 "stopwatch.c"
	}
}

static void
___lambda47__gtk_list_box_update_header_func (GtkListBoxRow* row,
                                              GtkListBoxRow* before,
                                              gpointer self)
{
#line 96 "../src/stopwatch.vala"
	__lambda47_ ((ClocksStopwatchFace*) self, row, before);
#line 499 "stopwatch.c"
}

static void
__lambda48_ (ClocksStopwatchFace* self,
             GtkWidget* w)
{
	ClocksStopwatchFaceState _tmp0_;
#line 104 "../src/stopwatch.vala"
	g_return_if_fail (w != NULL);
#line 105 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 105 "../src/stopwatch.vala"
	if (_tmp0_ == CLOCKS_STOPWATCH_FACE_STATE_RUNNING) {
#line 106 "../src/stopwatch.vala"
		clocks_stopwatch_face_remove_tick (self);
#line 515 "stopwatch.c"
	}
}

static void
___lambda48__gtk_widget_unmap (GtkWidget* _sender,
                               gpointer self)
{
#line 104 "../src/stopwatch.vala"
	__lambda48_ ((ClocksStopwatchFace*) self, _sender);
#line 525 "stopwatch.c"
}

ClocksStopwatchFace*
clocks_stopwatch_face_construct (GType object_type,
                                 ClocksHeaderBar* header_bar)
{
	ClocksStopwatchFace * self = NULL;
	GTimer* _tmp0_;
	GtkListBox* _tmp1_;
#line 80 "../src/stopwatch.vala"
	g_return_val_if_fail (header_bar != NULL, NULL);
#line 81 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) g_object_new (object_type, "label", _ ("Stopwatch"), "icon-name", "stopwatch-symbolic", "header-bar", header_bar, "panel-id", CLOCKS_PANEL_ID_STOPWATCH, NULL);
#line 86 "../src/stopwatch.vala"
	_tmp0_ = g_timer_new ();
#line 86 "../src/stopwatch.vala"
	_g_timer_destroy0 (self->priv->timer);
#line 86 "../src/stopwatch.vala"
	self->priv->timer = _tmp0_;
#line 87 "../src/stopwatch.vala"
	self->priv->tick_id = (guint) 0;
#line 89 "../src/stopwatch.vala"
	g_signal_connect_object ((GtkWidget*) self, "map", (GCallback) ___lambda45__gtk_widget_map, self, 0);
#line 96 "../src/stopwatch.vala"
	_tmp1_ = self->priv->laps_list;
#line 96 "../src/stopwatch.vala"
	gtk_list_box_set_header_func (_tmp1_, ___lambda47__gtk_list_box_update_header_func, g_object_ref (self), g_object_unref);
#line 104 "../src/stopwatch.vala"
	g_signal_connect_object ((GtkWidget*) self, "unmap", (GCallback) ___lambda48__gtk_widget_unmap, self, 0);
#line 110 "../src/stopwatch.vala"
	clocks_stopwatch_face_reset (self);
#line 80 "../src/stopwatch.vala"
	return self;
#line 559 "stopwatch.c"
}

ClocksStopwatchFace*
clocks_stopwatch_face_new (ClocksHeaderBar* header_bar)
{
#line 80 "../src/stopwatch.vala"
	return clocks_stopwatch_face_construct (CLOCKS_STOPWATCH_TYPE_FACE, header_bar);
#line 567 "stopwatch.c"
}

static void
clocks_stopwatch_face_on_left_button_clicked (ClocksStopwatchFace* self,
                                              GtkButton* button)
{
	ClocksStopwatchFaceState _tmp0_;
#line 114 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 114 "../src/stopwatch.vala"
	g_return_if_fail (button != NULL);
#line 115 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 115 "../src/stopwatch.vala"
	switch (_tmp0_) {
#line 115 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_RESET:
#line 115 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_STOPPED:
#line 587 "stopwatch.c"
		{
#line 118 "../src/stopwatch.vala"
			clocks_stopwatch_face_start (self);
#line 119 "../src/stopwatch.vala"
			break;
#line 593 "stopwatch.c"
		}
#line 115 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_RUNNING:
#line 597 "stopwatch.c"
		{
#line 121 "../src/stopwatch.vala"
			clocks_stopwatch_face_stop (self);
#line 122 "../src/stopwatch.vala"
			break;
#line 603 "stopwatch.c"
		}
		default:
		{
#line 124 "../src/stopwatch.vala"
			g_assert_not_reached ();
#line 609 "stopwatch.c"
		}
	}
}

static void
_clocks_stopwatch_face_on_left_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                  gpointer self)
{
#line 45 "../src/stopwatch.vala"
	clocks_stopwatch_face_on_left_button_clicked ((ClocksStopwatchFace*) self, _sender);
#line 620 "stopwatch.c"
}

static void
clocks_stopwatch_face_on_right_button_clicked (ClocksStopwatchFace* self,
                                               GtkButton* button)
{
	ClocksStopwatchFaceState _tmp0_;
#line 129 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 129 "../src/stopwatch.vala"
	g_return_if_fail (button != NULL);
#line 130 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 130 "../src/stopwatch.vala"
	switch (_tmp0_) {
#line 130 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_STOPPED:
#line 638 "stopwatch.c"
		{
#line 132 "../src/stopwatch.vala"
			clocks_stopwatch_face_reset (self);
#line 133 "../src/stopwatch.vala"
			break;
#line 644 "stopwatch.c"
		}
#line 130 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_RUNNING:
#line 648 "stopwatch.c"
		{
#line 135 "../src/stopwatch.vala"
			clocks_stopwatch_face_lap (self);
#line 136 "../src/stopwatch.vala"
			break;
#line 654 "stopwatch.c"
		}
		default:
		{
#line 138 "../src/stopwatch.vala"
			g_assert_not_reached ();
#line 660 "stopwatch.c"
		}
	}
}

static void
_clocks_stopwatch_face_on_right_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self)
{
#line 45 "../src/stopwatch.vala"
	clocks_stopwatch_face_on_right_button_clicked ((ClocksStopwatchFace*) self, _sender);
#line 671 "stopwatch.c"
}

static void
clocks_stopwatch_face_start (ClocksStopwatchFace* self)
{
	ClocksStopwatchFaceState _tmp0_;
	GtkButton* _tmp3_;
	GtkButton* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
#line 142 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 143 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 143 "../src/stopwatch.vala"
	if (_tmp0_ == CLOCKS_STOPWATCH_FACE_STATE_RESET) {
#line 689 "stopwatch.c"
		GTimer* _tmp1_;
#line 144 "../src/stopwatch.vala"
		_tmp1_ = self->priv->timer;
#line 144 "../src/stopwatch.vala"
		g_timer_start (_tmp1_);
#line 695 "stopwatch.c"
	} else {
		GTimer* _tmp2_;
#line 146 "../src/stopwatch.vala"
		_tmp2_ = self->priv->timer;
#line 146 "../src/stopwatch.vala"
		g_timer_continue (_tmp2_);
#line 702 "stopwatch.c"
	}
#line 148 "../src/stopwatch.vala"
	clocks_stopwatch_face_set_state (self, CLOCKS_STOPWATCH_FACE_STATE_RUNNING);
#line 149 "../src/stopwatch.vala"
	clocks_stopwatch_face_add_tick (self);
#line 150 "../src/stopwatch.vala"
	_tmp3_ = self->priv->left_button;
#line 150 "../src/stopwatch.vala"
	gtk_button_set_label (_tmp3_, _ ("Stop"));
#line 151 "../src/stopwatch.vala"
	_tmp4_ = self->priv->left_button;
#line 151 "../src/stopwatch.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 151 "../src/stopwatch.vala"
	gtk_style_context_add_class (_tmp5_, "destructive-action");
#line 152 "../src/stopwatch.vala"
	_tmp6_ = self->priv->right_button;
#line 152 "../src/stopwatch.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp6_, TRUE);
#line 153 "../src/stopwatch.vala"
	_tmp7_ = self->priv->right_button;
#line 153 "../src/stopwatch.vala"
	gtk_button_set_label (_tmp7_, _ ("Lap"));
#line 726 "stopwatch.c"
}

static void
clocks_stopwatch_face_stop (ClocksStopwatchFace* self)
{
	GTimer* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkButton* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
#line 156 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 157 "../src/stopwatch.vala"
	_tmp0_ = self->priv->timer;
#line 157 "../src/stopwatch.vala"
	g_timer_stop (_tmp0_);
#line 158 "../src/stopwatch.vala"
	clocks_stopwatch_face_set_state (self, CLOCKS_STOPWATCH_FACE_STATE_STOPPED);
#line 159 "../src/stopwatch.vala"
	clocks_stopwatch_face_remove_tick (self);
#line 160 "../src/stopwatch.vala"
	_tmp1_ = self->priv->left_button;
#line 160 "../src/stopwatch.vala"
	gtk_button_set_label (_tmp1_, _ ("Continue"));
#line 161 "../src/stopwatch.vala"
	_tmp2_ = self->priv->left_button;
#line 161 "../src/stopwatch.vala"
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
#line 161 "../src/stopwatch.vala"
	gtk_style_context_remove_class (_tmp3_, "destructive-action");
#line 162 "../src/stopwatch.vala"
	_tmp4_ = self->priv->left_button;
#line 162 "../src/stopwatch.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 162 "../src/stopwatch.vala"
	gtk_style_context_add_class (_tmp5_, "suggested-action");
#line 163 "../src/stopwatch.vala"
	_tmp6_ = self->priv->right_button;
#line 163 "../src/stopwatch.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp6_, TRUE);
#line 164 "../src/stopwatch.vala"
	_tmp7_ = self->priv->right_button;
#line 164 "../src/stopwatch.vala"
	gtk_button_set_label (_tmp7_, _ ("Reset"));
#line 774 "stopwatch.c"
}

static void
clocks_stopwatch_face_reset (ClocksStopwatchFace* self)
{
	GTimer* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkButton* _tmp4_;
	GtkListBox* _tmp5_;
	GList* _tmp6_;
#line 167 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 168 "../src/stopwatch.vala"
	_tmp0_ = self->priv->timer;
#line 168 "../src/stopwatch.vala"
	g_timer_reset (_tmp0_);
#line 169 "../src/stopwatch.vala"
	clocks_stopwatch_face_set_state (self, CLOCKS_STOPWATCH_FACE_STATE_RESET);
#line 170 "../src/stopwatch.vala"
	clocks_stopwatch_face_remove_tick (self);
#line 171 "../src/stopwatch.vala"
	clocks_stopwatch_face_update_time_label (self);
#line 172 "../src/stopwatch.vala"
	_tmp1_ = self->priv->left_button;
#line 172 "../src/stopwatch.vala"
	gtk_button_set_label (_tmp1_, _ ("Start"));
#line 173 "../src/stopwatch.vala"
	_tmp2_ = self->priv->left_button;
#line 173 "../src/stopwatch.vala"
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
#line 173 "../src/stopwatch.vala"
	gtk_style_context_add_class (_tmp3_, "suggested-action");
#line 174 "../src/stopwatch.vala"
	_tmp4_ = self->priv->right_button;
#line 174 "../src/stopwatch.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp4_, FALSE);
#line 175 "../src/stopwatch.vala"
	self->priv->current_lap = 0;
#line 176 "../src/stopwatch.vala"
	self->priv->last_lap_time = (gdouble) 0;
#line 177 "../src/stopwatch.vala"
	_tmp5_ = self->priv->laps_list;
#line 177 "../src/stopwatch.vala"
	_tmp6_ = gtk_container_get_children ((GtkContainer*) _tmp5_);
#line 821 "stopwatch.c"
	{
		GList* l_collection = NULL;
		GList* l_it = NULL;
#line 177 "../src/stopwatch.vala"
		l_collection = _tmp6_;
#line 177 "../src/stopwatch.vala"
		for (l_it = l_collection; l_it != NULL; l_it = l_it->next) {
#line 829 "stopwatch.c"
			GtkWidget* l = NULL;
#line 177 "../src/stopwatch.vala"
			l = (GtkWidget*) l_it->data;
#line 833 "stopwatch.c"
			{
				GtkListBox* _tmp7_;
				GtkWidget* _tmp8_;
#line 178 "../src/stopwatch.vala"
				_tmp7_ = self->priv->laps_list;
#line 178 "../src/stopwatch.vala"
				_tmp8_ = l;
#line 178 "../src/stopwatch.vala"
				gtk_container_remove ((GtkContainer*) _tmp7_, _tmp8_);
#line 843 "stopwatch.c"
			}
		}
#line 177 "../src/stopwatch.vala"
		(l_collection == NULL) ? NULL : (l_collection = (g_list_free (l_collection), NULL));
#line 848 "stopwatch.c"
	}
}

static void
clocks_stopwatch_face_lap (ClocksStopwatchFace* self)
{
	gdouble e = 0.0;
	GTimer* _tmp0_;
	gdouble split = 0.0;
	gint h = 0;
	gint m = 0;
	gint s = 0;
	gdouble r = 0.0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gdouble _tmp4_ = 0.0;
	gint cs = 0;
	gint split_h = 0;
	gint split_m = 0;
	gint split_s = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gdouble _tmp8_ = 0.0;
	gint split_cs = 0;
	gchar* n_label = NULL;
	gchar* _tmp9_;
	gchar* split_label = NULL;
	gchar* tot_label = NULL;
	ClocksStopwatchLapsRow* row = NULL;
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	const gchar* _tmp16_;
	ClocksStopwatchLapsRow* _tmp17_;
	GtkListBox* _tmp18_;
	GtkScrolledWindow* _tmp19_;
	GtkAdjustment* _tmp20_;
	GtkAdjustment* _tmp21_;
	GtkScrolledWindow* _tmp22_;
	GtkAdjustment* _tmp23_;
	GtkAdjustment* _tmp24_;
	gdouble _tmp25_;
	gdouble _tmp26_;
#line 182 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 183 "../src/stopwatch.vala"
	self->priv->current_lap = self->priv->current_lap + 1;
#line 184 "../src/stopwatch.vala"
	_tmp0_ = self->priv->timer;
#line 184 "../src/stopwatch.vala"
	e = g_timer_elapsed (_tmp0_, NULL);
#line 185 "../src/stopwatch.vala"
	split = e - self->priv->last_lap_time;
#line 192 "../src/stopwatch.vala"
	self->priv->last_lap_time = floor (e * 100) / 100;
#line 198 "../src/stopwatch.vala"
	clocks_utils_time_to_hms (e, &_tmp1_, &_tmp2_, &_tmp3_, &_tmp4_);
#line 198 "../src/stopwatch.vala"
	h = _tmp1_;
#line 198 "../src/stopwatch.vala"
	m = _tmp2_;
#line 198 "../src/stopwatch.vala"
	s = _tmp3_;
#line 198 "../src/stopwatch.vala"
	r = _tmp4_;
#line 199 "../src/stopwatch.vala"
	cs = (gint) (r * 100);
#line 204 "../src/stopwatch.vala"
	clocks_utils_time_to_hms (split, &_tmp5_, &_tmp6_, &_tmp7_, &_tmp8_);
#line 204 "../src/stopwatch.vala"
	split_h = _tmp5_;
#line 204 "../src/stopwatch.vala"
	split_m = _tmp6_;
#line 204 "../src/stopwatch.vala"
	split_s = _tmp7_;
#line 204 "../src/stopwatch.vala"
	r = _tmp8_;
#line 205 "../src/stopwatch.vala"
	split_cs = (gint) (r * 100);
#line 207 "../src/stopwatch.vala"
	_tmp9_ = g_strdup_printf ("#%d", self->priv->current_lap);
#line 207 "../src/stopwatch.vala"
	n_label = _tmp9_;
#line 213 "../src/stopwatch.vala"
	if (split_h > 0) {
#line 935 "stopwatch.c"
		gchar* _tmp10_;
#line 214 "../src/stopwatch.vala"
		_tmp10_ = g_strdup_printf ("%i\u200E∶%02i\u200E∶%02i.%02i", split_h, split_m, split_s, split_cs);
#line 214 "../src/stopwatch.vala"
		_g_free0 (split_label);
#line 214 "../src/stopwatch.vala"
		split_label = _tmp10_;
#line 943 "stopwatch.c"
	} else {
		gchar* _tmp11_;
#line 216 "../src/stopwatch.vala"
		_tmp11_ = g_strdup_printf ("%02i\u200E∶%02i.%02i", split_m, split_s, split_cs);
#line 216 "../src/stopwatch.vala"
		_g_free0 (split_label);
#line 216 "../src/stopwatch.vala"
		split_label = _tmp11_;
#line 952 "stopwatch.c"
	}
#line 220 "../src/stopwatch.vala"
	if (h > 0) {
#line 956 "stopwatch.c"
		gchar* _tmp12_;
#line 221 "../src/stopwatch.vala"
		_tmp12_ = g_strdup_printf ("%i\u200E∶%02i\u200E∶%02i.%02i", h, m, s, cs);
#line 221 "../src/stopwatch.vala"
		_g_free0 (tot_label);
#line 221 "../src/stopwatch.vala"
		tot_label = _tmp12_;
#line 964 "stopwatch.c"
	} else {
		gchar* _tmp13_;
#line 223 "../src/stopwatch.vala"
		_tmp13_ = g_strdup_printf ("%02i\u200E∶%02i.%02i", m, s, cs);
#line 223 "../src/stopwatch.vala"
		_g_free0 (tot_label);
#line 223 "../src/stopwatch.vala"
		tot_label = _tmp13_;
#line 973 "stopwatch.c"
	}
#line 226 "../src/stopwatch.vala"
	_tmp14_ = n_label;
#line 226 "../src/stopwatch.vala"
	_tmp15_ = split_label;
#line 226 "../src/stopwatch.vala"
	_tmp16_ = tot_label;
#line 226 "../src/stopwatch.vala"
	_tmp17_ = clocks_stopwatch_laps_row_new (_tmp14_, _tmp15_, _tmp16_);
#line 226 "../src/stopwatch.vala"
	g_object_ref_sink (_tmp17_);
#line 226 "../src/stopwatch.vala"
	row = _tmp17_;
#line 227 "../src/stopwatch.vala"
	_tmp18_ = self->priv->laps_list;
#line 227 "../src/stopwatch.vala"
	gtk_list_box_prepend (_tmp18_, (GtkWidget*) row);
#line 228 "../src/stopwatch.vala"
	clocks_stopwatch_laps_row_slide_in (row);
#line 229 "../src/stopwatch.vala"
	_tmp19_ = self->priv->laps_scrollwin;
#line 229 "../src/stopwatch.vala"
	_tmp20_ = gtk_scrolled_window_get_vadjustment (_tmp19_);
#line 229 "../src/stopwatch.vala"
	_tmp21_ = _tmp20_;
#line 229 "../src/stopwatch.vala"
	_tmp22_ = self->priv->laps_scrollwin;
#line 229 "../src/stopwatch.vala"
	_tmp23_ = gtk_scrolled_window_get_vadjustment (_tmp22_);
#line 229 "../src/stopwatch.vala"
	_tmp24_ = _tmp23_;
#line 229 "../src/stopwatch.vala"
	_tmp25_ = gtk_adjustment_get_lower (_tmp24_);
#line 229 "../src/stopwatch.vala"
	_tmp26_ = _tmp25_;
#line 229 "../src/stopwatch.vala"
	gtk_adjustment_set_value (_tmp21_, _tmp26_);
#line 182 "../src/stopwatch.vala"
	_g_object_unref0 (row);
#line 182 "../src/stopwatch.vala"
	_g_free0 (tot_label);
#line 182 "../src/stopwatch.vala"
	_g_free0 (split_label);
#line 182 "../src/stopwatch.vala"
	_g_free0 (n_label);
#line 1019 "stopwatch.c"
}

static gboolean
___lambda46_ (ClocksStopwatchFace* self,
              GtkWidget* c)
{
	gboolean result = FALSE;
#line 234 "../src/stopwatch.vala"
	g_return_val_if_fail (c != NULL, FALSE);
#line 235 "../src/stopwatch.vala"
	result = clocks_stopwatch_face_update_time_label (self);
#line 235 "../src/stopwatch.vala"
	return result;
#line 1033 "stopwatch.c"
}

static gboolean
____lambda46__gtk_tick_callback (GtkWidget* widget,
                                 GdkFrameClock* frame_clock,
                                 gpointer self)
{
	gboolean result;
	result = ___lambda46_ ((ClocksStopwatchFace*) self, widget);
#line 234 "../src/stopwatch.vala"
	return result;
#line 1045 "stopwatch.c"
}

static void
clocks_stopwatch_face_add_tick (ClocksStopwatchFace* self)
{
#line 232 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 233 "../src/stopwatch.vala"
	if (self->priv->tick_id == ((guint) 0)) {
#line 234 "../src/stopwatch.vala"
		self->priv->tick_id = gtk_widget_add_tick_callback ((GtkWidget*) self, ____lambda46__gtk_tick_callback, g_object_ref (self), g_object_unref);
#line 1057 "stopwatch.c"
	}
}

static void
clocks_stopwatch_face_remove_tick (ClocksStopwatchFace* self)
{
#line 240 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 241 "../src/stopwatch.vala"
	if (self->priv->tick_id != ((guint) 0)) {
#line 242 "../src/stopwatch.vala"
		gtk_widget_remove_tick_callback ((GtkWidget*) self, self->priv->tick_id);
#line 243 "../src/stopwatch.vala"
		self->priv->tick_id = (guint) 0;
#line 1072 "stopwatch.c"
	}
}

static gboolean
clocks_stopwatch_face_update_time_label (ClocksStopwatchFace* self)
{
	gint h = 0;
	gint m = 0;
	gint s = 0;
	gdouble r = 0.0;
	ClocksStopwatchFaceState _tmp0_;
	gint ds = 0;
	gboolean result = FALSE;
#line 247 "../src/stopwatch.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 248 "../src/stopwatch.vala"
	h = 0;
#line 249 "../src/stopwatch.vala"
	m = 0;
#line 250 "../src/stopwatch.vala"
	s = 0;
#line 251 "../src/stopwatch.vala"
	r = (gdouble) 0;
#line 252 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 252 "../src/stopwatch.vala"
	if (_tmp0_ != CLOCKS_STOPWATCH_FACE_STATE_RESET) {
#line 1100 "stopwatch.c"
		GTimer* _tmp1_;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gdouble _tmp5_ = 0.0;
#line 253 "../src/stopwatch.vala"
		_tmp1_ = self->priv->timer;
#line 253 "../src/stopwatch.vala"
		clocks_utils_time_to_hms (g_timer_elapsed (_tmp1_, NULL), &_tmp2_, &_tmp3_, &_tmp4_, &_tmp5_);
#line 253 "../src/stopwatch.vala"
		h = _tmp2_;
#line 253 "../src/stopwatch.vala"
		m = _tmp3_;
#line 253 "../src/stopwatch.vala"
		s = _tmp4_;
#line 253 "../src/stopwatch.vala"
		r = _tmp5_;
#line 1118 "stopwatch.c"
	}
#line 256 "../src/stopwatch.vala"
	ds = (gint) (r * 10);
#line 260 "../src/stopwatch.vala"
	if (h > 0) {
#line 1124 "stopwatch.c"
		GtkLabel* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
#line 261 "../src/stopwatch.vala"
		_tmp6_ = self->priv->time_label;
#line 261 "../src/stopwatch.vala"
		_tmp7_ = g_strdup_printf ("%i\u200E∶%02i\u200E∶%02i.%i", h, m, s, ds);
#line 261 "../src/stopwatch.vala"
		_tmp8_ = _tmp7_;
#line 261 "../src/stopwatch.vala"
		gtk_label_set_text (_tmp6_, _tmp8_);
#line 261 "../src/stopwatch.vala"
		_g_free0 (_tmp8_);
#line 1138 "stopwatch.c"
	} else {
		GtkLabel* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
#line 263 "../src/stopwatch.vala"
		_tmp9_ = self->priv->time_label;
#line 263 "../src/stopwatch.vala"
		_tmp10_ = g_strdup_printf ("%02i\u200E∶%02i.%i", m, s, ds);
#line 263 "../src/stopwatch.vala"
		_tmp11_ = _tmp10_;
#line 263 "../src/stopwatch.vala"
		gtk_label_set_text (_tmp9_, _tmp11_);
#line 263 "../src/stopwatch.vala"
		_g_free0 (_tmp11_);
#line 1153 "stopwatch.c"
	}
#line 265 "../src/stopwatch.vala"
	result = TRUE;
#line 265 "../src/stopwatch.vala"
	return result;
#line 1159 "stopwatch.c"
}

static void
clocks_stopwatch_face_real_grab_focus (GtkWidget* base)
{
	ClocksStopwatchFace * self;
	GtkButton* _tmp0_;
#line 268 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 269 "../src/stopwatch.vala"
	_tmp0_ = self->priv->left_button;
#line 269 "../src/stopwatch.vala"
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
#line 1173 "stopwatch.c"
}

static gboolean
clocks_stopwatch_face_real_escape_pressed (ClocksClock* base)
{
	ClocksStopwatchFace * self;
	ClocksStopwatchFaceState _tmp0_;
	gboolean result = FALSE;
#line 272 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 273 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 273 "../src/stopwatch.vala"
	switch (_tmp0_) {
#line 273 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_RESET:
#line 1190 "stopwatch.c"
		{
#line 275 "../src/stopwatch.vala"
			result = FALSE;
#line 275 "../src/stopwatch.vala"
			return result;
#line 1196 "stopwatch.c"
		}
#line 273 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_STOPPED:
#line 1200 "stopwatch.c"
		{
#line 277 "../src/stopwatch.vala"
			clocks_stopwatch_face_reset (self);
#line 278 "../src/stopwatch.vala"
			break;
#line 1206 "stopwatch.c"
		}
#line 273 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_RUNNING:
#line 1210 "stopwatch.c"
		{
#line 280 "../src/stopwatch.vala"
			clocks_stopwatch_face_stop (self);
#line 281 "../src/stopwatch.vala"
			break;
#line 1216 "stopwatch.c"
		}
		default:
		{
#line 283 "../src/stopwatch.vala"
			g_assert_not_reached ();
#line 1222 "stopwatch.c"
		}
	}
#line 286 "../src/stopwatch.vala"
	result = TRUE;
#line 286 "../src/stopwatch.vala"
	return result;
#line 1229 "stopwatch.c"
}

static const gchar*
clocks_stopwatch_face_real_get_label (ClocksClock* base)
{
	const gchar* result;
	ClocksStopwatchFace* self;
	const gchar* _tmp0_;
#line 58 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 58 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_label;
#line 58 "../src/stopwatch.vala"
	result = _tmp0_;
#line 58 "../src/stopwatch.vala"
	return result;
#line 1246 "stopwatch.c"
}

static void
clocks_stopwatch_face_real_set_label (ClocksClock* base,
                                      const gchar* value)
{
	ClocksStopwatchFace* self;
#line 58 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 58 "../src/stopwatch.vala"
	if (g_strcmp0 (value, clocks_stopwatch_face_real_get_label (base)) != 0) {
#line 1258 "stopwatch.c"
		gchar* _tmp0_;
#line 58 "../src/stopwatch.vala"
		_tmp0_ = g_strdup (value);
#line 58 "../src/stopwatch.vala"
		_g_free0 (self->priv->_label);
#line 58 "../src/stopwatch.vala"
		self->priv->_label = _tmp0_;
#line 58 "../src/stopwatch.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY]);
#line 1268 "stopwatch.c"
	}
}

static const gchar*
clocks_stopwatch_face_real_get_icon_name (ClocksClock* base)
{
	const gchar* result;
	ClocksStopwatchFace* self;
	const gchar* _tmp0_;
#line 59 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 59 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_icon_name;
#line 59 "../src/stopwatch.vala"
	result = _tmp0_;
#line 59 "../src/stopwatch.vala"
	return result;
#line 1286 "stopwatch.c"
}

static void
clocks_stopwatch_face_real_set_icon_name (ClocksClock* base,
                                          const gchar* value)
{
	ClocksStopwatchFace* self;
#line 59 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 59 "../src/stopwatch.vala"
	if (g_strcmp0 (value, clocks_stopwatch_face_real_get_icon_name (base)) != 0) {
#line 1298 "stopwatch.c"
		gchar* _tmp0_;
#line 59 "../src/stopwatch.vala"
		_tmp0_ = g_strdup (value);
#line 59 "../src/stopwatch.vala"
		_g_free0 (self->priv->_icon_name);
#line 59 "../src/stopwatch.vala"
		self->priv->_icon_name = _tmp0_;
#line 59 "../src/stopwatch.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY]);
#line 1308 "stopwatch.c"
	}
}

static ClocksHeaderBar*
clocks_stopwatch_face_real_get_header_bar (ClocksClock* base)
{
	ClocksHeaderBar* result;
	ClocksStopwatchFace* self;
	ClocksHeaderBar* _tmp0_;
#line 60 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 60 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_header_bar;
#line 60 "../src/stopwatch.vala"
	result = _tmp0_;
#line 60 "../src/stopwatch.vala"
	return result;
#line 1326 "stopwatch.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 60 "../src/stopwatch.vala"
	return self ? g_object_ref (self) : NULL;
#line 1334 "stopwatch.c"
}

static void
clocks_stopwatch_face_real_set_header_bar (ClocksClock* base,
                                           ClocksHeaderBar* value)
{
	ClocksStopwatchFace* self;
#line 60 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 60 "../src/stopwatch.vala"
	if (clocks_stopwatch_face_real_get_header_bar (base) != value) {
#line 1346 "stopwatch.c"
		ClocksHeaderBar* _tmp0_;
#line 60 "../src/stopwatch.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 60 "../src/stopwatch.vala"
		_g_object_unref0 (self->priv->_header_bar);
#line 60 "../src/stopwatch.vala"
		self->priv->_header_bar = _tmp0_;
#line 60 "../src/stopwatch.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY]);
#line 1356 "stopwatch.c"
	}
}

static ClocksPanelId
clocks_stopwatch_face_real_get_panel_id (ClocksClock* base)
{
	ClocksPanelId result;
	ClocksStopwatchFace* self;
	ClocksPanelId _tmp0_;
#line 61 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 61 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_panel_id;
#line 61 "../src/stopwatch.vala"
	result = _tmp0_;
#line 61 "../src/stopwatch.vala"
	return result;
#line 1374 "stopwatch.c"
}

static void
clocks_stopwatch_face_real_set_panel_id (ClocksClock* base,
                                         ClocksPanelId value)
{
	ClocksStopwatchFace* self;
#line 61 "../src/stopwatch.vala"
	self = (ClocksStopwatchFace*) base;
#line 61 "../src/stopwatch.vala"
	if (clocks_stopwatch_face_real_get_panel_id (base) != value) {
#line 61 "../src/stopwatch.vala"
		self->priv->_panel_id = value;
#line 61 "../src/stopwatch.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY]);
#line 1390 "stopwatch.c"
	}
}

ClocksStopwatchFaceState
clocks_stopwatch_face_get_state (ClocksStopwatchFace* self)
{
	ClocksStopwatchFaceState result;
	ClocksStopwatchFaceState _tmp0_;
#line 63 "../src/stopwatch.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 63 "../src/stopwatch.vala"
	_tmp0_ = self->priv->_state;
#line 63 "../src/stopwatch.vala"
	result = _tmp0_;
#line 63 "../src/stopwatch.vala"
	return result;
#line 1407 "stopwatch.c"
}

static void
clocks_stopwatch_face_set_state (ClocksStopwatchFace* self,
                                 ClocksStopwatchFaceState value)
{
#line 63 "../src/stopwatch.vala"
	g_return_if_fail (self != NULL);
#line 63 "../src/stopwatch.vala"
	if (clocks_stopwatch_face_get_state (self) != value) {
#line 63 "../src/stopwatch.vala"
		self->priv->_state = value;
#line 63 "../src/stopwatch.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_STATE_PROPERTY]);
#line 1422 "stopwatch.c"
	}
}

static void
clocks_stopwatch_face_class_init (ClocksStopwatchFaceClass * klass,
                                  gpointer klass_data)
{
#line 45 "../src/stopwatch.vala"
	clocks_stopwatch_face_parent_class = g_type_class_peek_parent (klass);
#line 45 "../src/stopwatch.vala"
	g_type_class_adjust_private_offset (klass, &ClocksStopwatchFace_private_offset);
#line 45 "../src/stopwatch.vala"
	((GtkWidgetClass *) klass)->grab_focus = (void (*) (GtkWidget*)) clocks_stopwatch_face_real_grab_focus;
#line 45 "../src/stopwatch.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_clocks_stopwatch_face_get_property;
#line 45 "../src/stopwatch.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_clocks_stopwatch_face_set_property;
#line 45 "../src/stopwatch.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_stopwatch_face_finalize;
#line 45 "../src/stopwatch.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY] = g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 45 "../src/stopwatch.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY] = g_param_spec_string ("icon-name", "icon-name", "icon-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 45 "../src/stopwatch.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY] = g_param_spec_object ("header-bar", "header-bar", "header-bar", CLOCKS_TYPE_HEADER_BAR, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 45 "../src/stopwatch.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY] = g_param_spec_enum ("panel-id", "panel-id", "panel-id", CLOCKS_TYPE_PANEL_ID, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 45 "../src/stopwatch.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_STOPWATCH_FACE_STATE_PROPERTY, clocks_stopwatch_face_properties[CLOCKS_STOPWATCH_FACE_STATE_PROPERTY] = g_param_spec_enum ("state", "state", "state", CLOCKS_STOPWATCH_FACE_TYPE_STATE, CLOCKS_STOPWATCH_FACE_STATE_RESET, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/clocks/ui/stopwatch.ui");
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "time_label", FALSE, ClocksStopwatchFace_private_offset + G_STRUCT_OFFSET (ClocksStopwatchFacePrivate, time_label));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "left_button", FALSE, ClocksStopwatchFace_private_offset + G_STRUCT_OFFSET (ClocksStopwatchFacePrivate, left_button));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "right_button", FALSE, ClocksStopwatchFace_private_offset + G_STRUCT_OFFSET (ClocksStopwatchFacePrivate, right_button));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "laps_scrollwin", FALSE, ClocksStopwatchFace_private_offset + G_STRUCT_OFFSET (ClocksStopwatchFacePrivate, laps_scrollwin));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "laps_list", FALSE, ClocksStopwatchFace_private_offset + G_STRUCT_OFFSET (ClocksStopwatchFacePrivate, laps_list));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_left_button_clicked", G_CALLBACK(_clocks_stopwatch_face_on_left_button_clicked_gtk_button_clicked));
#line 45 "../src/stopwatch.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_right_button_clicked", G_CALLBACK(_clocks_stopwatch_face_on_right_button_clicked_gtk_button_clicked));
#line 1468 "stopwatch.c"
}

static void
clocks_stopwatch_face_clocks_clock_interface_init (ClocksClockIface * iface,
                                                   gpointer iface_data)
{
#line 45 "../src/stopwatch.vala"
	clocks_stopwatch_face_clocks_clock_parent_iface = g_type_interface_peek_parent (iface);
#line 45 "../src/stopwatch.vala"
	iface->escape_pressed = (gboolean (*) (ClocksClock*)) clocks_stopwatch_face_real_escape_pressed;
#line 45 "../src/stopwatch.vala"
	iface->get_label = clocks_stopwatch_face_real_get_label;
#line 45 "../src/stopwatch.vala"
	iface->set_label = clocks_stopwatch_face_real_set_label;
#line 45 "../src/stopwatch.vala"
	iface->get_icon_name = clocks_stopwatch_face_real_get_icon_name;
#line 45 "../src/stopwatch.vala"
	iface->set_icon_name = clocks_stopwatch_face_real_set_icon_name;
#line 45 "../src/stopwatch.vala"
	iface->get_header_bar = clocks_stopwatch_face_real_get_header_bar;
#line 45 "../src/stopwatch.vala"
	iface->set_header_bar = clocks_stopwatch_face_real_set_header_bar;
#line 45 "../src/stopwatch.vala"
	iface->get_panel_id = clocks_stopwatch_face_real_get_panel_id;
#line 45 "../src/stopwatch.vala"
	iface->set_panel_id = clocks_stopwatch_face_real_set_panel_id;
#line 1495 "stopwatch.c"
}

static void
clocks_stopwatch_face_instance_init (ClocksStopwatchFace * self,
                                     gpointer klass)
{
#line 45 "../src/stopwatch.vala"
	self->priv = clocks_stopwatch_face_get_instance_private (self);
#line 63 "../src/stopwatch.vala"
	self->priv->_state = CLOCKS_STOPWATCH_FACE_STATE_RESET;
#line 45 "../src/stopwatch.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1508 "stopwatch.c"
}

static void
clocks_stopwatch_face_finalize (GObject * obj)
{
	ClocksStopwatchFace * self;
#line 45 "../src/stopwatch.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace);
#line 58 "../src/stopwatch.vala"
	_g_free0 (self->priv->_label);
#line 59 "../src/stopwatch.vala"
	_g_free0 (self->priv->_icon_name);
#line 60 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->_header_bar);
#line 65 "../src/stopwatch.vala"
	_g_timer_destroy0 (self->priv->timer);
#line 70 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->time_label);
#line 72 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->left_button);
#line 74 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->right_button);
#line 76 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->laps_scrollwin);
#line 78 "../src/stopwatch.vala"
	_g_object_unref0 (self->priv->laps_list);
#line 45 "../src/stopwatch.vala"
	G_OBJECT_CLASS (clocks_stopwatch_face_parent_class)->finalize (obj);
#line 1537 "stopwatch.c"
}

GType
clocks_stopwatch_face_get_type (void)
{
	static volatile gsize clocks_stopwatch_face_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_stopwatch_face_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksStopwatchFaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_stopwatch_face_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksStopwatchFace), 0, (GInstanceInitFunc) clocks_stopwatch_face_instance_init, NULL };
		static const GInterfaceInfo clocks_clock_info = { (GInterfaceInitFunc) clocks_stopwatch_face_clocks_clock_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType clocks_stopwatch_face_type_id;
		clocks_stopwatch_face_type_id = g_type_register_static (gtk_box_get_type (), "ClocksStopwatchFace", &g_define_type_info, 0);
		g_type_add_interface_static (clocks_stopwatch_face_type_id, CLOCKS_TYPE_CLOCK, &clocks_clock_info);
		ClocksStopwatchFace_private_offset = g_type_add_instance_private (clocks_stopwatch_face_type_id, sizeof (ClocksStopwatchFacePrivate));
		g_once_init_leave (&clocks_stopwatch_face_type_id__volatile, clocks_stopwatch_face_type_id);
	}
	return clocks_stopwatch_face_type_id__volatile;
}

static void
_vala_clocks_stopwatch_face_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec)
{
	ClocksStopwatchFace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace);
#line 45 "../src/stopwatch.vala"
	switch (property_id) {
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY:
#line 45 "../src/stopwatch.vala"
		g_value_set_string (value, clocks_clock_get_label ((ClocksClock*) self));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY:
#line 45 "../src/stopwatch.vala"
		g_value_set_string (value, clocks_clock_get_icon_name ((ClocksClock*) self));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY:
#line 45 "../src/stopwatch.vala"
		g_value_set_object (value, clocks_clock_get_header_bar ((ClocksClock*) self));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY:
#line 45 "../src/stopwatch.vala"
		g_value_set_enum (value, clocks_clock_get_panel_id ((ClocksClock*) self));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_PROPERTY:
#line 45 "../src/stopwatch.vala"
		g_value_set_enum (value, clocks_stopwatch_face_get_state (self));
#line 45 "../src/stopwatch.vala"
		break;
#line 1596 "stopwatch.c"
		default:
#line 45 "../src/stopwatch.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 45 "../src/stopwatch.vala"
		break;
#line 1602 "stopwatch.c"
	}
}

static void
_vala_clocks_stopwatch_face_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec)
{
	ClocksStopwatchFace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace);
#line 45 "../src/stopwatch.vala"
	switch (property_id) {
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_LABEL_PROPERTY:
#line 45 "../src/stopwatch.vala"
		clocks_clock_set_label ((ClocksClock*) self, g_value_get_string (value));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_ICON_NAME_PROPERTY:
#line 45 "../src/stopwatch.vala"
		clocks_clock_set_icon_name ((ClocksClock*) self, g_value_get_string (value));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_HEADER_BAR_PROPERTY:
#line 45 "../src/stopwatch.vala"
		clocks_clock_set_header_bar ((ClocksClock*) self, g_value_get_object (value));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_PANEL_ID_PROPERTY:
#line 45 "../src/stopwatch.vala"
		clocks_clock_set_panel_id ((ClocksClock*) self, g_value_get_enum (value));
#line 45 "../src/stopwatch.vala"
		break;
#line 45 "../src/stopwatch.vala"
		case CLOCKS_STOPWATCH_FACE_STATE_PROPERTY:
#line 45 "../src/stopwatch.vala"
		clocks_stopwatch_face_set_state (self, g_value_get_enum (value));
#line 45 "../src/stopwatch.vala"
		break;
#line 1646 "stopwatch.c"
		default:
#line 45 "../src/stopwatch.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 45 "../src/stopwatch.vala"
		break;
#line 1652 "stopwatch.c"
	}
}

