/* utils.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from utils.vala, do not modify */

/*
 * Copyright (C) 2013  Paolo Borelli <pborelli@gnome.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <float.h>
#include <math.h>
#include <glib-object.h>
#include <libgnome-desktop/gnome-wall-clock.h>
#include <glib/gi18n-lib.h>
#include <gobject/gvaluecollector.h>
#include <gsound.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define CLOCKS_UTILS_TYPE_WALL_CLOCK (clocks_utils_wall_clock_get_type ())
#define CLOCKS_UTILS_WALL_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClock))
#define CLOCKS_UTILS_WALL_CLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClockClass))
#define CLOCKS_UTILS_IS_WALL_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_UTILS_TYPE_WALL_CLOCK))
#define CLOCKS_UTILS_IS_WALL_CLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_UTILS_TYPE_WALL_CLOCK))
#define CLOCKS_UTILS_WALL_CLOCK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClockClass))

typedef struct _ClocksUtilsWallClock ClocksUtilsWallClock;
typedef struct _ClocksUtilsWallClockClass ClocksUtilsWallClockClass;
typedef struct _ClocksUtilsWallClockPrivate ClocksUtilsWallClockPrivate;
typedef enum  {
	CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE,
	CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWENTYFOUR
} ClocksUtilsWallClockFormat;

#define CLOCKS_UTILS_WALL_CLOCK_TYPE_FORMAT (clocks_utils_wall_clock_format_get_type ())
enum  {
	CLOCKS_UTILS_WALL_CLOCK_0_PROPERTY,
	CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY,
	CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY,
	CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY,
	CLOCKS_UTILS_WALL_CLOCK_NUM_PROPERTIES
};
static GParamSpec* clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_NUM_PROPERTIES];
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_time_zone_unref0(var) ((var == NULL) ? NULL : (var = (g_time_zone_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
enum  {
	CLOCKS_UTILS_WALL_CLOCK_TICK_SIGNAL,
	CLOCKS_UTILS_WALL_CLOCK_NUM_SIGNALS
};
static guint clocks_utils_wall_clock_signals[CLOCKS_UTILS_WALL_CLOCK_NUM_SIGNALS] = {0};

#define CLOCKS_UTILS_TYPE_WEEKDAYS (clocks_utils_weekdays_get_type ())
#define CLOCKS_UTILS_WEEKDAYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_UTILS_TYPE_WEEKDAYS, ClocksUtilsWeekdays))
#define CLOCKS_UTILS_WEEKDAYS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_UTILS_TYPE_WEEKDAYS, ClocksUtilsWeekdaysClass))
#define CLOCKS_UTILS_IS_WEEKDAYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_UTILS_TYPE_WEEKDAYS))
#define CLOCKS_UTILS_IS_WEEKDAYS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_UTILS_TYPE_WEEKDAYS))
#define CLOCKS_UTILS_WEEKDAYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_UTILS_TYPE_WEEKDAYS, ClocksUtilsWeekdaysClass))

typedef struct _ClocksUtilsWeekdays ClocksUtilsWeekdays;
typedef struct _ClocksUtilsWeekdaysClass ClocksUtilsWeekdaysClass;
typedef struct _ClocksUtilsWeekdaysPrivate ClocksUtilsWeekdaysPrivate;
typedef enum  {
	CLOCKS_UTILS_WEEKDAYS_DAY_MON,
	CLOCKS_UTILS_WEEKDAYS_DAY_TUE,
	CLOCKS_UTILS_WEEKDAYS_DAY_WED,
	CLOCKS_UTILS_WEEKDAYS_DAY_THU,
	CLOCKS_UTILS_WEEKDAYS_DAY_FRI,
	CLOCKS_UTILS_WEEKDAYS_DAY_SAT,
	CLOCKS_UTILS_WEEKDAYS_DAY_SUN
} ClocksUtilsWeekdaysDay;

#define CLOCKS_UTILS_WEEKDAYS_TYPE_DAY (clocks_utils_weekdays_day_get_type ())
#define _g_variant_type_free0(var) ((var == NULL) ? NULL : (var = (g_variant_type_free (var), NULL)))
#define _g_variant_builder_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_builder_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_variant_iter_free0(var) ((var == NULL) ? NULL : (var = (g_variant_iter_free (var), NULL)))
#define _clocks_utils_weekdays_unref0(var) ((var == NULL) ? NULL : (var = (clocks_utils_weekdays_unref (var), NULL)))
typedef struct _ClocksUtilsParamSpecWeekdays ClocksUtilsParamSpecWeekdays;

#define CLOCKS_UTILS_TYPE_BELL (clocks_utils_bell_get_type ())
#define CLOCKS_UTILS_BELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_UTILS_TYPE_BELL, ClocksUtilsBell))
#define CLOCKS_UTILS_BELL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_UTILS_TYPE_BELL, ClocksUtilsBellClass))
#define CLOCKS_UTILS_IS_BELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_UTILS_TYPE_BELL))
#define CLOCKS_UTILS_IS_BELL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_UTILS_TYPE_BELL))
#define CLOCKS_UTILS_BELL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_UTILS_TYPE_BELL, ClocksUtilsBellClass))

typedef struct _ClocksUtilsBell ClocksUtilsBell;
typedef struct _ClocksUtilsBellClass ClocksUtilsBellClass;
typedef struct _ClocksUtilsBellPrivate ClocksUtilsBellPrivate;
enum  {
	CLOCKS_UTILS_BELL_0_PROPERTY,
	CLOCKS_UTILS_BELL_NUM_PROPERTIES
};
static GParamSpec* clocks_utils_bell_properties[CLOCKS_UTILS_BELL_NUM_PROPERTIES];
typedef struct _ClocksUtilsBellRingRealData ClocksUtilsBellRingRealData;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ClocksUtilsWallClock {
	GObject parent_instance;
	ClocksUtilsWallClockPrivate * priv;
};

struct _ClocksUtilsWallClockClass {
	GObjectClass parent_class;
};

struct _ClocksUtilsWallClockPrivate {
	GDateTime* _date_time;
	GTimeZone* _timezone;
	ClocksUtilsWallClockFormat _format;
	GSettings* settings;
	GnomeWallClock* wc;
};

struct _ClocksUtilsWeekdays {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ClocksUtilsWeekdaysPrivate * priv;
};

struct _ClocksUtilsWeekdaysClass {
	GTypeClass parent_class;
	void (*finalize) (ClocksUtilsWeekdays *self);
};

struct _ClocksUtilsWeekdaysPrivate {
	gboolean* days;
	gint days_length1;
	gint _days_size_;
};

struct _ClocksUtilsParamSpecWeekdays {
	GParamSpec parent_instance;
};

struct _ClocksUtilsBell {
	GObject parent_instance;
	ClocksUtilsBellPrivate * priv;
};

struct _ClocksUtilsBellClass {
	GObjectClass parent_class;
};

struct _ClocksUtilsBellPrivate {
	GSoundContext* gsound;
	GCancellable* cancellable;
	gchar* soundtheme;
	gchar* sound;
};

struct _ClocksUtilsBellRingRealData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ClocksUtilsBell* self;
	gboolean repeat;
	GSoundContext* _tmp0_;
	gboolean _tmp1_;
	GSoundContext* _tmp2_;
	GCancellable* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GError* e;
	GError* _vala1_e;
	GError* _tmp6_;
	const gchar* _tmp7_;
	GError* _inner_error0_;
};

static gint ClocksUtilsWallClock_private_offset;
static gpointer clocks_utils_wall_clock_parent_class = NULL;
static ClocksUtilsWallClock* clocks_utils_wall_clock_instance;
static ClocksUtilsWallClock* clocks_utils_wall_clock_instance = NULL;
static gint ClocksUtilsWeekdays_private_offset;
static gpointer clocks_utils_weekdays_parent_class = NULL;
static gchar** clocks_utils_weekdays_abbreviations;
static gint clocks_utils_weekdays_abbreviations_length1;
static gchar** clocks_utils_weekdays_abbreviations = NULL;
static gint clocks_utils_weekdays_abbreviations_length1 = 0;
static gint _clocks_utils_weekdays_abbreviations_size_ = 0;
static gint ClocksUtilsBell_private_offset;
static gpointer clocks_utils_bell_parent_class = NULL;

gint clocks_cutils_get_week_start (void);
void clocks_utils_load_css (const gchar* css,
                            gboolean required);
void clocks_utils_load_main_css (void);
void clocks_utils_load_theme_css (const gchar* theme_name);
GdkPixbuf* clocks_utils_load_image (const gchar* image);
void clocks_utils_time_to_hms (gdouble t,
                               gint* h,
                               gint* m,
                               gint* s,
                               gdouble* remainder);
GType clocks_utils_wall_clock_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksUtilsWallClock, g_object_unref)
GType clocks_utils_wall_clock_format_get_type (void) G_GNUC_CONST;
ClocksUtilsWallClock* clocks_utils_wall_clock_get_default (void);
static ClocksUtilsWallClock* clocks_utils_wall_clock_new (void);
static ClocksUtilsWallClock* clocks_utils_wall_clock_construct (GType object_type);
static void __lambda4_ (ClocksUtilsWallClock* self);
static void clocks_utils_wall_clock_update (ClocksUtilsWallClock* self);
static void ___lambda4__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void clocks_utils_wall_clock_set_timezone (ClocksUtilsWallClock* self,
                                           GTimeZone* value);
static void __lambda5_ (ClocksUtilsWallClock* self);
static void ___lambda5__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void __lambda6_ (ClocksUtilsWallClock* self);
static void clocks_utils_wall_clock_update_format (ClocksUtilsWallClock* self);
static void ___lambda6__g_settings_changed (GSettings* _sender,
                                     const gchar* key,
                                     gpointer self);
static void clocks_utils_wall_clock_set_format (ClocksUtilsWallClock* self,
                                         ClocksUtilsWallClockFormat value);
GTimeZone* clocks_utils_wall_clock_get_timezone (ClocksUtilsWallClock* self);
static void clocks_utils_wall_clock_set_date_time (ClocksUtilsWallClock* self,
                                            GDateTime* value);
gchar* clocks_utils_wall_clock_format_time (ClocksUtilsWallClock* self,
                                            GDateTime* date_time);
ClocksUtilsWallClockFormat clocks_utils_wall_clock_get_format (ClocksUtilsWallClock* self);
GDateTime* clocks_utils_wall_clock_get_date_time (ClocksUtilsWallClock* self);
static void clocks_utils_wall_clock_finalize (GObject * obj);
static void _vala_clocks_utils_wall_clock_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec);
static void _vala_clocks_utils_wall_clock_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec);
gpointer clocks_utils_weekdays_ref (gpointer instance);
void clocks_utils_weekdays_unref (gpointer instance);
GParamSpec* clocks_utils_param_spec_weekdays (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void clocks_utils_value_set_weekdays (GValue* value,
                                      gpointer v_object);
void clocks_utils_value_take_weekdays (GValue* value,
                                       gpointer v_object);
gpointer clocks_utils_value_get_weekdays (const GValue* value);
GType clocks_utils_weekdays_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksUtilsWeekdays, clocks_utils_weekdays_unref)
GType clocks_utils_weekdays_day_get_type (void) G_GNUC_CONST;
ClocksUtilsWeekdaysDay clocks_utils_weekdays_get_first_weekday (void);
gchar* clocks_utils_weekdays_plural (ClocksUtilsWeekdaysDay d);
gchar* clocks_utils_weekdays_abbreviation (ClocksUtilsWeekdaysDay d);
ClocksUtilsWeekdays* clocks_utils_weekdays_new (void);
ClocksUtilsWeekdays* clocks_utils_weekdays_construct (GType object_type);
static gboolean clocks_utils_weekdays_days_equal (ClocksUtilsWeekdays* self,
                                           gboolean* d,
                                           gint d_length1);
gboolean clocks_utils_weekdays_get (ClocksUtilsWeekdays* self,
                                    ClocksUtilsWeekdaysDay d);
void clocks_utils_weekdays_set (ClocksUtilsWeekdays* self,
                                ClocksUtilsWeekdaysDay d,
                                gboolean on);
gchar* clocks_utils_weekdays_get_label (ClocksUtilsWeekdays* self);
static void _vala_array_add3 (gchar** * array,
                       int* length,
                       int* size,
                       gchar* value);
GVariant* clocks_utils_weekdays_serialize (ClocksUtilsWeekdays* self);
ClocksUtilsWeekdays* clocks_utils_weekdays_deserialize (GVariant* days_variant);
gboolean clocks_utils_weekdays_get_empty (ClocksUtilsWeekdays* self);
static void clocks_utils_weekdays_finalize (ClocksUtilsWeekdays * obj);
GType clocks_utils_bell_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksUtilsBell, g_object_unref)
ClocksUtilsBell* clocks_utils_bell_new (const gchar* soundid);
ClocksUtilsBell* clocks_utils_bell_construct (GType object_type,
                                              const gchar* soundid);
static void clocks_utils_bell_ring_real_data_free (gpointer _data);
static void clocks_utils_bell_ring_real (ClocksUtilsBell* self,
                                  gboolean repeat,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_);
static void clocks_utils_bell_ring_real_finish (ClocksUtilsBell* self,
                                         GAsyncResult* _res_);
static gboolean clocks_utils_bell_ring_real_co (ClocksUtilsBellRingRealData* _data_);
static void clocks_utils_bell_ring_real_ready (GObject* source_object,
                                        GAsyncResult* _res_,
                                        gpointer _user_data_);
void clocks_utils_bell_ring_once (ClocksUtilsBell* self);
void clocks_utils_bell_ring (ClocksUtilsBell* self);
void clocks_utils_bell_stop (ClocksUtilsBell* self);
static void clocks_utils_bell_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const gboolean CLOCKS_UTILS_WEEKDAYS_weekdays[7] = {TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE};
static const gboolean CLOCKS_UTILS_WEEKDAYS_weekends[7] = {FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE};
static const gchar* CLOCKS_UTILS_WEEKDAYS_plurals[7] = {N_ ("Mondays"), N_ ("Tuesdays"), N_ ("Wednesdays"), N_ ("Thursdays"), N_ ("Fridays"), N_ ("Saturdays"), N_ ("Sundays")};

void
clocks_utils_load_css (const gchar* css,
                       gboolean required)
{
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp0_;
	GdkScreen* _tmp11_;
	GtkCssProvider* _tmp12_;
	GError* _inner_error0_ = NULL;
#line 24 "../src/utils.vala"
	g_return_if_fail (css != NULL);
#line 25 "../src/utils.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 25 "../src/utils.vala"
	provider = _tmp0_;
#line 346 "utils.c"
	{
		GFile* file = NULL;
		gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GFile* _tmp5_;
		GFile* _tmp6_;
		GtkCssProvider* _tmp7_;
		GFile* _tmp8_;
#line 27 "../src/utils.vala"
		_tmp1_ = g_strconcat ("resource:///org/gnome/clocks/css/", css, NULL);
#line 27 "../src/utils.vala"
		_tmp2_ = _tmp1_;
#line 27 "../src/utils.vala"
		_tmp3_ = g_strconcat (_tmp2_, ".css", NULL);
#line 27 "../src/utils.vala"
		_tmp4_ = _tmp3_;
#line 27 "../src/utils.vala"
		_tmp5_ = g_file_new_for_uri (_tmp4_);
#line 27 "../src/utils.vala"
		_tmp6_ = _tmp5_;
#line 27 "../src/utils.vala"
		_g_free0 (_tmp4_);
#line 27 "../src/utils.vala"
		_g_free0 (_tmp2_);
#line 27 "../src/utils.vala"
		file = _tmp6_;
#line 28 "../src/utils.vala"
		_tmp7_ = provider;
#line 28 "../src/utils.vala"
		_tmp8_ = file;
#line 28 "../src/utils.vala"
		gtk_css_provider_load_from_file (_tmp7_, _tmp8_, &_inner_error0_);
#line 28 "../src/utils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 28 "../src/utils.vala"
			_g_object_unref0 (file);
#line 385 "utils.c"
			goto __catch5_g_error;
		}
#line 26 "../src/utils.vala"
		_g_object_unref0 (file);
#line 390 "utils.c"
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
#line 26 "../src/utils.vala"
		e = _inner_error0_;
#line 26 "../src/utils.vala"
		_inner_error0_ = NULL;
#line 30 "../src/utils.vala"
		if (required) {
#line 402 "utils.c"
			GError* _tmp9_;
			const gchar* _tmp10_;
#line 31 "../src/utils.vala"
			_tmp9_ = e;
#line 31 "../src/utils.vala"
			_tmp10_ = _tmp9_->message;
#line 31 "../src/utils.vala"
			g_warning ("utils.vala:31: loading css: %s", _tmp10_);
#line 411 "utils.c"
		}
#line 34 "../src/utils.vala"
		_g_error_free0 (e);
#line 34 "../src/utils.vala"
		_g_object_unref0 (provider);
#line 34 "../src/utils.vala"
		return;
#line 419 "utils.c"
	}
	__finally5:
#line 26 "../src/utils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 26 "../src/utils.vala"
		_g_object_unref0 (provider);
#line 26 "../src/utils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 26 "../src/utils.vala"
		g_clear_error (&_inner_error0_);
#line 26 "../src/utils.vala"
		return;
#line 432 "utils.c"
	}
#line 37 "../src/utils.vala"
	_tmp11_ = gdk_screen_get_default ();
#line 37 "../src/utils.vala"
	_tmp12_ = provider;
#line 37 "../src/utils.vala"
	gtk_style_context_add_provider_for_screen (_tmp11_, (GtkStyleProvider*) _tmp12_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 24 "../src/utils.vala"
	_g_object_unref0 (provider);
#line 442 "utils.c"
}

void
clocks_utils_load_main_css (void)
{
#line 43 "../src/utils.vala"
	clocks_utils_load_css ("gnome-clocks", TRUE);
#line 450 "utils.c"
}

void
clocks_utils_load_theme_css (const gchar* theme_name)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
#line 46 "../src/utils.vala"
	g_return_if_fail (theme_name != NULL);
#line 47 "../src/utils.vala"
	_tmp0_ = g_utf8_strdown (theme_name, (gssize) -1);
#line 47 "../src/utils.vala"
	_tmp1_ = _tmp0_;
#line 47 "../src/utils.vala"
	_tmp2_ = g_strconcat ("gnome-clocks.", _tmp1_, NULL);
#line 47 "../src/utils.vala"
	_tmp3_ = _tmp2_;
#line 47 "../src/utils.vala"
	clocks_utils_load_css (_tmp3_, FALSE);
#line 47 "../src/utils.vala"
	_g_free0 (_tmp3_);
#line 47 "../src/utils.vala"
	_g_free0 (_tmp1_);
#line 476 "utils.c"
}

GdkPixbuf*
clocks_utils_load_image (const gchar* image)
{
	GError* _inner_error0_ = NULL;
	GdkPixbuf* result = NULL;
#line 50 "../src/utils.vala"
	g_return_val_if_fail (image != NULL, NULL);
#line 486 "utils.c"
	{
		GdkPixbuf* _tmp0_ = NULL;
		gchar* _tmp1_;
		gchar* _tmp2_;
		GdkPixbuf* _tmp3_;
		GdkPixbuf* _tmp4_;
		GdkPixbuf* _tmp5_;
#line 52 "../src/utils.vala"
		_tmp1_ = g_strconcat ("/org/gnome/clocks/images/", image, NULL);
#line 52 "../src/utils.vala"
		_tmp2_ = _tmp1_;
#line 52 "../src/utils.vala"
		_tmp3_ = gdk_pixbuf_new_from_resource (_tmp2_, &_inner_error0_);
#line 52 "../src/utils.vala"
		_tmp4_ = _tmp3_;
#line 52 "../src/utils.vala"
		_g_free0 (_tmp2_);
#line 52 "../src/utils.vala"
		_tmp0_ = _tmp4_;
#line 52 "../src/utils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 508 "utils.c"
			goto __catch6_g_error;
		}
#line 52 "../src/utils.vala"
		_tmp5_ = _tmp0_;
#line 52 "../src/utils.vala"
		_tmp0_ = NULL;
#line 52 "../src/utils.vala"
		result = _tmp5_;
#line 52 "../src/utils.vala"
		_g_object_unref0 (_tmp0_);
#line 52 "../src/utils.vala"
		return result;
#line 521 "utils.c"
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		GError* _tmp6_;
		const gchar* _tmp7_;
#line 51 "../src/utils.vala"
		e = _inner_error0_;
#line 51 "../src/utils.vala"
		_inner_error0_ = NULL;
#line 54 "../src/utils.vala"
		_tmp6_ = e;
#line 54 "../src/utils.vala"
		_tmp7_ = _tmp6_->message;
#line 54 "../src/utils.vala"
		g_warning ("utils.vala:54: loading image file: %s", _tmp7_);
#line 51 "../src/utils.vala"
		_g_error_free0 (e);
#line 541 "utils.c"
	}
	__finally6:
#line 51 "../src/utils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 51 "../src/utils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 51 "../src/utils.vala"
		g_clear_error (&_inner_error0_);
#line 51 "../src/utils.vala"
		return NULL;
#line 552 "utils.c"
	}
#line 56 "../src/utils.vala"
	result = NULL;
#line 56 "../src/utils.vala"
	return result;
#line 558 "utils.c"
}

void
clocks_utils_time_to_hms (gdouble t,
                          gint* h,
                          gint* m,
                          gint* s,
                          gdouble* remainder)
{
	gint _vala_h = 0;
	gint _vala_m = 0;
	gint _vala_s = 0;
	gdouble _vala_remainder = 0.0;
#line 60 "../src/utils.vala"
	_vala_h = ((gint) t) / 3600;
#line 61 "../src/utils.vala"
	t = fmod (t, 3600);
#line 62 "../src/utils.vala"
	_vala_m = ((gint) t) / 60;
#line 63 "../src/utils.vala"
	t = fmod (t, 60);
#line 64 "../src/utils.vala"
	_vala_s = (gint) t;
#line 65 "../src/utils.vala"
	_vala_remainder = t - _vala_s;
#line 59 "../src/utils.vala"
	if (h) {
#line 59 "../src/utils.vala"
		*h = _vala_h;
#line 588 "utils.c"
	}
#line 59 "../src/utils.vala"
	if (m) {
#line 59 "../src/utils.vala"
		*m = _vala_m;
#line 594 "utils.c"
	}
#line 59 "../src/utils.vala"
	if (s) {
#line 59 "../src/utils.vala"
		*s = _vala_s;
#line 600 "utils.c"
	}
#line 59 "../src/utils.vala"
	if (remainder) {
#line 59 "../src/utils.vala"
		*remainder = _vala_remainder;
#line 606 "utils.c"
	}
}

static inline gpointer
clocks_utils_wall_clock_get_instance_private (ClocksUtilsWallClock* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksUtilsWallClock_private_offset);
}

GType
clocks_utils_wall_clock_format_get_type (void)
{
	static volatile gsize clocks_utils_wall_clock_format_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_utils_wall_clock_format_type_id__volatile)) {
		static const GEnumValue values[] = {{CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE, "CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE", "twelve"}, {CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWENTYFOUR, "CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWENTYFOUR", "twentyfour"}, {0, NULL, NULL}};
		GType clocks_utils_wall_clock_format_type_id;
		clocks_utils_wall_clock_format_type_id = g_enum_register_static ("ClocksUtilsWallClockFormat", values);
		g_once_init_leave (&clocks_utils_wall_clock_format_type_id__volatile, clocks_utils_wall_clock_format_type_id);
	}
	return clocks_utils_wall_clock_format_type_id__volatile;
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 84 "../src/utils.vala"
	return self ? g_object_ref (self) : NULL;
#line 634 "utils.c"
}

ClocksUtilsWallClock*
clocks_utils_wall_clock_get_default (void)
{
	ClocksUtilsWallClock* _tmp0_;
	ClocksUtilsWallClock* _tmp2_;
	ClocksUtilsWallClock* _tmp3_;
	ClocksUtilsWallClock* result = NULL;
#line 81 "../src/utils.vala"
	_tmp0_ = clocks_utils_wall_clock_instance;
#line 81 "../src/utils.vala"
	if (_tmp0_ == NULL) {
#line 648 "utils.c"
		ClocksUtilsWallClock* _tmp1_;
#line 82 "../src/utils.vala"
		_tmp1_ = clocks_utils_wall_clock_new ();
#line 82 "../src/utils.vala"
		_g_object_unref0 (clocks_utils_wall_clock_instance);
#line 82 "../src/utils.vala"
		clocks_utils_wall_clock_instance = _tmp1_;
#line 656 "utils.c"
	}
#line 84 "../src/utils.vala"
	_tmp2_ = clocks_utils_wall_clock_instance;
#line 84 "../src/utils.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 84 "../src/utils.vala"
	result = _tmp3_;
#line 84 "../src/utils.vala"
	return result;
#line 666 "utils.c"
}

static void
__lambda4_ (ClocksUtilsWallClock* self)
{
#line 97 "../src/utils.vala"
	clocks_utils_wall_clock_update (self);
#line 98 "../src/utils.vala"
	g_signal_emit (self, clocks_utils_wall_clock_signals[CLOCKS_UTILS_WALL_CLOCK_TICK_SIGNAL], 0);
#line 676 "utils.c"
}

static void
___lambda4__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 96 "../src/utils.vala"
	__lambda4_ ((ClocksUtilsWallClock*) self);
#line 686 "utils.c"
}

static void
__lambda5_ (ClocksUtilsWallClock* self)
{
	GnomeWallClock* _tmp0_;
	GTimeZone* _tmp1_;
	GTimeZone* _tmp2_;
	GTimeZone* _tmp3_;
#line 104 "../src/utils.vala"
	_tmp0_ = self->priv->wc;
#line 104 "../src/utils.vala"
	g_object_get (_tmp0_, "timezone", &_tmp1_, NULL);
#line 104 "../src/utils.vala"
	_tmp2_ = _tmp1_;
#line 104 "../src/utils.vala"
	_tmp3_ = _tmp2_;
#line 104 "../src/utils.vala"
	clocks_utils_wall_clock_set_timezone (self, _tmp3_);
#line 104 "../src/utils.vala"
	_g_time_zone_unref0 (_tmp3_);
#line 708 "utils.c"
}

static void
___lambda5__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 103 "../src/utils.vala"
	__lambda5_ ((ClocksUtilsWallClock*) self);
#line 718 "utils.c"
}

static void
__lambda6_ (ClocksUtilsWallClock* self)
{
#line 110 "../src/utils.vala"
	clocks_utils_wall_clock_update_format (self);
#line 726 "utils.c"
}

static void
___lambda6__g_settings_changed (GSettings* _sender,
                                const gchar* key,
                                gpointer self)
{
#line 109 "../src/utils.vala"
	__lambda6_ ((ClocksUtilsWallClock*) self);
#line 736 "utils.c"
}

static ClocksUtilsWallClock*
clocks_utils_wall_clock_construct (GType object_type)
{
	ClocksUtilsWallClock * self = NULL;
	GnomeWallClock* _tmp0_;
	GnomeWallClock* _tmp1_;
	GnomeWallClock* _tmp2_;
	GTimeZone* _tmp3_;
	GTimeZone* _tmp4_;
	GTimeZone* _tmp5_;
	GnomeWallClock* _tmp6_;
	GSettings* _tmp7_;
	GSettings* _tmp8_;
#line 94 "../src/utils.vala"
	self = (ClocksUtilsWallClock*) g_object_new (object_type, NULL);
#line 95 "../src/utils.vala"
	_tmp0_ = gnome_wall_clock_new ();
#line 95 "../src/utils.vala"
	_g_object_unref0 (self->priv->wc);
#line 95 "../src/utils.vala"
	self->priv->wc = _tmp0_;
#line 96 "../src/utils.vala"
	_tmp1_ = self->priv->wc;
#line 96 "../src/utils.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify::clock", (GCallback) ___lambda4__g_object_notify, self, 0);
#line 102 "../src/utils.vala"
	_tmp2_ = self->priv->wc;
#line 102 "../src/utils.vala"
	g_object_get (_tmp2_, "timezone", &_tmp3_, NULL);
#line 102 "../src/utils.vala"
	_tmp4_ = _tmp3_;
#line 102 "../src/utils.vala"
	_tmp5_ = _tmp4_;
#line 102 "../src/utils.vala"
	clocks_utils_wall_clock_set_timezone (self, _tmp5_);
#line 102 "../src/utils.vala"
	_g_time_zone_unref0 (_tmp5_);
#line 103 "../src/utils.vala"
	_tmp6_ = self->priv->wc;
#line 103 "../src/utils.vala"
	g_signal_connect_object ((GObject*) _tmp6_, "notify::timezone", (GCallback) ___lambda5__g_object_notify, self, 0);
#line 108 "../src/utils.vala"
	_tmp7_ = g_settings_new ("org.gnome.desktop.interface");
#line 108 "../src/utils.vala"
	_g_object_unref0 (self->priv->settings);
#line 108 "../src/utils.vala"
	self->priv->settings = _tmp7_;
#line 109 "../src/utils.vala"
	_tmp8_ = self->priv->settings;
#line 109 "../src/utils.vala"
	g_signal_connect_object (_tmp8_, "changed::clock-format", (GCallback) ___lambda6__g_settings_changed, self, 0);
#line 112 "../src/utils.vala"
	clocks_utils_wall_clock_update_format (self);
#line 114 "../src/utils.vala"
	clocks_utils_wall_clock_update (self);
#line 94 "../src/utils.vala"
	return self;
#line 796 "utils.c"
}

static ClocksUtilsWallClock*
clocks_utils_wall_clock_new (void)
{
#line 94 "../src/utils.vala"
	return clocks_utils_wall_clock_construct (CLOCKS_UTILS_TYPE_WALL_CLOCK);
#line 804 "utils.c"
}

static void
clocks_utils_wall_clock_update_format (ClocksUtilsWallClock* self)
{
	gchar* sys_format = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	ClocksUtilsWallClockFormat _tmp2_ = 0;
	const gchar* _tmp3_;
#line 119 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 120 "../src/utils.vala"
	_tmp0_ = self->priv->settings;
#line 120 "../src/utils.vala"
	_tmp1_ = g_settings_get_string (_tmp0_, "clock-format");
#line 120 "../src/utils.vala"
	sys_format = _tmp1_;
#line 121 "../src/utils.vala"
	_tmp3_ = sys_format;
#line 121 "../src/utils.vala"
	if (g_strcmp0 (_tmp3_, "12h") == 0) {
#line 121 "../src/utils.vala"
		_tmp2_ = CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE;
#line 829 "utils.c"
	} else {
#line 121 "../src/utils.vala"
		_tmp2_ = CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWENTYFOUR;
#line 833 "utils.c"
	}
#line 121 "../src/utils.vala"
	clocks_utils_wall_clock_set_format (self, _tmp2_);
#line 119 "../src/utils.vala"
	_g_free0 (sys_format);
#line 839 "utils.c"
}

static void
clocks_utils_wall_clock_update (ClocksUtilsWallClock* self)
{
	GTimeZone* _tmp0_;
	GDateTime* _tmp1_;
	GDateTime* _tmp2_;
#line 127 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 128 "../src/utils.vala"
	_tmp0_ = self->priv->_timezone;
#line 128 "../src/utils.vala"
	_tmp1_ = g_date_time_new_now (_tmp0_);
#line 128 "../src/utils.vala"
	_tmp2_ = _tmp1_;
#line 128 "../src/utils.vala"
	clocks_utils_wall_clock_set_date_time (self, _tmp2_);
#line 128 "../src/utils.vala"
	_g_date_time_unref0 (_tmp2_);
#line 860 "utils.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1480 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1480 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1480 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1481 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1481 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 882 "utils.c"
	} else {
#line 1481 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 886 "utils.c"
	}
#line 1481 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1481 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 892 "utils.c"
	} else {
#line 1481 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 896 "utils.c"
	}
#line 1481 "glib-2.0.vapi"
	if (_tmp0_) {
#line 900 "utils.c"
		gchar* _tmp2_;
#line 1482 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1482 "glib-2.0.vapi"
		result = _tmp2_;
#line 1482 "glib-2.0.vapi"
		return result;
#line 908 "utils.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1485 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1485 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1485 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1485 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1485 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1485 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1485 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1485 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 936 "utils.c"
				goto __catch7_g_regex_error;
			}
#line 1485 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1485 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1485 "glib-2.0.vapi"
			return NULL;
#line 945 "utils.c"
		}
#line 1486 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1486 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1486 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1486 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1486 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1486 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 959 "utils.c"
				goto __catch7_g_regex_error;
			}
#line 1486 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1486 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1486 "glib-2.0.vapi"
			return NULL;
#line 968 "utils.c"
		}
#line 1486 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1486 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1486 "glib-2.0.vapi"
		result = _tmp10_;
#line 1486 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1486 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1486 "glib-2.0.vapi"
		return result;
#line 982 "utils.c"
	}
	goto __finally7;
	__catch7_g_regex_error:
	{
		GError* e = NULL;
#line 1484 "glib-2.0.vapi"
		e = _inner_error0_;
#line 1484 "glib-2.0.vapi"
		_inner_error0_ = NULL;
#line 1488 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 1484 "glib-2.0.vapi"
		_g_error_free0 (e);
#line 996 "utils.c"
	}
	__finally7:
#line 1484 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1484 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1484 "glib-2.0.vapi"
	return NULL;
#line 1005 "utils.c"
}

gchar*
clocks_utils_wall_clock_format_time (ClocksUtilsWallClock* self,
                                     GDateTime* date_time)
{
	const gchar* _tmp0_ = NULL;
	ClocksUtilsWallClockFormat _tmp1_;
	gchar* time = NULL;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	ClocksUtilsWallClockFormat _tmp5_;
	gchar* result = NULL;
#line 131 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 131 "../src/utils.vala"
	g_return_val_if_fail (date_time != NULL, NULL);
#line 132 "../src/utils.vala"
	_tmp1_ = self->priv->_format;
#line 132 "../src/utils.vala"
	if (_tmp1_ == CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE) {
#line 132 "../src/utils.vala"
		_tmp0_ = "%I:%M %p";
#line 1030 "utils.c"
	} else {
#line 132 "../src/utils.vala"
		_tmp0_ = "%H:%M";
#line 1034 "utils.c"
	}
#line 132 "../src/utils.vala"
	_tmp2_ = g_date_time_format (date_time, _tmp0_);
#line 132 "../src/utils.vala"
	time = _tmp2_;
#line 137 "../src/utils.vala"
	_tmp3_ = time;
#line 137 "../src/utils.vala"
	_tmp4_ = string_replace (_tmp3_, ":", "\xE2\x80\x8E\xE2\x88\xB6");
#line 137 "../src/utils.vala"
	_g_free0 (time);
#line 137 "../src/utils.vala"
	time = _tmp4_;
#line 139 "../src/utils.vala"
	_tmp5_ = self->priv->_format;
#line 139 "../src/utils.vala"
	if (_tmp5_ == CLOCKS_UTILS_WALL_CLOCK_FORMAT_TWELVE) {
#line 1052 "utils.c"
		const gchar* _tmp6_;
		gchar* _tmp7_;
#line 140 "../src/utils.vala"
		_tmp6_ = time;
#line 140 "../src/utils.vala"
		_tmp7_ = string_replace (_tmp6_, " ", "\xE2\x80\x89");
#line 140 "../src/utils.vala"
		_g_free0 (time);
#line 140 "../src/utils.vala"
		time = _tmp7_;
#line 1063 "utils.c"
	}
#line 143 "../src/utils.vala"
	result = time;
#line 143 "../src/utils.vala"
	return result;
#line 1069 "utils.c"
}

GDateTime*
clocks_utils_wall_clock_get_date_time (ClocksUtilsWallClock* self)
{
	GDateTime* result;
	GDateTime* _tmp0_;
#line 87 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 87 "../src/utils.vala"
	_tmp0_ = self->priv->_date_time;
#line 87 "../src/utils.vala"
	result = _tmp0_;
#line 87 "../src/utils.vala"
	return result;
#line 1085 "utils.c"
}

static gpointer
_g_date_time_ref0 (gpointer self)
{
#line 87 "../src/utils.vala"
	return self ? g_date_time_ref (self) : NULL;
#line 1093 "utils.c"
}

static void
clocks_utils_wall_clock_set_date_time (ClocksUtilsWallClock* self,
                                       GDateTime* value)
{
#line 87 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 87 "../src/utils.vala"
	if (clocks_utils_wall_clock_get_date_time (self) != value) {
#line 1104 "utils.c"
		GDateTime* _tmp0_;
#line 87 "../src/utils.vala"
		_tmp0_ = _g_date_time_ref0 (value);
#line 87 "../src/utils.vala"
		_g_date_time_unref0 (self->priv->_date_time);
#line 87 "../src/utils.vala"
		self->priv->_date_time = _tmp0_;
#line 87 "../src/utils.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY]);
#line 1114 "utils.c"
	}
}

GTimeZone*
clocks_utils_wall_clock_get_timezone (ClocksUtilsWallClock* self)
{
	GTimeZone* result;
	GTimeZone* _tmp0_;
#line 88 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 88 "../src/utils.vala"
	_tmp0_ = self->priv->_timezone;
#line 88 "../src/utils.vala"
	result = _tmp0_;
#line 88 "../src/utils.vala"
	return result;
#line 1131 "utils.c"
}

static gpointer
_g_time_zone_ref0 (gpointer self)
{
#line 88 "../src/utils.vala"
	return self ? g_time_zone_ref (self) : NULL;
#line 1139 "utils.c"
}

static void
clocks_utils_wall_clock_set_timezone (ClocksUtilsWallClock* self,
                                      GTimeZone* value)
{
#line 88 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 88 "../src/utils.vala"
	if (clocks_utils_wall_clock_get_timezone (self) != value) {
#line 1150 "utils.c"
		GTimeZone* _tmp0_;
#line 88 "../src/utils.vala"
		_tmp0_ = _g_time_zone_ref0 (value);
#line 88 "../src/utils.vala"
		_g_time_zone_unref0 (self->priv->_timezone);
#line 88 "../src/utils.vala"
		self->priv->_timezone = _tmp0_;
#line 88 "../src/utils.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY]);
#line 1160 "utils.c"
	}
}

ClocksUtilsWallClockFormat
clocks_utils_wall_clock_get_format (ClocksUtilsWallClock* self)
{
	ClocksUtilsWallClockFormat result;
	ClocksUtilsWallClockFormat _tmp0_;
#line 89 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 89 "../src/utils.vala"
	_tmp0_ = self->priv->_format;
#line 89 "../src/utils.vala"
	result = _tmp0_;
#line 89 "../src/utils.vala"
	return result;
#line 1177 "utils.c"
}

static void
clocks_utils_wall_clock_set_format (ClocksUtilsWallClock* self,
                                    ClocksUtilsWallClockFormat value)
{
#line 89 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 89 "../src/utils.vala"
	if (clocks_utils_wall_clock_get_format (self) != value) {
#line 89 "../src/utils.vala"
		self->priv->_format = value;
#line 89 "../src/utils.vala"
		g_object_notify_by_pspec ((GObject *) self, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY]);
#line 1192 "utils.c"
	}
}

static void
clocks_utils_wall_clock_class_init (ClocksUtilsWallClockClass * klass,
                                    gpointer klass_data)
{
#line 72 "../src/utils.vala"
	clocks_utils_wall_clock_parent_class = g_type_class_peek_parent (klass);
#line 72 "../src/utils.vala"
	g_type_class_adjust_private_offset (klass, &ClocksUtilsWallClock_private_offset);
#line 72 "../src/utils.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_clocks_utils_wall_clock_get_property;
#line 72 "../src/utils.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_clocks_utils_wall_clock_set_property;
#line 72 "../src/utils.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_utils_wall_clock_finalize;
#line 72 "../src/utils.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY] = g_param_spec_boxed ("date-time", "date-time", "date-time", G_TYPE_DATE_TIME, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 72 "../src/utils.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY] = g_param_spec_pointer ("timezone", "timezone", "timezone", G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 72 "../src/utils.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY, clocks_utils_wall_clock_properties[CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY] = g_param_spec_enum ("format", "format", "format", CLOCKS_UTILS_WALL_CLOCK_TYPE_FORMAT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 72 "../src/utils.vala"
	clocks_utils_wall_clock_signals[CLOCKS_UTILS_WALL_CLOCK_TICK_SIGNAL] = g_signal_new ("tick", CLOCKS_UTILS_TYPE_WALL_CLOCK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1218 "utils.c"
}

static void
clocks_utils_wall_clock_instance_init (ClocksUtilsWallClock * self,
                                       gpointer klass)
{
#line 72 "../src/utils.vala"
	self->priv = clocks_utils_wall_clock_get_instance_private (self);
#line 1227 "utils.c"
}

static void
clocks_utils_wall_clock_finalize (GObject * obj)
{
	ClocksUtilsWallClock * self;
#line 72 "../src/utils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClock);
#line 87 "../src/utils.vala"
	_g_date_time_unref0 (self->priv->_date_time);
#line 88 "../src/utils.vala"
	_g_time_zone_unref0 (self->priv->_timezone);
#line 91 "../src/utils.vala"
	_g_object_unref0 (self->priv->settings);
#line 92 "../src/utils.vala"
	_g_object_unref0 (self->priv->wc);
#line 72 "../src/utils.vala"
	G_OBJECT_CLASS (clocks_utils_wall_clock_parent_class)->finalize (obj);
#line 1246 "utils.c"
}

GType
clocks_utils_wall_clock_get_type (void)
{
	static volatile gsize clocks_utils_wall_clock_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_utils_wall_clock_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksUtilsWallClockClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_utils_wall_clock_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksUtilsWallClock), 0, (GInstanceInitFunc) clocks_utils_wall_clock_instance_init, NULL };
		GType clocks_utils_wall_clock_type_id;
		clocks_utils_wall_clock_type_id = g_type_register_static (G_TYPE_OBJECT, "ClocksUtilsWallClock", &g_define_type_info, 0);
		ClocksUtilsWallClock_private_offset = g_type_add_instance_private (clocks_utils_wall_clock_type_id, sizeof (ClocksUtilsWallClockPrivate));
		g_once_init_leave (&clocks_utils_wall_clock_type_id__volatile, clocks_utils_wall_clock_type_id);
	}
	return clocks_utils_wall_clock_type_id__volatile;
}

static void
_vala_clocks_utils_wall_clock_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec)
{
	ClocksUtilsWallClock * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClock);
#line 72 "../src/utils.vala"
	switch (property_id) {
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY:
#line 72 "../src/utils.vala"
		g_value_set_boxed (value, clocks_utils_wall_clock_get_date_time (self));
#line 72 "../src/utils.vala"
		break;
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY:
#line 72 "../src/utils.vala"
		g_value_set_pointer (value, clocks_utils_wall_clock_get_timezone (self));
#line 72 "../src/utils.vala"
		break;
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY:
#line 72 "../src/utils.vala"
		g_value_set_enum (value, clocks_utils_wall_clock_get_format (self));
#line 72 "../src/utils.vala"
		break;
#line 1291 "utils.c"
		default:
#line 72 "../src/utils.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 72 "../src/utils.vala"
		break;
#line 1297 "utils.c"
	}
}

static void
_vala_clocks_utils_wall_clock_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec)
{
	ClocksUtilsWallClock * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CLOCKS_UTILS_TYPE_WALL_CLOCK, ClocksUtilsWallClock);
#line 72 "../src/utils.vala"
	switch (property_id) {
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_DATE_TIME_PROPERTY:
#line 72 "../src/utils.vala"
		clocks_utils_wall_clock_set_date_time (self, g_value_get_boxed (value));
#line 72 "../src/utils.vala"
		break;
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_TIMEZONE_PROPERTY:
#line 72 "../src/utils.vala"
		clocks_utils_wall_clock_set_timezone (self, g_value_get_pointer (value));
#line 72 "../src/utils.vala"
		break;
#line 72 "../src/utils.vala"
		case CLOCKS_UTILS_WALL_CLOCK_FORMAT_PROPERTY:
#line 72 "../src/utils.vala"
		clocks_utils_wall_clock_set_format (self, g_value_get_enum (value));
#line 72 "../src/utils.vala"
		break;
#line 1329 "utils.c"
		default:
#line 72 "../src/utils.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 72 "../src/utils.vala"
		break;
#line 1335 "utils.c"
	}
}

static inline gpointer
clocks_utils_weekdays_get_instance_private (ClocksUtilsWeekdays* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksUtilsWeekdays_private_offset);
}

GType
clocks_utils_weekdays_day_get_type (void)
{
	static volatile gsize clocks_utils_weekdays_day_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_utils_weekdays_day_type_id__volatile)) {
		static const GEnumValue values[] = {{CLOCKS_UTILS_WEEKDAYS_DAY_MON, "CLOCKS_UTILS_WEEKDAYS_DAY_MON", "mon"}, {CLOCKS_UTILS_WEEKDAYS_DAY_TUE, "CLOCKS_UTILS_WEEKDAYS_DAY_TUE", "tue"}, {CLOCKS_UTILS_WEEKDAYS_DAY_WED, "CLOCKS_UTILS_WEEKDAYS_DAY_WED", "wed"}, {CLOCKS_UTILS_WEEKDAYS_DAY_THU, "CLOCKS_UTILS_WEEKDAYS_DAY_THU", "thu"}, {CLOCKS_UTILS_WEEKDAYS_DAY_FRI, "CLOCKS_UTILS_WEEKDAYS_DAY_FRI", "fri"}, {CLOCKS_UTILS_WEEKDAYS_DAY_SAT, "CLOCKS_UTILS_WEEKDAYS_DAY_SAT", "sat"}, {CLOCKS_UTILS_WEEKDAYS_DAY_SUN, "CLOCKS_UTILS_WEEKDAYS_DAY_SUN", "sun"}, {0, NULL, NULL}};
		GType clocks_utils_weekdays_day_type_id;
		clocks_utils_weekdays_day_type_id = g_enum_register_static ("ClocksUtilsWeekdaysDay", values);
		g_once_init_leave (&clocks_utils_weekdays_day_type_id__volatile, clocks_utils_weekdays_day_type_id);
	}
	return clocks_utils_weekdays_day_type_id__volatile;
}

ClocksUtilsWeekdaysDay
clocks_utils_weekdays_get_first_weekday (void)
{
	gint d = 0;
	ClocksUtilsWeekdaysDay result = 0;
#line 179 "../src/utils.vala"
	d = clocks_cutils_get_week_start ();
#line 180 "../src/utils.vala"
	result = (ClocksUtilsWeekdaysDay) ((d + 6) % 7);
#line 180 "../src/utils.vala"
	return result;
#line 1369 "utils.c"
}

gchar*
clocks_utils_weekdays_plural (ClocksUtilsWeekdaysDay d)
{
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* result = NULL;
#line 184 "../src/utils.vala"
	if (d >= 0) {
#line 184 "../src/utils.vala"
		_tmp0_ = d < 7;
#line 1383 "utils.c"
	} else {
#line 184 "../src/utils.vala"
		_tmp0_ = FALSE;
#line 1387 "utils.c"
	}
#line 184 "../src/utils.vala"
	_vala_assert (_tmp0_, "d >= 0 && d < 7");
#line 185 "../src/utils.vala"
	_tmp1_ = CLOCKS_UTILS_WEEKDAYS_plurals[d];
#line 185 "../src/utils.vala"
	_tmp2_ = g_strdup (_ (_tmp1_));
#line 185 "../src/utils.vala"
	result = _tmp2_;
#line 185 "../src/utils.vala"
	return result;
#line 1399 "utils.c"
}

gchar*
clocks_utils_weekdays_abbreviation (ClocksUtilsWeekdaysDay d)
{
	gboolean _tmp0_ = FALSE;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** _tmp24_;
	gint _tmp24__length1;
	const gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* result = NULL;
#line 189 "../src/utils.vala"
	if (d >= 0) {
#line 189 "../src/utils.vala"
		_tmp0_ = d < 7;
#line 1417 "utils.c"
	} else {
#line 189 "../src/utils.vala"
		_tmp0_ = FALSE;
#line 1421 "utils.c"
	}
#line 189 "../src/utils.vala"
	_vala_assert (_tmp0_, "d >= 0 && d < 7");
#line 193 "../src/utils.vala"
	_tmp1_ = clocks_utils_weekdays_abbreviations;
#line 193 "../src/utils.vala"
	_tmp1__length1 = clocks_utils_weekdays_abbreviations_length1;
#line 193 "../src/utils.vala"
	if (_tmp1_ == NULL) {
#line 1431 "utils.c"
		GDateTime* _tmp2_;
		GDateTime* _tmp3_;
		gchar* _tmp4_;
		GDateTime* _tmp5_;
		GDateTime* _tmp6_;
		gchar* _tmp7_;
		GDateTime* _tmp8_;
		GDateTime* _tmp9_;
		gchar* _tmp10_;
		GDateTime* _tmp11_;
		GDateTime* _tmp12_;
		gchar* _tmp13_;
		GDateTime* _tmp14_;
		GDateTime* _tmp15_;
		gchar* _tmp16_;
		GDateTime* _tmp17_;
		GDateTime* _tmp18_;
		gchar* _tmp19_;
		GDateTime* _tmp20_;
		GDateTime* _tmp21_;
		gchar* _tmp22_;
		gchar** _tmp23_;
#line 194 "../src/utils.vala"
		_tmp2_ = g_date_time_new_utc (1, 1, 1, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp3_ = _tmp2_;
#line 194 "../src/utils.vala"
		_tmp4_ = g_date_time_format (_tmp3_, "%a");
#line 194 "../src/utils.vala"
		_tmp5_ = g_date_time_new_utc (1, 1, 2, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp6_ = _tmp5_;
#line 194 "../src/utils.vala"
		_tmp7_ = g_date_time_format (_tmp6_, "%a");
#line 194 "../src/utils.vala"
		_tmp8_ = g_date_time_new_utc (1, 1, 3, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp9_ = _tmp8_;
#line 194 "../src/utils.vala"
		_tmp10_ = g_date_time_format (_tmp9_, "%a");
#line 194 "../src/utils.vala"
		_tmp11_ = g_date_time_new_utc (1, 1, 4, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp12_ = _tmp11_;
#line 194 "../src/utils.vala"
		_tmp13_ = g_date_time_format (_tmp12_, "%a");
#line 194 "../src/utils.vala"
		_tmp14_ = g_date_time_new_utc (1, 1, 5, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp15_ = _tmp14_;
#line 194 "../src/utils.vala"
		_tmp16_ = g_date_time_format (_tmp15_, "%a");
#line 194 "../src/utils.vala"
		_tmp17_ = g_date_time_new_utc (1, 1, 6, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp18_ = _tmp17_;
#line 194 "../src/utils.vala"
		_tmp19_ = g_date_time_format (_tmp18_, "%a");
#line 194 "../src/utils.vala"
		_tmp20_ = g_date_time_new_utc (1, 1, 7, 0, 0, (gdouble) 0);
#line 194 "../src/utils.vala"
		_tmp21_ = _tmp20_;
#line 194 "../src/utils.vala"
		_tmp22_ = g_date_time_format (_tmp21_, "%a");
#line 194 "../src/utils.vala"
		_tmp23_ = g_new0 (gchar*, 7 + 1);
#line 194 "../src/utils.vala"
		_tmp23_[0] = _tmp4_;
#line 194 "../src/utils.vala"
		_tmp23_[1] = _tmp7_;
#line 194 "../src/utils.vala"
		_tmp23_[2] = _tmp10_;
#line 194 "../src/utils.vala"
		_tmp23_[3] = _tmp13_;
#line 194 "../src/utils.vala"
		_tmp23_[4] = _tmp16_;
#line 194 "../src/utils.vala"
		_tmp23_[5] = _tmp19_;
#line 194 "../src/utils.vala"
		_tmp23_[6] = _tmp22_;
#line 194 "../src/utils.vala"
		clocks_utils_weekdays_abbreviations = (_vala_array_free (clocks_utils_weekdays_abbreviations, clocks_utils_weekdays_abbreviations_length1, (GDestroyNotify) g_free), NULL);
#line 194 "../src/utils.vala"
		clocks_utils_weekdays_abbreviations = _tmp23_;
#line 194 "../src/utils.vala"
		clocks_utils_weekdays_abbreviations_length1 = 7;
#line 194 "../src/utils.vala"
		_clocks_utils_weekdays_abbreviations_size_ = clocks_utils_weekdays_abbreviations_length1;
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp21_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp18_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp15_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp12_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp9_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp6_);
#line 194 "../src/utils.vala"
		_g_date_time_unref0 (_tmp3_);
#line 1534 "utils.c"
	}
#line 204 "../src/utils.vala"
	_tmp24_ = clocks_utils_weekdays_abbreviations;
#line 204 "../src/utils.vala"
	_tmp24__length1 = clocks_utils_weekdays_abbreviations_length1;
#line 204 "../src/utils.vala"
	_tmp25_ = _tmp24_[d];
#line 204 "../src/utils.vala"
	_tmp26_ = g_strdup (_tmp25_);
#line 204 "../src/utils.vala"
	result = _tmp26_;
#line 204 "../src/utils.vala"
	return result;
#line 1548 "utils.c"
}

ClocksUtilsWeekdays*
clocks_utils_weekdays_construct (GType object_type)
{
	ClocksUtilsWeekdays* self = NULL;
#line 211 "../src/utils.vala"
	self = (ClocksUtilsWeekdays*) g_type_create_instance (object_type);
#line 211 "../src/utils.vala"
	return self;
#line 1559 "utils.c"
}

ClocksUtilsWeekdays*
clocks_utils_weekdays_new (void)
{
#line 211 "../src/utils.vala"
	return clocks_utils_weekdays_construct (CLOCKS_UTILS_TYPE_WEEKDAYS);
#line 1567 "utils.c"
}

static gboolean
clocks_utils_weekdays_days_equal (ClocksUtilsWeekdays* self,
                                  gboolean* d,
                                  gint d_length1)
{
	gboolean* _tmp0_;
	gint _tmp0__length1;
	gboolean* _tmp1_;
	gint _tmp1__length1;
	gboolean result = FALSE;
#line 220 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 221 "../src/utils.vala"
	_vala_assert (d_length1 == 7, "d.length == 7");
#line 222 "../src/utils.vala"
	_tmp0_ = self->priv->days;
#line 222 "../src/utils.vala"
	_tmp0__length1 = self->priv->days_length1;
#line 222 "../src/utils.vala"
	_tmp1_ = self->priv->days;
#line 222 "../src/utils.vala"
	_tmp1__length1 = self->priv->days_length1;
#line 222 "../src/utils.vala"
	result = memcmp (d, _tmp0_, (gsize) (_tmp1__length1 * sizeof (gboolean))) == 0;
#line 222 "../src/utils.vala"
	return result;
#line 1596 "utils.c"
}

gboolean
clocks_utils_weekdays_get (ClocksUtilsWeekdays* self,
                           ClocksUtilsWeekdaysDay d)
{
	gboolean _tmp0_ = FALSE;
	gboolean* _tmp1_;
	gint _tmp1__length1;
	gboolean _tmp2_;
	gboolean result = FALSE;
#line 225 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 226 "../src/utils.vala"
	if (d >= 0) {
#line 226 "../src/utils.vala"
		_tmp0_ = d < 7;
#line 1614 "utils.c"
	} else {
#line 226 "../src/utils.vala"
		_tmp0_ = FALSE;
#line 1618 "utils.c"
	}
#line 226 "../src/utils.vala"
	_vala_assert (_tmp0_, "d >= 0 && d < 7");
#line 227 "../src/utils.vala"
	_tmp1_ = self->priv->days;
#line 227 "../src/utils.vala"
	_tmp1__length1 = self->priv->days_length1;
#line 227 "../src/utils.vala"
	_tmp2_ = _tmp1_[d];
#line 227 "../src/utils.vala"
	result = _tmp2_;
#line 227 "../src/utils.vala"
	return result;
#line 1632 "utils.c"
}

void
clocks_utils_weekdays_set (ClocksUtilsWeekdays* self,
                           ClocksUtilsWeekdaysDay d,
                           gboolean on)
{
	gboolean _tmp0_ = FALSE;
	gboolean* _tmp1_;
	gint _tmp1__length1;
#line 230 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 231 "../src/utils.vala"
	if (d >= 0) {
#line 231 "../src/utils.vala"
		_tmp0_ = d < 7;
#line 1649 "utils.c"
	} else {
#line 231 "../src/utils.vala"
		_tmp0_ = FALSE;
#line 1653 "utils.c"
	}
#line 231 "../src/utils.vala"
	_vala_assert (_tmp0_, "d >= 0 && d < 7");
#line 232 "../src/utils.vala"
	_tmp1_ = self->priv->days;
#line 232 "../src/utils.vala"
	_tmp1__length1 = self->priv->days_length1;
#line 232 "../src/utils.vala"
	_tmp1_[d] = on;
#line 1663 "utils.c"
}

static void
_vala_array_add3 (gchar** * array,
                  int* length,
                  int* size,
                  gchar* value)
{
#line 263 "../src/utils.vala"
	if ((*length) == (*size)) {
#line 263 "../src/utils.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 263 "../src/utils.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 1678 "utils.c"
	}
#line 263 "../src/utils.vala"
	(*array)[(*length)++] = value;
#line 263 "../src/utils.vala"
	(*array)[*length] = NULL;
#line 1684 "utils.c"
}

static gchar*
_vala_g_strjoinv (const gchar* separator,
                  gchar** str_array,
                  gint str_array_length1)
{
	gboolean _tmp0_ = FALSE;
	gchar* result = NULL;
#line 1148 "glib-2.0.vapi"
	if (separator == NULL) {
#line 1149 "glib-2.0.vapi"
		separator = "";
#line 1698 "utils.c"
	}
#line 1151 "glib-2.0.vapi"
	if (str_array != NULL) {
#line 1702 "utils.c"
		gboolean _tmp1_ = FALSE;
#line 1151 "glib-2.0.vapi"
		if (str_array_length1 > 0) {
#line 1151 "glib-2.0.vapi"
			_tmp1_ = TRUE;
#line 1708 "utils.c"
		} else {
			gboolean _tmp2_ = FALSE;
#line 1151 "glib-2.0.vapi"
			if (str_array_length1 == -1) {
#line 1713 "utils.c"
				const gchar* _tmp3_;
#line 1151 "glib-2.0.vapi"
				_tmp3_ = str_array[0];
#line 1151 "glib-2.0.vapi"
				_tmp2_ = _tmp3_ != NULL;
#line 1719 "utils.c"
			} else {
#line 1151 "glib-2.0.vapi"
				_tmp2_ = FALSE;
#line 1723 "utils.c"
			}
#line 1151 "glib-2.0.vapi"
			_tmp1_ = _tmp2_;
#line 1727 "utils.c"
		}
#line 1151 "glib-2.0.vapi"
		_tmp0_ = _tmp1_;
#line 1731 "utils.c"
	} else {
#line 1151 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 1735 "utils.c"
	}
#line 1151 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1739 "utils.c"
		gint i = 0;
		gsize len = 0UL;
		gint _tmp16_;
		gint _tmp17_;
		const gchar* res = NULL;
		void* _tmp18_;
		void* ptr = NULL;
		const gchar* _tmp19_;
		const gchar* _tmp20_;
		void* _tmp21_;
		const gchar* _tmp31_;
#line 1153 "glib-2.0.vapi"
		len = (gsize) 1;
#line 1753 "utils.c"
		{
			gboolean _tmp4_ = FALSE;
#line 1154 "glib-2.0.vapi"
			i = 0;
#line 1154 "glib-2.0.vapi"
			_tmp4_ = TRUE;
#line 1154 "glib-2.0.vapi"
			while (TRUE) {
#line 1762 "utils.c"
				gboolean _tmp6_ = FALSE;
				gboolean _tmp7_ = FALSE;
				gint _tmp10_ = 0;
				const gchar* _tmp11_;
#line 1154 "glib-2.0.vapi"
				if (!_tmp4_) {
#line 1769 "utils.c"
					gint _tmp5_;
#line 1154 "glib-2.0.vapi"
					_tmp5_ = i;
#line 1154 "glib-2.0.vapi"
					i = _tmp5_ + 1;
#line 1775 "utils.c"
				}
#line 1154 "glib-2.0.vapi"
				_tmp4_ = FALSE;
#line 1154 "glib-2.0.vapi"
				if (str_array_length1 != -1) {
#line 1154 "glib-2.0.vapi"
					_tmp7_ = i < str_array_length1;
#line 1783 "utils.c"
				} else {
#line 1154 "glib-2.0.vapi"
					_tmp7_ = FALSE;
#line 1787 "utils.c"
				}
#line 1154 "glib-2.0.vapi"
				if (_tmp7_) {
#line 1154 "glib-2.0.vapi"
					_tmp6_ = TRUE;
#line 1793 "utils.c"
				} else {
					gboolean _tmp8_ = FALSE;
#line 1154 "glib-2.0.vapi"
					if (str_array_length1 == -1) {
#line 1798 "utils.c"
						const gchar* _tmp9_;
#line 1154 "glib-2.0.vapi"
						_tmp9_ = str_array[i];
#line 1154 "glib-2.0.vapi"
						_tmp8_ = _tmp9_ != NULL;
#line 1804 "utils.c"
					} else {
#line 1154 "glib-2.0.vapi"
						_tmp8_ = FALSE;
#line 1808 "utils.c"
					}
#line 1154 "glib-2.0.vapi"
					_tmp6_ = _tmp8_;
#line 1812 "utils.c"
				}
#line 1154 "glib-2.0.vapi"
				if (!_tmp6_) {
#line 1154 "glib-2.0.vapi"
					break;
#line 1818 "utils.c"
				}
#line 1155 "glib-2.0.vapi"
				_tmp11_ = str_array[i];
#line 1155 "glib-2.0.vapi"
				if (_tmp11_ != NULL) {
#line 1824 "utils.c"
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
#line 1155 "glib-2.0.vapi"
					_tmp12_ = str_array[i];
#line 1155 "glib-2.0.vapi"
					_tmp13_ = strlen ((const gchar*) _tmp12_);
#line 1155 "glib-2.0.vapi"
					_tmp14_ = _tmp13_;
#line 1155 "glib-2.0.vapi"
					_tmp10_ = _tmp14_;
#line 1836 "utils.c"
				} else {
#line 1155 "glib-2.0.vapi"
					_tmp10_ = 0;
#line 1840 "utils.c"
				}
#line 1155 "glib-2.0.vapi"
				len += (gsize) _tmp10_;
#line 1844 "utils.c"
			}
		}
#line 1157 "glib-2.0.vapi"
		if (i == 0) {
#line 1849 "utils.c"
			gchar* _tmp15_;
#line 1158 "glib-2.0.vapi"
			_tmp15_ = g_strdup ("");
#line 1158 "glib-2.0.vapi"
			result = _tmp15_;
#line 1158 "glib-2.0.vapi"
			return result;
#line 1857 "utils.c"
		}
#line 1160 "glib-2.0.vapi"
		str_array_length1 = i;
#line 1161 "glib-2.0.vapi"
		_tmp16_ = strlen ((const gchar*) separator);
#line 1161 "glib-2.0.vapi"
		_tmp17_ = _tmp16_;
#line 1161 "glib-2.0.vapi"
		len += (gsize) (_tmp17_ * (i - 1));
#line 1163 "glib-2.0.vapi"
		_tmp18_ = g_malloc (len);
#line 1163 "glib-2.0.vapi"
		res = _tmp18_;
#line 1164 "glib-2.0.vapi"
		_tmp19_ = res;
#line 1164 "glib-2.0.vapi"
		_tmp20_ = str_array[0];
#line 1164 "glib-2.0.vapi"
		_tmp21_ = g_stpcpy ((void*) _tmp19_, (const gchar*) _tmp20_);
#line 1164 "glib-2.0.vapi"
		ptr = _tmp21_;
#line 1879 "utils.c"
		{
			gboolean _tmp22_ = FALSE;
#line 1165 "glib-2.0.vapi"
			i = 1;
#line 1165 "glib-2.0.vapi"
			_tmp22_ = TRUE;
#line 1165 "glib-2.0.vapi"
			while (TRUE) {
#line 1888 "utils.c"
				void* _tmp24_;
				void* _tmp25_;
				const gchar* _tmp26_ = NULL;
				const gchar* _tmp27_;
				void* _tmp29_;
				void* _tmp30_;
#line 1165 "glib-2.0.vapi"
				if (!_tmp22_) {
#line 1897 "utils.c"
					gint _tmp23_;
#line 1165 "glib-2.0.vapi"
					_tmp23_ = i;
#line 1165 "glib-2.0.vapi"
					i = _tmp23_ + 1;
#line 1903 "utils.c"
				}
#line 1165 "glib-2.0.vapi"
				_tmp22_ = FALSE;
#line 1165 "glib-2.0.vapi"
				if (!(i < str_array_length1)) {
#line 1165 "glib-2.0.vapi"
					break;
#line 1911 "utils.c"
				}
#line 1166 "glib-2.0.vapi"
				_tmp24_ = ptr;
#line 1166 "glib-2.0.vapi"
				_tmp25_ = g_stpcpy (_tmp24_, (const gchar*) separator);
#line 1166 "glib-2.0.vapi"
				ptr = _tmp25_;
#line 1167 "glib-2.0.vapi"
				_tmp27_ = str_array[i];
#line 1167 "glib-2.0.vapi"
				if (_tmp27_ != NULL) {
#line 1923 "utils.c"
					const gchar* _tmp28_;
#line 1167 "glib-2.0.vapi"
					_tmp28_ = str_array[i];
#line 1167 "glib-2.0.vapi"
					_tmp26_ = (const gchar*) _tmp28_;
#line 1929 "utils.c"
				} else {
#line 1167 "glib-2.0.vapi"
					_tmp26_ = "";
#line 1933 "utils.c"
				}
#line 1167 "glib-2.0.vapi"
				_tmp29_ = ptr;
#line 1167 "glib-2.0.vapi"
				_tmp30_ = g_stpcpy (_tmp29_, _tmp26_);
#line 1167 "glib-2.0.vapi"
				ptr = _tmp30_;
#line 1941 "utils.c"
			}
		}
#line 1170 "glib-2.0.vapi"
		_tmp31_ = res;
#line 1170 "glib-2.0.vapi"
		res = NULL;
#line 1170 "glib-2.0.vapi"
		result = (gchar*) _tmp31_;
#line 1170 "glib-2.0.vapi"
		return result;
#line 1952 "utils.c"
	} else {
		gchar* _tmp32_;
#line 1172 "glib-2.0.vapi"
		_tmp32_ = g_strdup ("");
#line 1172 "glib-2.0.vapi"
		result = _tmp32_;
#line 1172 "glib-2.0.vapi"
		return result;
#line 1961 "utils.c"
	}
}

gchar*
clocks_utils_weekdays_get_label (ClocksUtilsWeekdays* self)
{
	gchar* r = NULL;
	gint n = 0;
	gint first = 0;
	gchar* result = NULL;
#line 235 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 236 "../src/utils.vala"
	r = NULL;
#line 237 "../src/utils.vala"
	n = 0;
#line 238 "../src/utils.vala"
	first = -1;
#line 1980 "utils.c"
	{
		gint i = 0;
#line 239 "../src/utils.vala"
		i = 0;
#line 1985 "utils.c"
		{
			gboolean _tmp0_ = FALSE;
#line 239 "../src/utils.vala"
			_tmp0_ = TRUE;
#line 239 "../src/utils.vala"
			while (TRUE) {
#line 239 "../src/utils.vala"
				if (!_tmp0_) {
#line 1994 "utils.c"
					gint _tmp1_;
#line 239 "../src/utils.vala"
					_tmp1_ = i;
#line 239 "../src/utils.vala"
					i = _tmp1_ + 1;
#line 2000 "utils.c"
				}
#line 239 "../src/utils.vala"
				_tmp0_ = FALSE;
#line 239 "../src/utils.vala"
				if (!(i < 7)) {
#line 239 "../src/utils.vala"
					break;
#line 2008 "utils.c"
				}
#line 240 "../src/utils.vala"
				if (clocks_utils_weekdays_get (self, (ClocksUtilsWeekdaysDay) i)) {
#line 2012 "utils.c"
					gint _tmp2_;
#line 241 "../src/utils.vala"
					if (first < 0) {
#line 242 "../src/utils.vala"
						first = i;
#line 2018 "utils.c"
					}
#line 244 "../src/utils.vala"
					_tmp2_ = n;
#line 244 "../src/utils.vala"
					n = _tmp2_ + 1;
#line 2024 "utils.c"
				}
			}
		}
	}
#line 248 "../src/utils.vala"
	if (n == 0) {
#line 2031 "utils.c"
		gchar* _tmp3_;
#line 249 "../src/utils.vala"
		_tmp3_ = g_strdup ("");
#line 249 "../src/utils.vala"
		_g_free0 (r);
#line 249 "../src/utils.vala"
		r = _tmp3_;
#line 2039 "utils.c"
	} else {
#line 250 "../src/utils.vala"
		if (n == 1) {
#line 2043 "utils.c"
			gchar* _tmp4_;
#line 251 "../src/utils.vala"
			_tmp4_ = clocks_utils_weekdays_plural ((ClocksUtilsWeekdaysDay) first);
#line 251 "../src/utils.vala"
			_g_free0 (r);
#line 251 "../src/utils.vala"
			r = _tmp4_;
#line 2051 "utils.c"
		} else {
#line 252 "../src/utils.vala"
			if (n == 7) {
#line 2055 "utils.c"
				gchar* _tmp5_;
#line 253 "../src/utils.vala"
				_tmp5_ = g_strdup (_ ("Every Day"));
#line 253 "../src/utils.vala"
				_g_free0 (r);
#line 253 "../src/utils.vala"
				r = _tmp5_;
#line 2063 "utils.c"
			} else {
#line 254 "../src/utils.vala"
				if (clocks_utils_weekdays_days_equal (self, CLOCKS_UTILS_WEEKDAYS_weekdays, (gint) G_N_ELEMENTS (CLOCKS_UTILS_WEEKDAYS_weekdays))) {
#line 2067 "utils.c"
					gchar* _tmp6_;
#line 255 "../src/utils.vala"
					_tmp6_ = g_strdup (_ ("Weekdays"));
#line 255 "../src/utils.vala"
					_g_free0 (r);
#line 255 "../src/utils.vala"
					r = _tmp6_;
#line 2075 "utils.c"
				} else {
#line 256 "../src/utils.vala"
					if (clocks_utils_weekdays_days_equal (self, CLOCKS_UTILS_WEEKDAYS_weekends, (gint) G_N_ELEMENTS (CLOCKS_UTILS_WEEKDAYS_weekends))) {
#line 2079 "utils.c"
						gchar* _tmp7_;
#line 257 "../src/utils.vala"
						_tmp7_ = g_strdup (_ ("Weekends"));
#line 257 "../src/utils.vala"
						_g_free0 (r);
#line 257 "../src/utils.vala"
						r = _tmp7_;
#line 2087 "utils.c"
					} else {
						gchar** abbrs = NULL;
						gchar** _tmp8_;
						gint abbrs_length1;
						gint _abbrs_size_;
						gchar** _tmp15_;
						gint _tmp15__length1;
						gchar* _tmp16_;
#line 259 "../src/utils.vala"
						_tmp8_ = g_new0 (gchar*, 0 + 1);
#line 259 "../src/utils.vala"
						abbrs = _tmp8_;
#line 259 "../src/utils.vala"
						abbrs_length1 = 0;
#line 259 "../src/utils.vala"
						_abbrs_size_ = abbrs_length1;
#line 2104 "utils.c"
						{
							gint i = 0;
#line 260 "../src/utils.vala"
							i = 0;
#line 2109 "utils.c"
							{
								gboolean _tmp9_ = FALSE;
#line 260 "../src/utils.vala"
								_tmp9_ = TRUE;
#line 260 "../src/utils.vala"
								while (TRUE) {
#line 2116 "utils.c"
									ClocksUtilsWeekdaysDay d = 0;
									ClocksUtilsWeekdaysDay _tmp11_;
#line 260 "../src/utils.vala"
									if (!_tmp9_) {
#line 2121 "utils.c"
										gint _tmp10_;
#line 260 "../src/utils.vala"
										_tmp10_ = i;
#line 260 "../src/utils.vala"
										i = _tmp10_ + 1;
#line 2127 "utils.c"
									}
#line 260 "../src/utils.vala"
									_tmp9_ = FALSE;
#line 260 "../src/utils.vala"
									if (!(i < 7)) {
#line 260 "../src/utils.vala"
										break;
#line 2135 "utils.c"
									}
#line 261 "../src/utils.vala"
									d = (clocks_utils_weekdays_get_first_weekday () + i) % 7;
#line 262 "../src/utils.vala"
									_tmp11_ = d;
#line 262 "../src/utils.vala"
									if (clocks_utils_weekdays_get (self, _tmp11_)) {
#line 2143 "utils.c"
										gchar** _tmp12_;
										gint _tmp12__length1;
										ClocksUtilsWeekdaysDay _tmp13_;
										gchar* _tmp14_;
#line 263 "../src/utils.vala"
										_tmp12_ = abbrs;
#line 263 "../src/utils.vala"
										_tmp12__length1 = abbrs_length1;
#line 263 "../src/utils.vala"
										_tmp13_ = d;
#line 263 "../src/utils.vala"
										_tmp14_ = clocks_utils_weekdays_abbreviation (_tmp13_);
#line 263 "../src/utils.vala"
										_vala_array_add3 (&abbrs, &abbrs_length1, &_abbrs_size_, _tmp14_);
#line 2158 "utils.c"
									}
								}
							}
						}
#line 266 "../src/utils.vala"
						_tmp15_ = abbrs;
#line 266 "../src/utils.vala"
						_tmp15__length1 = abbrs_length1;
#line 266 "../src/utils.vala"
						_tmp16_ = _vala_g_strjoinv (", ", _tmp15_, (gint) _tmp15__length1);
#line 266 "../src/utils.vala"
						_g_free0 (r);
#line 266 "../src/utils.vala"
						r = _tmp16_;
#line 256 "../src/utils.vala"
						abbrs = (_vala_array_free (abbrs, abbrs_length1, (GDestroyNotify) g_free), NULL);
#line 2175 "utils.c"
					}
				}
			}
		}
	}
#line 268 "../src/utils.vala"
	result = r;
#line 268 "../src/utils.vala"
	return result;
#line 2185 "utils.c"
}

GVariant*
clocks_utils_weekdays_serialize (ClocksUtilsWeekdays* self)
{
	GVariantBuilder* builder = NULL;
	GVariantType* _tmp0_;
	GVariantType* _tmp1_;
	GVariantBuilder* _tmp2_;
	GVariantBuilder* _tmp3_;
	gint32 i = 0;
	gboolean* _tmp4_;
	gint _tmp4__length1;
	GVariantBuilder* _tmp7_;
	GVariant* _tmp8_;
	GVariant* result = NULL;
#line 274 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 275 "../src/utils.vala"
	_tmp0_ = g_variant_type_new ("ai");
#line 275 "../src/utils.vala"
	_tmp1_ = _tmp0_;
#line 275 "../src/utils.vala"
	_tmp2_ = g_variant_builder_new (_tmp1_);
#line 275 "../src/utils.vala"
	_tmp3_ = _tmp2_;
#line 275 "../src/utils.vala"
	_g_variant_type_free0 (_tmp1_);
#line 275 "../src/utils.vala"
	builder = _tmp3_;
#line 276 "../src/utils.vala"
	i = (gint32) 1;
#line 277 "../src/utils.vala"
	_tmp4_ = self->priv->days;
#line 277 "../src/utils.vala"
	_tmp4__length1 = self->priv->days_length1;
#line 2222 "utils.c"
	{
		gboolean* d_collection = NULL;
		gint d_collection_length1 = 0;
		gint _d_collection_size_ = 0;
		gint d_it = 0;
#line 277 "../src/utils.vala"
		d_collection = _tmp4_;
#line 277 "../src/utils.vala"
		d_collection_length1 = _tmp4__length1;
#line 277 "../src/utils.vala"
		for (d_it = 0; d_it < d_collection_length1; d_it = d_it + 1) {
#line 2234 "utils.c"
			gboolean d = FALSE;
#line 277 "../src/utils.vala"
			d = d_collection[d_it];
#line 2238 "utils.c"
			{
				gint32 _tmp6_;
#line 278 "../src/utils.vala"
				if (d) {
#line 2243 "utils.c"
					GVariantBuilder* _tmp5_;
#line 279 "../src/utils.vala"
					_tmp5_ = builder;
#line 279 "../src/utils.vala"
					g_variant_builder_add (_tmp5_, "i", i, NULL);
#line 2249 "utils.c"
				}
#line 281 "../src/utils.vala"
				_tmp6_ = i;
#line 281 "../src/utils.vala"
				i = _tmp6_ + 1;
#line 2255 "utils.c"
			}
		}
	}
#line 283 "../src/utils.vala"
	_tmp7_ = builder;
#line 283 "../src/utils.vala"
	_tmp8_ = g_variant_builder_end (_tmp7_);
#line 283 "../src/utils.vala"
	g_variant_ref_sink (_tmp8_);
#line 283 "../src/utils.vala"
	result = _tmp8_;
#line 283 "../src/utils.vala"
	_g_variant_builder_unref0 (builder);
#line 283 "../src/utils.vala"
	return result;
#line 2271 "utils.c"
}

ClocksUtilsWeekdays*
clocks_utils_weekdays_deserialize (GVariant* days_variant)
{
	ClocksUtilsWeekdays* d = NULL;
	ClocksUtilsWeekdays* _tmp0_;
	ClocksUtilsWeekdays* result = NULL;
#line 286 "../src/utils.vala"
	g_return_val_if_fail (days_variant != NULL, NULL);
#line 287 "../src/utils.vala"
	_tmp0_ = clocks_utils_weekdays_new ();
#line 287 "../src/utils.vala"
	d = _tmp0_;
#line 2286 "utils.c"
	{
		GVariantIter* _v_it = NULL;
		GVariantIter* _tmp1_;
		GVariant* v = NULL;
#line 288 "../src/utils.vala"
		_tmp1_ = g_variant_iter_new (days_variant);
#line 288 "../src/utils.vala"
		_v_it = _tmp1_;
#line 288 "../src/utils.vala"
		while (TRUE) {
#line 2297 "utils.c"
			GVariantIter* _tmp2_;
			GVariant* _tmp3_;
			GVariant* _tmp4_;
			gint32 i = 0;
			GVariant* _tmp5_;
			gboolean _tmp6_ = FALSE;
#line 288 "../src/utils.vala"
			_tmp2_ = _v_it;
#line 288 "../src/utils.vala"
			_tmp3_ = g_variant_iter_next_value (_tmp2_);
#line 288 "../src/utils.vala"
			_g_variant_unref0 (v);
#line 288 "../src/utils.vala"
			v = _tmp3_;
#line 288 "../src/utils.vala"
			_tmp4_ = v;
#line 288 "../src/utils.vala"
			if (!(_tmp4_ != NULL)) {
#line 288 "../src/utils.vala"
				break;
#line 2318 "utils.c"
			}
#line 289 "../src/utils.vala"
			_tmp5_ = v;
#line 289 "../src/utils.vala"
			i = g_variant_get_int32 (_tmp5_);
#line 290 "../src/utils.vala"
			if (i > ((gint32) 0)) {
#line 290 "../src/utils.vala"
				_tmp6_ = i <= ((gint32) 7);
#line 2328 "utils.c"
			} else {
#line 290 "../src/utils.vala"
				_tmp6_ = FALSE;
#line 2332 "utils.c"
			}
#line 290 "../src/utils.vala"
			if (_tmp6_) {
#line 2336 "utils.c"
				ClocksUtilsWeekdays* _tmp7_;
#line 291 "../src/utils.vala"
				_tmp7_ = d;
#line 291 "../src/utils.vala"
				clocks_utils_weekdays_set (_tmp7_, (ClocksUtilsWeekdaysDay) (i - 1), TRUE);
#line 2342 "utils.c"
			} else {
#line 293 "../src/utils.vala"
				g_warning ("utils.vala:293: Invalid days %d", (gint) i);
#line 2346 "utils.c"
			}
		}
#line 288 "../src/utils.vala"
		_g_variant_unref0 (v);
#line 288 "../src/utils.vala"
		_g_variant_iter_free0 (_v_it);
#line 2353 "utils.c"
	}
#line 296 "../src/utils.vala"
	result = d;
#line 296 "../src/utils.vala"
	return result;
#line 2359 "utils.c"
}

gboolean
clocks_utils_weekdays_get_empty (ClocksUtilsWeekdays* self)
{
	gboolean result;
	gboolean* _tmp0_;
	gboolean* _tmp1_;
	gint _tmp1__length1;
	gboolean _tmp2_;
#line 215 "../src/utils.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 216 "../src/utils.vala"
	_tmp0_ = g_new0 (gboolean, 7);
#line 216 "../src/utils.vala"
	_tmp0_[0] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[1] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[2] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[3] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[4] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[5] = FALSE;
#line 216 "../src/utils.vala"
	_tmp0_[6] = FALSE;
#line 216 "../src/utils.vala"
	_tmp1_ = _tmp0_;
#line 216 "../src/utils.vala"
	_tmp1__length1 = 7;
#line 216 "../src/utils.vala"
	_tmp2_ = clocks_utils_weekdays_days_equal (self, _tmp1_, (gint) 7);
#line 216 "../src/utils.vala"
	_tmp1_ = (g_free (_tmp1_), NULL);
#line 216 "../src/utils.vala"
	result = _tmp2_;
#line 216 "../src/utils.vala"
	return result;
#line 2400 "utils.c"
}

static void
clocks_utils_value_weekdays_init (GValue* value)
{
#line 147 "../src/utils.vala"
	value->data[0].v_pointer = NULL;
#line 2408 "utils.c"
}

static void
clocks_utils_value_weekdays_free_value (GValue* value)
{
#line 147 "../src/utils.vala"
	if (value->data[0].v_pointer) {
#line 147 "../src/utils.vala"
		clocks_utils_weekdays_unref (value->data[0].v_pointer);
#line 2418 "utils.c"
	}
}

static void
clocks_utils_value_weekdays_copy_value (const GValue* src_value,
                                        GValue* dest_value)
{
#line 147 "../src/utils.vala"
	if (src_value->data[0].v_pointer) {
#line 147 "../src/utils.vala"
		dest_value->data[0].v_pointer = clocks_utils_weekdays_ref (src_value->data[0].v_pointer);
#line 2430 "utils.c"
	} else {
#line 147 "../src/utils.vala"
		dest_value->data[0].v_pointer = NULL;
#line 2434 "utils.c"
	}
}

static gpointer
clocks_utils_value_weekdays_peek_pointer (const GValue* value)
{
#line 147 "../src/utils.vala"
	return value->data[0].v_pointer;
#line 2443 "utils.c"
}

static gchar*
clocks_utils_value_weekdays_collect_value (GValue* value,
                                           guint n_collect_values,
                                           GTypeCValue* collect_values,
                                           guint collect_flags)
{
#line 147 "../src/utils.vala"
	if (collect_values[0].v_pointer) {
#line 2454 "utils.c"
		ClocksUtilsWeekdays * object;
		object = collect_values[0].v_pointer;
#line 147 "../src/utils.vala"
		if (object->parent_instance.g_class == NULL) {
#line 147 "../src/utils.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 2461 "utils.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 147 "../src/utils.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 2465 "utils.c"
		}
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = clocks_utils_weekdays_ref (object);
#line 2469 "utils.c"
	} else {
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = NULL;
#line 2473 "utils.c"
	}
#line 147 "../src/utils.vala"
	return NULL;
#line 2477 "utils.c"
}

static gchar*
clocks_utils_value_weekdays_lcopy_value (const GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
	ClocksUtilsWeekdays ** object_p;
	object_p = collect_values[0].v_pointer;
#line 147 "../src/utils.vala"
	if (!object_p) {
#line 147 "../src/utils.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 2492 "utils.c"
	}
#line 147 "../src/utils.vala"
	if (!value->data[0].v_pointer) {
#line 147 "../src/utils.vala"
		*object_p = NULL;
#line 2498 "utils.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 147 "../src/utils.vala"
		*object_p = value->data[0].v_pointer;
#line 2502 "utils.c"
	} else {
#line 147 "../src/utils.vala"
		*object_p = clocks_utils_weekdays_ref (value->data[0].v_pointer);
#line 2506 "utils.c"
	}
#line 147 "../src/utils.vala"
	return NULL;
#line 2510 "utils.c"
}

GParamSpec*
clocks_utils_param_spec_weekdays (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags)
{
	ClocksUtilsParamSpecWeekdays* spec;
#line 147 "../src/utils.vala"
	g_return_val_if_fail (g_type_is_a (object_type, CLOCKS_UTILS_TYPE_WEEKDAYS), NULL);
#line 147 "../src/utils.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 147 "../src/utils.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 147 "../src/utils.vala"
	return G_PARAM_SPEC (spec);
#line 2529 "utils.c"
}

gpointer
clocks_utils_value_get_weekdays (const GValue* value)
{
#line 147 "../src/utils.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CLOCKS_UTILS_TYPE_WEEKDAYS), NULL);
#line 147 "../src/utils.vala"
	return value->data[0].v_pointer;
#line 2539 "utils.c"
}

void
clocks_utils_value_set_weekdays (GValue* value,
                                 gpointer v_object)
{
	ClocksUtilsWeekdays * old;
#line 147 "../src/utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CLOCKS_UTILS_TYPE_WEEKDAYS));
#line 147 "../src/utils.vala"
	old = value->data[0].v_pointer;
#line 147 "../src/utils.vala"
	if (v_object) {
#line 147 "../src/utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CLOCKS_UTILS_TYPE_WEEKDAYS));
#line 147 "../src/utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = v_object;
#line 147 "../src/utils.vala"
		clocks_utils_weekdays_ref (value->data[0].v_pointer);
#line 2561 "utils.c"
	} else {
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = NULL;
#line 2565 "utils.c"
	}
#line 147 "../src/utils.vala"
	if (old) {
#line 147 "../src/utils.vala"
		clocks_utils_weekdays_unref (old);
#line 2571 "utils.c"
	}
}

void
clocks_utils_value_take_weekdays (GValue* value,
                                  gpointer v_object)
{
	ClocksUtilsWeekdays * old;
#line 147 "../src/utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CLOCKS_UTILS_TYPE_WEEKDAYS));
#line 147 "../src/utils.vala"
	old = value->data[0].v_pointer;
#line 147 "../src/utils.vala"
	if (v_object) {
#line 147 "../src/utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CLOCKS_UTILS_TYPE_WEEKDAYS));
#line 147 "../src/utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = v_object;
#line 2592 "utils.c"
	} else {
#line 147 "../src/utils.vala"
		value->data[0].v_pointer = NULL;
#line 2596 "utils.c"
	}
#line 147 "../src/utils.vala"
	if (old) {
#line 147 "../src/utils.vala"
		clocks_utils_weekdays_unref (old);
#line 2602 "utils.c"
	}
}

static void
clocks_utils_weekdays_class_init (ClocksUtilsWeekdaysClass * klass,
                                  gpointer klass_data)
{
#line 147 "../src/utils.vala"
	clocks_utils_weekdays_parent_class = g_type_class_peek_parent (klass);
#line 147 "../src/utils.vala"
	((ClocksUtilsWeekdaysClass *) klass)->finalize = clocks_utils_weekdays_finalize;
#line 147 "../src/utils.vala"
	g_type_class_adjust_private_offset (klass, &ClocksUtilsWeekdays_private_offset);
#line 2616 "utils.c"
}

static void
clocks_utils_weekdays_instance_init (ClocksUtilsWeekdays * self,
                                     gpointer klass)
{
	gboolean* _tmp0_;
#line 147 "../src/utils.vala"
	self->priv = clocks_utils_weekdays_get_instance_private (self);
#line 207 "../src/utils.vala"
	_tmp0_ = g_new0 (gboolean, 7);
#line 207 "../src/utils.vala"
	_tmp0_[0] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[1] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[2] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[3] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[4] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[5] = FALSE;
#line 207 "../src/utils.vala"
	_tmp0_[6] = FALSE;
#line 207 "../src/utils.vala"
	self->priv->days = _tmp0_;
#line 207 "../src/utils.vala"
	self->priv->days_length1 = 7;
#line 207 "../src/utils.vala"
	self->priv->_days_size_ = self->priv->days_length1;
#line 147 "../src/utils.vala"
	self->ref_count = 1;
#line 2650 "utils.c"
}

static void
clocks_utils_weekdays_finalize (ClocksUtilsWeekdays * obj)
{
	ClocksUtilsWeekdays * self;
#line 147 "../src/utils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_UTILS_TYPE_WEEKDAYS, ClocksUtilsWeekdays);
#line 147 "../src/utils.vala"
	g_signal_handlers_destroy (self);
#line 207 "../src/utils.vala"
	self->priv->days = (g_free (self->priv->days), NULL);
#line 2663 "utils.c"
}

GType
clocks_utils_weekdays_get_type (void)
{
	static volatile gsize clocks_utils_weekdays_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_utils_weekdays_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { clocks_utils_value_weekdays_init, clocks_utils_value_weekdays_free_value, clocks_utils_value_weekdays_copy_value, clocks_utils_value_weekdays_peek_pointer, "p", clocks_utils_value_weekdays_collect_value, "p", clocks_utils_value_weekdays_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ClocksUtilsWeekdaysClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_utils_weekdays_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksUtilsWeekdays), 0, (GInstanceInitFunc) clocks_utils_weekdays_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType clocks_utils_weekdays_type_id;
		clocks_utils_weekdays_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ClocksUtilsWeekdays", &g_define_type_info, &g_define_type_fundamental_info, 0);
		ClocksUtilsWeekdays_private_offset = g_type_add_instance_private (clocks_utils_weekdays_type_id, sizeof (ClocksUtilsWeekdaysPrivate));
		g_once_init_leave (&clocks_utils_weekdays_type_id__volatile, clocks_utils_weekdays_type_id);
	}
	return clocks_utils_weekdays_type_id__volatile;
}

gpointer
clocks_utils_weekdays_ref (gpointer instance)
{
	ClocksUtilsWeekdays * self;
	self = instance;
#line 147 "../src/utils.vala"
	g_atomic_int_inc (&self->ref_count);
#line 147 "../src/utils.vala"
	return instance;
#line 2691 "utils.c"
}

void
clocks_utils_weekdays_unref (gpointer instance)
{
	ClocksUtilsWeekdays * self;
	self = instance;
#line 147 "../src/utils.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 147 "../src/utils.vala"
		CLOCKS_UTILS_WEEKDAYS_GET_CLASS (self)->finalize (self);
#line 147 "../src/utils.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 2705 "utils.c"
	}
}

static inline gpointer
clocks_utils_bell_get_instance_private (ClocksUtilsBell* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksUtilsBell_private_offset);
}

ClocksUtilsBell*
clocks_utils_bell_construct (GType object_type,
                             const gchar* soundid)
{
	ClocksUtilsBell * self = NULL;
	GSettings* settings = NULL;
	GSettings* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GCancellable* _tmp8_;
	GError* _inner_error0_ = NULL;
#line 306 "../src/utils.vala"
	g_return_val_if_fail (soundid != NULL, NULL);
#line 306 "../src/utils.vala"
	self = (ClocksUtilsBell*) g_object_new (object_type, NULL);
#line 2730 "utils.c"
	{
		GSoundContext* _tmp0_ = NULL;
		GSoundContext* _tmp1_;
		GSoundContext* _tmp2_;
#line 308 "../src/utils.vala"
		_tmp1_ = gsound_context_new (NULL, &_inner_error0_);
#line 308 "../src/utils.vala"
		_tmp0_ = _tmp1_;
#line 308 "../src/utils.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 2741 "utils.c"
			goto __catch8_g_error;
		}
#line 308 "../src/utils.vala"
		_tmp2_ = _tmp0_;
#line 308 "../src/utils.vala"
		_tmp0_ = NULL;
#line 308 "../src/utils.vala"
		_g_object_unref0 (self->priv->gsound);
#line 308 "../src/utils.vala"
		self->priv->gsound = _tmp2_;
#line 307 "../src/utils.vala"
		_g_object_unref0 (_tmp0_);
#line 2754 "utils.c"
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
		GError* _tmp3_;
		const gchar* _tmp4_;
#line 307 "../src/utils.vala"
		e = _inner_error0_;
#line 307 "../src/utils.vala"
		_inner_error0_ = NULL;
#line 310 "../src/utils.vala"
		_tmp3_ = e;
#line 310 "../src/utils.vala"
		_tmp4_ = _tmp3_->message;
#line 310 "../src/utils.vala"
		g_warning ("utils.vala:310: Sound could not be initialized, error: %s", _tmp4_);
#line 307 "../src/utils.vala"
		_g_error_free0 (e);
#line 2774 "utils.c"
	}
	__finally8:
#line 307 "../src/utils.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 307 "../src/utils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 307 "../src/utils.vala"
		g_clear_error (&_inner_error0_);
#line 307 "../src/utils.vala"
		return NULL;
#line 2785 "utils.c"
	}
#line 313 "../src/utils.vala"
	_tmp5_ = g_settings_new ("org.gnome.desktop.sound");
#line 313 "../src/utils.vala"
	settings = _tmp5_;
#line 314 "../src/utils.vala"
	_tmp6_ = g_settings_get_string (settings, "theme-name");
#line 314 "../src/utils.vala"
	_g_free0 (self->priv->soundtheme);
#line 314 "../src/utils.vala"
	self->priv->soundtheme = _tmp6_;
#line 315 "../src/utils.vala"
	_tmp7_ = g_strdup (soundid);
#line 315 "../src/utils.vala"
	_g_free0 (self->priv->sound);
#line 315 "../src/utils.vala"
	self->priv->sound = _tmp7_;
#line 316 "../src/utils.vala"
	_tmp8_ = g_cancellable_new ();
#line 316 "../src/utils.vala"
	_g_object_unref0 (self->priv->cancellable);
#line 316 "../src/utils.vala"
	self->priv->cancellable = _tmp8_;
#line 306 "../src/utils.vala"
	_g_object_unref0 (settings);
#line 306 "../src/utils.vala"
	return self;
#line 2813 "utils.c"
}

ClocksUtilsBell*
clocks_utils_bell_new (const gchar* soundid)
{
#line 306 "../src/utils.vala"
	return clocks_utils_bell_construct (CLOCKS_UTILS_TYPE_BELL, soundid);
#line 2821 "utils.c"
}

static void
clocks_utils_bell_ring_real_data_free (gpointer _data)
{
	ClocksUtilsBellRingRealData* _data_;
	_data_ = _data;
#line 300 "../src/utils.vala"
	_g_object_unref0 (_data_->self);
#line 300 "../src/utils.vala"
	g_slice_free (ClocksUtilsBellRingRealData, _data_);
#line 2833 "utils.c"
}

static void
clocks_utils_bell_ring_real (ClocksUtilsBell* self,
                             gboolean repeat,
                             GAsyncReadyCallback _callback_,
                             gpointer _user_data_)
{
	ClocksUtilsBellRingRealData* _data_;
	ClocksUtilsBell* _tmp0_;
#line 300 "../src/utils.vala"
	_data_ = g_slice_new0 (ClocksUtilsBellRingRealData);
#line 300 "../src/utils.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 300 "../src/utils.vala"
	g_task_set_task_data (_data_->_async_result, _data_, clocks_utils_bell_ring_real_data_free);
#line 300 "../src/utils.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 300 "../src/utils.vala"
	_data_->self = _tmp0_;
#line 300 "../src/utils.vala"
	_data_->repeat = repeat;
#line 300 "../src/utils.vala"
	clocks_utils_bell_ring_real_co (_data_);
#line 2858 "utils.c"
}

static void
clocks_utils_bell_ring_real_finish (ClocksUtilsBell* self,
                                    GAsyncResult* _res_)
{
	ClocksUtilsBellRingRealData* _data_;
#line 300 "../src/utils.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 2868 "utils.c"
}

static void
clocks_utils_bell_ring_real_ready (GObject* source_object,
                                   GAsyncResult* _res_,
                                   gpointer _user_data_)
{
	ClocksUtilsBellRingRealData* _data_;
#line 326 "../src/utils.vala"
	_data_ = _user_data_;
#line 326 "../src/utils.vala"
	_data_->_source_object_ = source_object;
#line 326 "../src/utils.vala"
	_data_->_res_ = _res_;
#line 326 "../src/utils.vala"
	clocks_utils_bell_ring_real_co (_data_);
#line 2885 "utils.c"
}

static gboolean
clocks_utils_bell_ring_real_co (ClocksUtilsBellRingRealData* _data_)
{
#line 319 "../src/utils.vala"
	switch (_data_->_state_) {
#line 319 "../src/utils.vala"
		case 0:
#line 2895 "utils.c"
		goto _state_0;
#line 319 "../src/utils.vala"
		case 1:
#line 2899 "utils.c"
		goto _state_1;
		default:
#line 319 "../src/utils.vala"
		g_assert_not_reached ();
#line 2904 "utils.c"
	}
	_state_0:
#line 320 "../src/utils.vala"
	_data_->_tmp0_ = _data_->self->priv->gsound;
#line 320 "../src/utils.vala"
	if (_data_->_tmp0_ == NULL) {
#line 321 "../src/utils.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 321 "../src/utils.vala"
		if (_data_->_state_ != 0) {
#line 321 "../src/utils.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 321 "../src/utils.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 2919 "utils.c"
			}
		}
#line 321 "../src/utils.vala"
		g_object_unref (_data_->_async_result);
#line 321 "../src/utils.vala"
		return FALSE;
#line 2926 "utils.c"
	}
	{
		{
#line 325 "../src/utils.vala"
			_data_->_tmp1_ = TRUE;
#line 325 "../src/utils.vala"
			while (TRUE) {
#line 325 "../src/utils.vala"
				if (!_data_->_tmp1_) {
#line 330 "../src/utils.vala"
					if (!_data_->repeat) {
#line 330 "../src/utils.vala"
						break;
#line 2940 "utils.c"
					}
				}
#line 325 "../src/utils.vala"
				_data_->_tmp1_ = FALSE;
#line 326 "../src/utils.vala"
				_data_->_tmp2_ = _data_->self->priv->gsound;
#line 326 "../src/utils.vala"
				_data_->_tmp3_ = _data_->self->priv->cancellable;
#line 326 "../src/utils.vala"
				_data_->_tmp4_ = _data_->self->priv->sound;
#line 326 "../src/utils.vala"
				_data_->_tmp5_ = _data_->self->priv->soundtheme;
#line 326 "../src/utils.vala"
				_data_->_state_ = 1;
#line 326 "../src/utils.vala"
				gsound_context_play_full (_data_->_tmp2_, _data_->_tmp3_, clocks_utils_bell_ring_real_ready, _data_, GSOUND_ATTR_EVENT_ID, _data_->_tmp4_, GSOUND_ATTR_CANBERRA_XDG_THEME_NAME, _data_->_tmp5_, GSOUND_ATTR_MEDIA_ROLE, "alarm", NULL);
#line 326 "../src/utils.vala"
				return FALSE;
#line 2959 "utils.c"
				_state_1:
#line 326 "../src/utils.vala"
				gsound_context_play_full_finish (_data_->_tmp2_, _data_->_res_, &_data_->_inner_error0_);
#line 326 "../src/utils.vala"
				if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 326 "../src/utils.vala"
					if (g_error_matches (_data_->_inner_error0_, G_IO_ERROR, G_IO_ERROR_CANCELLED)) {
#line 2967 "utils.c"
						goto __catch9_g_io_error_cancelled;
					}
					goto __catch9_g_error;
				}
			}
		}
	}
	goto __finally9;
	__catch9_g_io_error_cancelled:
	{
#line 324 "../src/utils.vala"
		_data_->e = _data_->_inner_error0_;
#line 324 "../src/utils.vala"
		_data_->_inner_error0_ = NULL;
#line 324 "../src/utils.vala"
		_g_error_free0 (_data_->e);
#line 2984 "utils.c"
	}
	goto __finally9;
	__catch9_g_error:
	{
#line 324 "../src/utils.vala"
		_data_->_vala1_e = _data_->_inner_error0_;
#line 324 "../src/utils.vala"
		_data_->_inner_error0_ = NULL;
#line 334 "../src/utils.vala"
		_data_->_tmp6_ = _data_->_vala1_e;
#line 334 "../src/utils.vala"
		_data_->_tmp7_ = _data_->_tmp6_->message;
#line 334 "../src/utils.vala"
		g_warning ("utils.vala:334: Error playing sound: %s", _data_->_tmp7_);
#line 324 "../src/utils.vala"
		_g_error_free0 (_data_->_vala1_e);
#line 3001 "utils.c"
	}
	__finally9:
#line 324 "../src/utils.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 324 "../src/utils.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 324 "../src/utils.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 324 "../src/utils.vala"
		g_object_unref (_data_->_async_result);
#line 324 "../src/utils.vala"
		return FALSE;
#line 3014 "utils.c"
	}
#line 319 "../src/utils.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 319 "../src/utils.vala"
	if (_data_->_state_ != 0) {
#line 319 "../src/utils.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 319 "../src/utils.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 3024 "utils.c"
		}
	}
#line 319 "../src/utils.vala"
	g_object_unref (_data_->_async_result);
#line 319 "../src/utils.vala"
	return FALSE;
#line 3031 "utils.c"
}

void
clocks_utils_bell_ring_once (ClocksUtilsBell* self)
{
#line 338 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 339 "../src/utils.vala"
	clocks_utils_bell_ring_real (self, FALSE, NULL, NULL);
#line 3041 "utils.c"
}

void
clocks_utils_bell_ring (ClocksUtilsBell* self)
{
#line 342 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 343 "../src/utils.vala"
	clocks_utils_bell_ring_real (self, TRUE, NULL, NULL);
#line 3051 "utils.c"
}

void
clocks_utils_bell_stop (ClocksUtilsBell* self)
{
	GCancellable* _tmp0_;
#line 346 "../src/utils.vala"
	g_return_if_fail (self != NULL);
#line 347 "../src/utils.vala"
	_tmp0_ = self->priv->cancellable;
#line 347 "../src/utils.vala"
	g_cancellable_cancel (_tmp0_);
#line 3064 "utils.c"
}

static void
clocks_utils_bell_class_init (ClocksUtilsBellClass * klass,
                              gpointer klass_data)
{
#line 300 "../src/utils.vala"
	clocks_utils_bell_parent_class = g_type_class_peek_parent (klass);
#line 300 "../src/utils.vala"
	g_type_class_adjust_private_offset (klass, &ClocksUtilsBell_private_offset);
#line 300 "../src/utils.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_utils_bell_finalize;
#line 3077 "utils.c"
}

static void
clocks_utils_bell_instance_init (ClocksUtilsBell * self,
                                 gpointer klass)
{
#line 300 "../src/utils.vala"
	self->priv = clocks_utils_bell_get_instance_private (self);
#line 3086 "utils.c"
}

static void
clocks_utils_bell_finalize (GObject * obj)
{
	ClocksUtilsBell * self;
#line 300 "../src/utils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_UTILS_TYPE_BELL, ClocksUtilsBell);
#line 301 "../src/utils.vala"
	_g_object_unref0 (self->priv->gsound);
#line 302 "../src/utils.vala"
	_g_object_unref0 (self->priv->cancellable);
#line 303 "../src/utils.vala"
	_g_free0 (self->priv->soundtheme);
#line 304 "../src/utils.vala"
	_g_free0 (self->priv->sound);
#line 300 "../src/utils.vala"
	G_OBJECT_CLASS (clocks_utils_bell_parent_class)->finalize (obj);
#line 3105 "utils.c"
}

GType
clocks_utils_bell_get_type (void)
{
	static volatile gsize clocks_utils_bell_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_utils_bell_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksUtilsBellClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_utils_bell_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksUtilsBell), 0, (GInstanceInitFunc) clocks_utils_bell_instance_init, NULL };
		GType clocks_utils_bell_type_id;
		clocks_utils_bell_type_id = g_type_register_static (G_TYPE_OBJECT, "ClocksUtilsBell", &g_define_type_info, 0);
		ClocksUtilsBell_private_offset = g_type_add_instance_private (clocks_utils_bell_type_id, sizeof (ClocksUtilsBellPrivate));
		g_once_init_leave (&clocks_utils_bell_type_id__volatile, clocks_utils_bell_type_id);
	}
	return clocks_utils_bell_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

