/* window.c generated by valac 0.46.0.4-d3026, the Vala compiler
 * generated from window.vala, do not modify */

/*
 * Copyright (C) 2013  Paolo Borelli <pborelli@gnome.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <handy.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <cairo.h>
#include "config.h"
#include <libgweather/gweather.h>

#define CLOCKS_TYPE_WINDOW (clocks_window_get_type ())
#define CLOCKS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_WINDOW, ClocksWindow))
#define CLOCKS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_WINDOW, ClocksWindowClass))
#define CLOCKS_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_WINDOW))
#define CLOCKS_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_WINDOW))
#define CLOCKS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_WINDOW, ClocksWindowClass))

typedef struct _ClocksWindow ClocksWindow;
typedef struct _ClocksWindowClass ClocksWindowClass;
typedef struct _ClocksWindowPrivate ClocksWindowPrivate;

#define CLOCKS_TYPE_HEADER_BAR (clocks_header_bar_get_type ())
#define CLOCKS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBar))
#define CLOCKS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBarClass))
#define CLOCKS_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_HEADER_BAR))
#define CLOCKS_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_HEADER_BAR))
#define CLOCKS_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_HEADER_BAR, ClocksHeaderBarClass))

typedef struct _ClocksHeaderBar ClocksHeaderBar;
typedef struct _ClocksHeaderBarClass ClocksHeaderBarClass;
enum  {
	CLOCKS_WINDOW_0_PROPERTY,
	CLOCKS_WINDOW_NUM_PROPERTIES
};
static GParamSpec* clocks_window_properties[CLOCKS_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CLOCKS_TYPE_APPLICATION (clocks_application_get_type ())
#define CLOCKS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplication))
#define CLOCKS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))
#define CLOCKS_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TYPE_APPLICATION))
#define CLOCKS_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TYPE_APPLICATION, ClocksApplicationClass))

typedef struct _ClocksApplication ClocksApplication;
typedef struct _ClocksApplicationClass ClocksApplicationClass;

#define CLOCKS_WORLD_TYPE_FACE (clocks_world_face_get_type ())
#define CLOCKS_WORLD_FACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_WORLD_TYPE_FACE, ClocksWorldFace))
#define CLOCKS_WORLD_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_WORLD_TYPE_FACE, ClocksWorldFaceClass))
#define CLOCKS_WORLD_IS_FACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_WORLD_TYPE_FACE))
#define CLOCKS_WORLD_IS_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_WORLD_TYPE_FACE))
#define CLOCKS_WORLD_FACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_WORLD_TYPE_FACE, ClocksWorldFaceClass))

typedef struct _ClocksWorldFace ClocksWorldFace;
typedef struct _ClocksWorldFaceClass ClocksWorldFaceClass;

#define CLOCKS_STOPWATCH_TYPE_FACE (clocks_stopwatch_face_get_type ())
#define CLOCKS_STOPWATCH_FACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace))
#define CLOCKS_STOPWATCH_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFaceClass))
#define CLOCKS_STOPWATCH_IS_FACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_STOPWATCH_TYPE_FACE))
#define CLOCKS_STOPWATCH_IS_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_STOPWATCH_TYPE_FACE))
#define CLOCKS_STOPWATCH_FACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFaceClass))

typedef struct _ClocksStopwatchFace ClocksStopwatchFace;
typedef struct _ClocksStopwatchFaceClass ClocksStopwatchFaceClass;

#define CLOCKS_TIMER_TYPE_FACE (clocks_timer_face_get_type ())
#define CLOCKS_TIMER_FACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TIMER_TYPE_FACE, ClocksTimerFace))
#define CLOCKS_TIMER_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_TIMER_TYPE_FACE, ClocksTimerFaceClass))
#define CLOCKS_TIMER_IS_FACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TIMER_TYPE_FACE))
#define CLOCKS_TIMER_IS_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_TIMER_TYPE_FACE))
#define CLOCKS_TIMER_FACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_TIMER_TYPE_FACE, ClocksTimerFaceClass))

typedef struct _ClocksTimerFace ClocksTimerFace;
typedef struct _ClocksTimerFaceClass ClocksTimerFaceClass;
typedef struct _Block8Data Block8Data;
typedef enum  {
	CLOCKS_PANEL_ID_WORLD,
	CLOCKS_PANEL_ID_ALARM,
	CLOCKS_PANEL_ID_STOPWATCH,
	CLOCKS_PANEL_ID_TIMER
} ClocksPanelId;

#define CLOCKS_TYPE_PANEL_ID (clocks_panel_id_get_type ())

#define CLOCKS_ALARM_TYPE_FACE (clocks_alarm_face_get_type ())
#define CLOCKS_ALARM_FACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_ALARM_TYPE_FACE, ClocksAlarmFace))
#define CLOCKS_ALARM_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLOCKS_ALARM_TYPE_FACE, ClocksAlarmFaceClass))
#define CLOCKS_ALARM_IS_FACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_ALARM_TYPE_FACE))
#define CLOCKS_ALARM_IS_FACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLOCKS_ALARM_TYPE_FACE))
#define CLOCKS_ALARM_FACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLOCKS_ALARM_TYPE_FACE, ClocksAlarmFaceClass))

typedef struct _ClocksAlarmFace ClocksAlarmFace;
typedef struct _ClocksAlarmFaceClass ClocksAlarmFaceClass;

#define CLOCKS_TYPE_CLOCK (clocks_clock_get_type ())
#define CLOCKS_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLOCKS_TYPE_CLOCK, ClocksClock))
#define CLOCKS_IS_CLOCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLOCKS_TYPE_CLOCK))
#define CLOCKS_CLOCK_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CLOCKS_TYPE_CLOCK, ClocksClockIface))

typedef struct _ClocksClock ClocksClock;
typedef struct _ClocksClockIface ClocksClockIface;
typedef enum  {
	CLOCKS_STOPWATCH_FACE_STATE_RESET,
	CLOCKS_STOPWATCH_FACE_STATE_RUNNING,
	CLOCKS_STOPWATCH_FACE_STATE_STOPPED
} ClocksStopwatchFaceState;

#define CLOCKS_STOPWATCH_FACE_TYPE_STATE (clocks_stopwatch_face_state_get_type ())
typedef enum  {
	CLOCKS_TIMER_FACE_STATE_STOPPED,
	CLOCKS_TIMER_FACE_STATE_RUNNING,
	CLOCKS_TIMER_FACE_STATE_PAUSED
} ClocksTimerFaceState;

#define CLOCKS_TIMER_FACE_TYPE_STATE (clocks_timer_face_state_get_type ())
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef enum  {
	CLOCKS_HEADER_BAR_MODE_NORMAL,
	CLOCKS_HEADER_BAR_MODE_SELECTION,
	CLOCKS_HEADER_BAR_MODE_STANDALONE
} ClocksHeaderBarMode;

#define CLOCKS_HEADER_BAR_TYPE_MODE (clocks_header_bar_mode_get_type ())
enum  {
	CLOCKS_WINDOW_CHANGE_PAGE_SIGNAL,
	CLOCKS_WINDOW_NUM_SIGNALS
};
static guint clocks_window_signals[CLOCKS_WINDOW_NUM_SIGNALS] = {0};

struct _ClocksWindow {
	GtkApplicationWindow parent_instance;
	ClocksWindowPrivate * priv;
};

struct _ClocksWindowClass {
	GtkApplicationWindowClass parent_class;
	void (*change_page) (ClocksWindow* self, gint offset);
};

struct _ClocksWindowPrivate {
	ClocksHeaderBar* header_bar;
	GtkStack* stack;
	GtkMenuButton* menu_button;
	HdyViewSwitcherBar* switcher_bar;
	HdySqueezer* squeezer;
	HdyViewSwitcher* title_wide_switcher;
	HdyViewSwitcher* title_narrow_switcher;
	GtkBox* title_text;
	GSettings* settings;
	GtkWidget** panels;
	gint panels_length1;
	gint _panels_size_;
};

struct _Block8Data {
	int _ref_count_;
	ClocksWindow* self;
	ClocksWorldFace* world;
	ClocksStopwatchFace* stopwatch;
	ClocksTimerFace* timer;
	gulong stack_id;
	gulong header_bar_id;
};

struct _ClocksClockIface {
	GTypeInterface parent_iface;
	void (*activate_new) (ClocksClock* self);
	void (*activate_select_all) (ClocksClock* self);
	void (*activate_select_none) (ClocksClock* self);
	gboolean (*escape_pressed) (ClocksClock* self);
	void (*back) (ClocksClock* self);
	void (*update_header_bar) (ClocksClock* self);
	const gchar* (*get_label) (ClocksClock* self);
	void (*set_label) (ClocksClock* self, const gchar* value);
	const gchar* (*get_icon_name) (ClocksClock* self);
	void (*set_icon_name) (ClocksClock* self, const gchar* value);
	ClocksHeaderBar* (*get_header_bar) (ClocksClock* self);
	void (*set_header_bar) (ClocksClock* self, ClocksHeaderBar* value);
	ClocksPanelId (*get_panel_id) (ClocksClock* self);
	void (*set_panel_id) (ClocksClock* self, ClocksPanelId value);
};

static gint ClocksWindow_private_offset;
static gpointer clocks_window_parent_class = NULL;

GType clocks_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksWindow, g_object_unref)
GType clocks_header_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksHeaderBar, g_object_unref)
static void clocks_window_on_show_primary_menu_activate (ClocksWindow* self,
                                                  GSimpleAction* action);
static void _clocks_window_on_show_primary_menu_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                                    GVariant* parameter,
                                                                                    gpointer self);
static void clocks_window_on_new_activate (ClocksWindow* self);
static void _clocks_window_on_new_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                      GVariant* parameter,
                                                                      gpointer self);
static void clocks_window_on_help_activate (ClocksWindow* self);
static void _clocks_window_on_help_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                       GVariant* parameter,
                                                                       gpointer self);
static void clocks_window_on_about_activate (ClocksWindow* self);
static void _clocks_window_on_about_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self);
static void clocks_window_on_select_all_activate (ClocksWindow* self);
static void _clocks_window_on_select_all_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                             GVariant* parameter,
                                                                             gpointer self);
static void clocks_window_on_select_none_activate (ClocksWindow* self);
static void _clocks_window_on_select_none_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                              GVariant* parameter,
                                                                              gpointer self);
GType clocks_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksApplication, g_object_unref)
ClocksWindow* clocks_window_new (ClocksApplication* app);
ClocksWindow* clocks_window_construct (GType object_type,
                                       ClocksApplication* app);
GType clocks_world_face_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksWorldFace, g_object_unref)
GType clocks_stopwatch_face_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksStopwatchFace, g_object_unref)
GType clocks_timer_face_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksTimerFace, g_object_unref)
static Block8Data* block8_data_ref (Block8Data* _data8_);
static void block8_data_unref (void * _userdata_);
static void __lambda9_ (ClocksWindow* self);
static void ___lambda9__gtk_widget_destroy (GtkWidget* _sender,
                                     gpointer self);
#define CLOCKS_N_PANELS 4
GType clocks_panel_id_get_type (void) G_GNUC_CONST;
ClocksWorldFace* clocks_world_face_new (ClocksHeaderBar* header_bar);
ClocksWorldFace* clocks_world_face_construct (GType object_type,
                                              ClocksHeaderBar* header_bar);
ClocksAlarmFace* clocks_alarm_face_new (ClocksHeaderBar* header_bar);
ClocksAlarmFace* clocks_alarm_face_construct (GType object_type,
                                              ClocksHeaderBar* header_bar);
GType clocks_alarm_face_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ClocksAlarmFace, g_object_unref)
ClocksStopwatchFace* clocks_stopwatch_face_new (ClocksHeaderBar* header_bar);
ClocksStopwatchFace* clocks_stopwatch_face_construct (GType object_type,
                                                      ClocksHeaderBar* header_bar);
ClocksTimerFace* clocks_timer_face_new (ClocksHeaderBar* header_bar);
ClocksTimerFace* clocks_timer_face_construct (GType object_type,
                                              ClocksHeaderBar* header_bar);
GType clocks_clock_get_type (void) G_GNUC_CONST;
const gchar* clocks_clock_get_label (ClocksClock* self);
const gchar* clocks_clock_get_icon_name (ClocksClock* self);
static void ____lambda51_ (ClocksWindow* self);
static void clocks_window_update_header_bar (ClocksWindow* self);
static void _____lambda51__clocks_clock_request_header_bar_update (ClocksClock* _sender,
                                                            gpointer self);
static void __lambda52_ (ClocksWindow* self);
static void ___lambda52__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void __lambda53_ (ClocksWindow* self);
static void ___lambda53__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void __lambda54_ (ClocksWindow* self,
                  GtkWidget* widget,
                  GtkAllocation* allocation);
static void ___lambda54__gtk_widget_size_allocate (GtkWidget* _sender,
                                            GtkAllocation* allocation,
                                            gpointer self);
static void __lambda55_ (Block8Data* _data8_);
static void ___lambda55__gtk_widget_destroy (GtkWidget* _sender,
                                      gpointer self);
static void __lambda56_ (Block8Data* _data8_,
                  ClocksAlarmFace* w);
void clocks_world_face_reset_view (ClocksWorldFace* self);
static void ___lambda56__clocks_alarm_face_ring (ClocksAlarmFace* _sender,
                                          gpointer self);
static void __lambda57_ (Block8Data* _data8_,
                  GParamSpec* w);
GType clocks_stopwatch_face_state_get_type (void) G_GNUC_CONST;
ClocksStopwatchFaceState clocks_stopwatch_face_get_state (ClocksStopwatchFace* self);
static void ___lambda57__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void __lambda58_ (Block8Data* _data8_,
                  ClocksTimerFace* w);
static void ___lambda58__clocks_timer_face_ring (ClocksTimerFace* _sender,
                                          gpointer self);
static void __lambda59_ (Block8Data* _data8_,
                  GParamSpec* w);
GType clocks_timer_face_state_get_type (void) G_GNUC_CONST;
ClocksTimerFaceState clocks_timer_face_get_state (ClocksTimerFace* self);
static void ___lambda59__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
void clocks_clock_activate_new (ClocksClock* self);
void clocks_clock_activate_select_all (ClocksClock* self);
void clocks_clock_activate_select_none (ClocksClock* self);
void clocks_window_show_world (ClocksWindow* self);
void clocks_window_add_world_location (ClocksWindow* self,
                                       GWeatherLocation* location);
void clocks_world_face_add_location (ClocksWorldFace* self,
                                     GWeatherLocation* location);
static gboolean clocks_window_real_key_press_event (GtkWidget* base,
                                             GdkEventKey* event);
gboolean clocks_clock_escape_pressed (ClocksClock* self);
static gboolean clocks_window_real_button_release_event (GtkWidget* base,
                                                  GdkEventButton* event);
void clocks_clock_back (ClocksClock* self);
static gboolean clocks_window_real_configure_event (GtkWidget* base,
                                             GdkEventConfigure* event);
static gboolean clocks_window_real_window_state_event (GtkWidget* base,
                                                GdkEventWindowState* event);
ClocksPanelId clocks_clock_get_panel_id (ClocksClock* self);
void clocks_clock_update_header_bar (ClocksClock* self);
GType clocks_header_bar_mode_get_type (void) G_GNUC_CONST;
ClocksHeaderBarMode clocks_header_bar_get_mode (ClocksHeaderBar* self);
static void clocks_window_real_change_page (ClocksWindow* self,
                                     gint offset);
static void clocks_window_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const GActionEntry CLOCKS_WINDOW_action_entries[6] = {{"show-primary-menu", _clocks_window_on_show_primary_menu_activate_gsimple_action_activate_callback, NULL, "false", NULL}, {"new", _clocks_window_on_new_activate_gsimple_action_activate_callback}, {"help", _clocks_window_on_help_activate_gsimple_action_activate_callback}, {"about", _clocks_window_on_about_activate_gsimple_action_activate_callback}, {"select-all", _clocks_window_on_select_all_activate_gsimple_action_activate_callback}, {"select-none", _clocks_window_on_select_none_activate_gsimple_action_activate_callback}};

static inline gpointer
clocks_window_get_instance_private (ClocksWindow* self)
{
	return G_STRUCT_MEMBER_P (self, ClocksWindow_private_offset);
}

static void
_clocks_window_on_show_primary_menu_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                               GVariant* parameter,
                                                                               gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_show_primary_menu_activate ((ClocksWindow*) self, action);
#line 370 "window.c"
}

static void
_clocks_window_on_new_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                 GVariant* parameter,
                                                                 gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_new_activate ((ClocksWindow*) self);
#line 380 "window.c"
}

static void
_clocks_window_on_help_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                  GVariant* parameter,
                                                                  gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_help_activate ((ClocksWindow*) self);
#line 390 "window.c"
}

static void
_clocks_window_on_about_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                   GVariant* parameter,
                                                                   gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_about_activate ((ClocksWindow*) self);
#line 400 "window.c"
}

static void
_clocks_window_on_select_all_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_select_all_activate ((ClocksWindow*) self);
#line 410 "window.c"
}

static void
_clocks_window_on_select_none_activate_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self)
{
#line 23 "../src/window.vala"
	clocks_window_on_select_none_activate ((ClocksWindow*) self);
#line 420 "window.c"
}

static Block8Data*
block8_data_ref (Block8Data* _data8_)
{
#line 55 "../src/window.vala"
	g_atomic_int_inc (&_data8_->_ref_count_);
#line 55 "../src/window.vala"
	return _data8_;
#line 430 "window.c"
}

static void
block8_data_unref (void * _userdata_)
{
	Block8Data* _data8_;
	_data8_ = (Block8Data*) _userdata_;
#line 55 "../src/window.vala"
	if (g_atomic_int_dec_and_test (&_data8_->_ref_count_)) {
#line 440 "window.c"
		ClocksWindow* self;
#line 55 "../src/window.vala"
		self = _data8_->self;
#line 55 "../src/window.vala"
		_g_object_unref0 (_data8_->timer);
#line 55 "../src/window.vala"
		_g_object_unref0 (_data8_->stopwatch);
#line 55 "../src/window.vala"
		_g_object_unref0 (_data8_->world);
#line 55 "../src/window.vala"
		_g_object_unref0 (self);
#line 55 "../src/window.vala"
		g_slice_free (Block8Data, _data8_);
#line 454 "window.c"
	}
}

static void
__lambda9_ (ClocksWindow* self)
{
	GSettings* _tmp0_;
#line 64 "../src/window.vala"
	_tmp0_ = self->priv->settings;
#line 64 "../src/window.vala"
	g_settings_apply (_tmp0_);
#line 466 "window.c"
}

static void
___lambda9__gtk_widget_destroy (GtkWidget* _sender,
                                gpointer self)
{
#line 63 "../src/window.vala"
	__lambda9_ ((ClocksWindow*) self);
#line 475 "window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 85 "../src/window.vala"
	return self ? g_object_ref (self) : NULL;
#line 483 "window.c"
}

static void
____lambda51_ (ClocksWindow* self)
{
#line 94 "../src/window.vala"
	clocks_window_update_header_bar (self);
#line 491 "window.c"
}

static void
_____lambda51__clocks_clock_request_header_bar_update (ClocksClock* _sender,
                                                       gpointer self)
{
#line 93 "../src/window.vala"
	____lambda51_ ((ClocksWindow*) self);
#line 500 "window.c"
}

static void
__lambda52_ (ClocksWindow* self)
{
	GtkShortcutsWindow* help_overlay = NULL;
	GtkShortcutsWindow* _tmp0_;
	GtkShortcutsWindow* _tmp1_;
	GtkStack* _tmp2_;
	GtkWidget* _tmp3_;
	GtkWidget* _tmp4_;
	const gchar* _tmp5_;
#line 99 "../src/window.vala"
	_tmp0_ = gtk_application_window_get_help_overlay ((GtkApplicationWindow*) self);
#line 99 "../src/window.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 99 "../src/window.vala"
	help_overlay = _tmp1_;
#line 100 "../src/window.vala"
	_tmp2_ = self->priv->stack;
#line 100 "../src/window.vala"
	_tmp3_ = gtk_stack_get_visible_child (_tmp2_);
#line 100 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 100 "../src/window.vala"
	_tmp5_ = g_type_name (G_TYPE_FROM_INSTANCE (_tmp4_));
#line 100 "../src/window.vala"
	g_object_set (help_overlay, "view-name", _tmp5_, NULL);
#line 101 "../src/window.vala"
	clocks_window_update_header_bar (self);
#line 98 "../src/window.vala"
	_g_object_unref0 (help_overlay);
#line 533 "window.c"
}

static void
___lambda52__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 98 "../src/window.vala"
	__lambda52_ ((ClocksWindow*) self);
#line 543 "window.c"
}

static void
__lambda53_ (ClocksWindow* self)
{
#line 105 "../src/window.vala"
	clocks_window_update_header_bar (self);
#line 551 "window.c"
}

static void
___lambda53__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 104 "../src/window.vala"
	__lambda53_ ((ClocksWindow*) self);
#line 561 "window.c"
}

static void
__lambda54_ (ClocksWindow* self,
             GtkWidget* widget,
             GtkAllocation* allocation)
{
	GtkAllocation _tmp0_;
#line 107 "../src/window.vala"
	g_return_if_fail (widget != NULL);
#line 107 "../src/window.vala"
	g_return_if_fail (allocation != NULL);
#line 108 "../src/window.vala"
	_tmp0_ = *allocation;
#line 108 "../src/window.vala"
	if (_tmp0_.width > 500) {
#line 578 "window.c"
		HdyViewSwitcherBar* _tmp1_;
#line 109 "../src/window.vala"
		_tmp1_ = self->priv->switcher_bar;
#line 109 "../src/window.vala"
		hdy_view_switcher_bar_set_reveal (_tmp1_, FALSE);
#line 584 "window.c"
	} else {
		HdyViewSwitcherBar* _tmp2_;
#line 111 "../src/window.vala"
		_tmp2_ = self->priv->switcher_bar;
#line 111 "../src/window.vala"
		hdy_view_switcher_bar_set_reveal (_tmp2_, TRUE);
#line 591 "window.c"
	}
}

static void
___lambda54__gtk_widget_size_allocate (GtkWidget* _sender,
                                       GtkAllocation* allocation,
                                       gpointer self)
{
#line 107 "../src/window.vala"
	__lambda54_ ((ClocksWindow*) self, _sender, allocation);
#line 602 "window.c"
}

static void
__lambda55_ (Block8Data* _data8_)
{
	ClocksWindow* self;
	ClocksHeaderBar* _tmp0_;
	GtkStack* _tmp1_;
#line 115 "../src/window.vala"
	self = _data8_->self;
#line 116 "../src/window.vala"
	_tmp0_ = self->priv->header_bar;
#line 116 "../src/window.vala"
	g_signal_handler_disconnect ((GObject*) _tmp0_, _data8_->header_bar_id);
#line 117 "../src/window.vala"
	_data8_->header_bar_id = (gulong) 0;
#line 118 "../src/window.vala"
	_tmp1_ = self->priv->stack;
#line 118 "../src/window.vala"
	g_signal_handler_disconnect ((GObject*) _tmp1_, _data8_->stack_id);
#line 119 "../src/window.vala"
	_data8_->stack_id = (gulong) 0;
#line 625 "window.c"
}

static void
___lambda55__gtk_widget_destroy (GtkWidget* _sender,
                                 gpointer self)
{
#line 115 "../src/window.vala"
	__lambda55_ (self);
#line 634 "window.c"
}

static void
__lambda56_ (Block8Data* _data8_,
             ClocksAlarmFace* w)
{
	ClocksWindow* self;
	ClocksWorldFace* _tmp0_;
	GtkStack* _tmp1_;
#line 122 "../src/window.vala"
	self = _data8_->self;
#line 122 "../src/window.vala"
	g_return_if_fail (w != NULL);
#line 123 "../src/window.vala"
	_tmp0_ = _data8_->world;
#line 123 "../src/window.vala"
	clocks_world_face_reset_view (_tmp0_);
#line 124 "../src/window.vala"
	_tmp1_ = self->priv->stack;
#line 124 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp1_, (GtkWidget*) w);
#line 656 "window.c"
}

static void
___lambda56__clocks_alarm_face_ring (ClocksAlarmFace* _sender,
                                     gpointer self)
{
#line 122 "../src/window.vala"
	__lambda56_ (self, _sender);
#line 665 "window.c"
}

static void
__lambda57_ (Block8Data* _data8_,
             GParamSpec* w)
{
	ClocksWindow* self;
	GtkStack* _tmp0_;
	ClocksStopwatchFace* _tmp1_;
	ClocksStopwatchFace* _tmp2_;
	ClocksStopwatchFaceState _tmp3_;
	ClocksStopwatchFaceState _tmp4_;
	GValue _tmp5_ = {0};
#line 127 "../src/window.vala"
	self = _data8_->self;
#line 127 "../src/window.vala"
	g_return_if_fail (w != NULL);
#line 128 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 128 "../src/window.vala"
	_tmp1_ = _data8_->stopwatch;
#line 128 "../src/window.vala"
	_tmp2_ = _data8_->stopwatch;
#line 128 "../src/window.vala"
	_tmp3_ = clocks_stopwatch_face_get_state (_tmp2_);
#line 128 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 128 "../src/window.vala"
	g_value_init (&_tmp5_, G_TYPE_BOOLEAN);
#line 128 "../src/window.vala"
	g_value_set_boolean (&_tmp5_, _tmp4_ == CLOCKS_STOPWATCH_FACE_STATE_RUNNING);
#line 128 "../src/window.vala"
	gtk_container_child_set_property ((GtkContainer*) _tmp0_, (GtkWidget*) _tmp1_, "needs-attention", &_tmp5_);
#line 128 "../src/window.vala"
	G_IS_VALUE (&_tmp5_) ? (g_value_unset (&_tmp5_), NULL) : NULL;
#line 701 "window.c"
}

static void
___lambda57__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 127 "../src/window.vala"
	__lambda57_ (self, pspec);
#line 711 "window.c"
}

static void
__lambda58_ (Block8Data* _data8_,
             ClocksTimerFace* w)
{
	ClocksWindow* self;
	ClocksWorldFace* _tmp0_;
	GtkStack* _tmp1_;
#line 131 "../src/window.vala"
	self = _data8_->self;
#line 131 "../src/window.vala"
	g_return_if_fail (w != NULL);
#line 132 "../src/window.vala"
	_tmp0_ = _data8_->world;
#line 132 "../src/window.vala"
	clocks_world_face_reset_view (_tmp0_);
#line 133 "../src/window.vala"
	_tmp1_ = self->priv->stack;
#line 133 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp1_, (GtkWidget*) w);
#line 733 "window.c"
}

static void
___lambda58__clocks_timer_face_ring (ClocksTimerFace* _sender,
                                     gpointer self)
{
#line 131 "../src/window.vala"
	__lambda58_ (self, _sender);
#line 742 "window.c"
}

static void
__lambda59_ (Block8Data* _data8_,
             GParamSpec* w)
{
	ClocksWindow* self;
	GtkStack* _tmp0_;
	ClocksTimerFace* _tmp1_;
	ClocksTimerFace* _tmp2_;
	ClocksTimerFaceState _tmp3_;
	ClocksTimerFaceState _tmp4_;
	GValue _tmp5_ = {0};
#line 136 "../src/window.vala"
	self = _data8_->self;
#line 136 "../src/window.vala"
	g_return_if_fail (w != NULL);
#line 137 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 137 "../src/window.vala"
	_tmp1_ = _data8_->timer;
#line 137 "../src/window.vala"
	_tmp2_ = _data8_->timer;
#line 137 "../src/window.vala"
	_tmp3_ = clocks_timer_face_get_state (_tmp2_);
#line 137 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 137 "../src/window.vala"
	g_value_init (&_tmp5_, G_TYPE_BOOLEAN);
#line 137 "../src/window.vala"
	g_value_set_boolean (&_tmp5_, _tmp4_ == CLOCKS_TIMER_FACE_STATE_RUNNING);
#line 137 "../src/window.vala"
	gtk_container_child_set_property ((GtkContainer*) _tmp0_, (GtkWidget*) _tmp1_, "needs-attention", &_tmp5_);
#line 137 "../src/window.vala"
	G_IS_VALUE (&_tmp5_) ? (g_value_unset (&_tmp5_), NULL) : NULL;
#line 778 "window.c"
}

static void
___lambda59__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 136 "../src/window.vala"
	__lambda59_ (self, pspec);
#line 788 "window.c"
}

ClocksWindow*
clocks_window_construct (GType object_type,
                         ClocksApplication* app)
{
	ClocksWindow * self = NULL;
	Block8Data* _data8_;
	GSettings* _tmp0_;
	GSettings* _tmp1_;
	GdkWindowState window_state = 0U;
	GSettings* _tmp2_;
	GdkWindowState _tmp3_;
	gint width = 0;
	gint height = 0;
	GSettings* _tmp4_;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	GtkWidget** _tmp7_;
	GtkWidget** _tmp8_;
	gint _tmp8__length1;
	ClocksHeaderBar* _tmp9_;
	ClocksWorldFace* _tmp10_;
	GtkWidget** _tmp11_;
	gint _tmp11__length1;
	ClocksHeaderBar* _tmp12_;
	ClocksAlarmFace* _tmp13_;
	GtkWidget** _tmp14_;
	gint _tmp14__length1;
	ClocksHeaderBar* _tmp15_;
	ClocksStopwatchFace* _tmp16_;
	GtkWidget** _tmp17_;
	gint _tmp17__length1;
	ClocksHeaderBar* _tmp18_;
	ClocksTimerFace* _tmp19_;
	GtkWidget** _tmp20_;
	gint _tmp20__length1;
	GtkWidget* _tmp21_;
	ClocksWorldFace* _tmp22_;
	ClocksAlarmFace* alarm = NULL;
	GtkWidget** _tmp23_;
	gint _tmp23__length1;
	GtkWidget* _tmp24_;
	ClocksAlarmFace* _tmp25_;
	GtkWidget** _tmp26_;
	gint _tmp26__length1;
	GtkWidget* _tmp27_;
	ClocksStopwatchFace* _tmp28_;
	GtkWidget** _tmp29_;
	gint _tmp29__length1;
	GtkWidget* _tmp30_;
	ClocksTimerFace* _tmp31_;
	GtkWidget** _tmp32_;
	gint _tmp32__length1;
	GtkStack* _tmp49_;
	gulong _tmp50_;
	ClocksHeaderBar* _tmp51_;
	gulong _tmp52_;
	GtkStack* _tmp53_;
	ClocksAlarmFace* _tmp54_;
	ClocksStopwatchFace* _tmp55_;
	ClocksTimerFace* _tmp56_;
	ClocksTimerFace* _tmp57_;
	GtkBindingSet* binding_set = NULL;
	GObjectClass* _tmp58_;
	GtkBindingSet* _tmp59_;
	GtkBindingSet* _tmp60_;
	GtkBindingSet* _tmp61_;
	GtkStack* _tmp62_;
	GtkWidget** _tmp63_;
	gint _tmp63__length1;
	GSettings* _tmp64_;
	GtkWidget* _tmp65_;
	GtkStyleContext* style = NULL;
	GtkStyleContext* _tmp66_;
	GtkStyleContext* _tmp67_;
#line 55 "../src/window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 55 "../src/window.vala"
	_data8_ = g_slice_new0 (Block8Data);
#line 55 "../src/window.vala"
	_data8_->_ref_count_ = 1;
#line 56 "../src/window.vala"
	self = (ClocksWindow*) g_object_new (object_type, "application", app, NULL);
#line 56 "../src/window.vala"
	_data8_->self = g_object_ref (self);
#line 58 "../src/window.vala"
	g_action_map_add_action_entries ((GActionMap*) self, CLOCKS_WINDOW_action_entries, (gint) G_N_ELEMENTS (CLOCKS_WINDOW_action_entries), self);
#line 60 "../src/window.vala"
	_tmp0_ = g_settings_new ("org.gnome.clocks.state.window");
#line 60 "../src/window.vala"
	_g_object_unref0 (self->priv->settings);
#line 60 "../src/window.vala"
	self->priv->settings = _tmp0_;
#line 61 "../src/window.vala"
	_tmp1_ = self->priv->settings;
#line 61 "../src/window.vala"
	g_settings_delay (_tmp1_);
#line 63 "../src/window.vala"
	g_signal_connect_object ((GtkWidget*) self, "destroy", (GCallback) ___lambda9__gtk_widget_destroy, self, 0);
#line 68 "../src/window.vala"
	_tmp2_ = self->priv->settings;
#line 68 "../src/window.vala"
	window_state = (GdkWindowState) g_settings_get_int (_tmp2_, "state");
#line 69 "../src/window.vala"
	_tmp3_ = window_state;
#line 69 "../src/window.vala"
	if ((_tmp3_ & GDK_WINDOW_STATE_MAXIMIZED) == GDK_WINDOW_STATE_MAXIMIZED) {
#line 70 "../src/window.vala"
		gtk_window_maximize ((GtkWindow*) self);
#line 899 "window.c"
	}
#line 74 "../src/window.vala"
	_tmp4_ = self->priv->settings;
#line 74 "../src/window.vala"
	g_settings_get (_tmp4_, "size", "(ii)", &_tmp5_, &_tmp6_);
#line 74 "../src/window.vala"
	width = _tmp5_;
#line 74 "../src/window.vala"
	height = _tmp6_;
#line 75 "../src/window.vala"
	gtk_window_resize ((GtkWindow*) self, width, height);
#line 76 "../src/window.vala"
	gtk_window_set_title ((GtkWindow*) self, _ ("Clocks"));
#line 78 "../src/window.vala"
	_tmp7_ = g_new0 (GtkWidget*, CLOCKS_N_PANELS + 1);
#line 78 "../src/window.vala"
	self->priv->panels = (_vala_array_free (self->priv->panels, self->priv->panels_length1, (GDestroyNotify) g_object_unref), NULL);
#line 78 "../src/window.vala"
	self->priv->panels = _tmp7_;
#line 78 "../src/window.vala"
	self->priv->panels_length1 = CLOCKS_N_PANELS;
#line 78 "../src/window.vala"
	self->priv->_panels_size_ = self->priv->panels_length1;
#line 80 "../src/window.vala"
	_tmp8_ = self->priv->panels;
#line 80 "../src/window.vala"
	_tmp8__length1 = self->priv->panels_length1;
#line 80 "../src/window.vala"
	_tmp9_ = self->priv->header_bar;
#line 80 "../src/window.vala"
	_tmp10_ = clocks_world_face_new (_tmp9_);
#line 80 "../src/window.vala"
	g_object_ref_sink (_tmp10_);
#line 80 "../src/window.vala"
	_g_object_unref0 (_tmp8_[CLOCKS_PANEL_ID_WORLD]);
#line 80 "../src/window.vala"
	_tmp8_[CLOCKS_PANEL_ID_WORLD] = (GtkWidget*) _tmp10_;
#line 81 "../src/window.vala"
	_tmp11_ = self->priv->panels;
#line 81 "../src/window.vala"
	_tmp11__length1 = self->priv->panels_length1;
#line 81 "../src/window.vala"
	_tmp12_ = self->priv->header_bar;
#line 81 "../src/window.vala"
	_tmp13_ = clocks_alarm_face_new (_tmp12_);
#line 81 "../src/window.vala"
	g_object_ref_sink (_tmp13_);
#line 81 "../src/window.vala"
	_g_object_unref0 (_tmp11_[CLOCKS_PANEL_ID_ALARM]);
#line 81 "../src/window.vala"
	_tmp11_[CLOCKS_PANEL_ID_ALARM] = (GtkWidget*) _tmp13_;
#line 82 "../src/window.vala"
	_tmp14_ = self->priv->panels;
#line 82 "../src/window.vala"
	_tmp14__length1 = self->priv->panels_length1;
#line 82 "../src/window.vala"
	_tmp15_ = self->priv->header_bar;
#line 82 "../src/window.vala"
	_tmp16_ = clocks_stopwatch_face_new (_tmp15_);
#line 82 "../src/window.vala"
	g_object_ref_sink (_tmp16_);
#line 82 "../src/window.vala"
	_g_object_unref0 (_tmp14_[CLOCKS_PANEL_ID_STOPWATCH]);
#line 82 "../src/window.vala"
	_tmp14_[CLOCKS_PANEL_ID_STOPWATCH] = (GtkWidget*) _tmp16_;
#line 83 "../src/window.vala"
	_tmp17_ = self->priv->panels;
#line 83 "../src/window.vala"
	_tmp17__length1 = self->priv->panels_length1;
#line 83 "../src/window.vala"
	_tmp18_ = self->priv->header_bar;
#line 83 "../src/window.vala"
	_tmp19_ = clocks_timer_face_new (_tmp18_);
#line 83 "../src/window.vala"
	g_object_ref_sink (_tmp19_);
#line 83 "../src/window.vala"
	_g_object_unref0 (_tmp17_[CLOCKS_PANEL_ID_TIMER]);
#line 83 "../src/window.vala"
	_tmp17_[CLOCKS_PANEL_ID_TIMER] = (GtkWidget*) _tmp19_;
#line 85 "../src/window.vala"
	_tmp20_ = self->priv->panels;
#line 85 "../src/window.vala"
	_tmp20__length1 = self->priv->panels_length1;
#line 85 "../src/window.vala"
	_tmp21_ = _tmp20_[CLOCKS_PANEL_ID_WORLD];
#line 85 "../src/window.vala"
	_tmp22_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp21_, CLOCKS_WORLD_TYPE_FACE, ClocksWorldFace));
#line 85 "../src/window.vala"
	_data8_->world = _tmp22_;
#line 86 "../src/window.vala"
	_tmp23_ = self->priv->panels;
#line 86 "../src/window.vala"
	_tmp23__length1 = self->priv->panels_length1;
#line 86 "../src/window.vala"
	_tmp24_ = _tmp23_[CLOCKS_PANEL_ID_ALARM];
#line 86 "../src/window.vala"
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp24_, CLOCKS_ALARM_TYPE_FACE, ClocksAlarmFace));
#line 86 "../src/window.vala"
	alarm = _tmp25_;
#line 87 "../src/window.vala"
	_tmp26_ = self->priv->panels;
#line 87 "../src/window.vala"
	_tmp26__length1 = self->priv->panels_length1;
#line 87 "../src/window.vala"
	_tmp27_ = _tmp26_[CLOCKS_PANEL_ID_STOPWATCH];
#line 87 "../src/window.vala"
	_tmp28_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp27_, CLOCKS_STOPWATCH_TYPE_FACE, ClocksStopwatchFace));
#line 87 "../src/window.vala"
	_data8_->stopwatch = _tmp28_;
#line 88 "../src/window.vala"
	_tmp29_ = self->priv->panels;
#line 88 "../src/window.vala"
	_tmp29__length1 = self->priv->panels_length1;
#line 88 "../src/window.vala"
	_tmp30_ = _tmp29_[CLOCKS_PANEL_ID_TIMER];
#line 88 "../src/window.vala"
	_tmp31_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp30_, CLOCKS_TIMER_TYPE_FACE, ClocksTimerFace));
#line 88 "../src/window.vala"
	_data8_->timer = _tmp31_;
#line 90 "../src/window.vala"
	_tmp32_ = self->priv->panels;
#line 90 "../src/window.vala"
	_tmp32__length1 = self->priv->panels_length1;
#line 1023 "window.c"
	{
		GtkWidget** clock_collection = NULL;
		gint clock_collection_length1 = 0;
		gint _clock_collection_size_ = 0;
		gint clock_it = 0;
#line 90 "../src/window.vala"
		clock_collection = _tmp32_;
#line 90 "../src/window.vala"
		clock_collection_length1 = _tmp32__length1;
#line 90 "../src/window.vala"
		for (clock_it = 0; clock_it < clock_collection_length1; clock_it = clock_it + 1) {
#line 1035 "window.c"
			GtkWidget* _tmp33_;
			GtkWidget* clock = NULL;
#line 90 "../src/window.vala"
			_tmp33_ = _g_object_ref0 (clock_collection[clock_it]);
#line 90 "../src/window.vala"
			clock = _tmp33_;
#line 1042 "window.c"
			{
				GtkStack* _tmp34_;
				GtkWidget* _tmp35_;
				GtkWidget* _tmp36_;
				const gchar* _tmp37_;
				const gchar* _tmp38_;
				GtkWidget* _tmp39_;
				const gchar* _tmp40_;
				const gchar* _tmp41_;
				GtkStack* _tmp42_;
				GtkWidget* _tmp43_;
				GtkWidget* _tmp44_;
				const gchar* _tmp45_;
				const gchar* _tmp46_;
				GValue _tmp47_ = {0};
				GtkWidget* _tmp48_;
#line 91 "../src/window.vala"
				_tmp34_ = self->priv->stack;
#line 91 "../src/window.vala"
				_tmp35_ = clock;
#line 91 "../src/window.vala"
				_tmp36_ = clock;
#line 91 "../src/window.vala"
				_tmp37_ = clocks_clock_get_label (G_TYPE_CHECK_INSTANCE_CAST (_tmp36_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 91 "../src/window.vala"
				_tmp38_ = _tmp37_;
#line 91 "../src/window.vala"
				_tmp39_ = clock;
#line 91 "../src/window.vala"
				_tmp40_ = clocks_clock_get_label (G_TYPE_CHECK_INSTANCE_CAST (_tmp39_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 91 "../src/window.vala"
				_tmp41_ = _tmp40_;
#line 91 "../src/window.vala"
				gtk_stack_add_titled (_tmp34_, _tmp35_, _tmp38_, _tmp41_);
#line 92 "../src/window.vala"
				_tmp42_ = self->priv->stack;
#line 92 "../src/window.vala"
				_tmp43_ = clock;
#line 92 "../src/window.vala"
				_tmp44_ = clock;
#line 92 "../src/window.vala"
				_tmp45_ = clocks_clock_get_icon_name (G_TYPE_CHECK_INSTANCE_CAST (_tmp44_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 92 "../src/window.vala"
				_tmp46_ = _tmp45_;
#line 92 "../src/window.vala"
				g_value_init (&_tmp47_, G_TYPE_STRING);
#line 92 "../src/window.vala"
				g_value_set_string (&_tmp47_, _tmp46_);
#line 92 "../src/window.vala"
				gtk_container_child_set_property ((GtkContainer*) _tmp42_, _tmp43_, "icon-name", &_tmp47_);
#line 92 "../src/window.vala"
				G_IS_VALUE (&_tmp47_) ? (g_value_unset (&_tmp47_), NULL) : NULL;
#line 93 "../src/window.vala"
				_tmp48_ = clock;
#line 93 "../src/window.vala"
				g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp48_, CLOCKS_TYPE_CLOCK, ClocksClock), "request-header-bar-update", (GCallback) _____lambda51__clocks_clock_request_header_bar_update, self, 0);
#line 90 "../src/window.vala"
				_g_object_unref0 (clock);
#line 1101 "window.c"
			}
		}
	}
#line 98 "../src/window.vala"
	_tmp49_ = self->priv->stack;
#line 98 "../src/window.vala"
	_tmp50_ = g_signal_connect_object ((GObject*) _tmp49_, "notify::visible-child", (GCallback) ___lambda52__g_object_notify, self, 0);
#line 98 "../src/window.vala"
	_data8_->stack_id = _tmp50_;
#line 104 "../src/window.vala"
	_tmp51_ = self->priv->header_bar;
#line 104 "../src/window.vala"
	_tmp52_ = g_signal_connect_object ((GObject*) _tmp51_, "notify::mode", (GCallback) ___lambda53__g_object_notify, self, 0);
#line 104 "../src/window.vala"
	_data8_->header_bar_id = _tmp52_;
#line 107 "../src/window.vala"
	g_signal_connect_object ((GtkWidget*) self, "size-allocate", (GCallback) ___lambda54__gtk_widget_size_allocate, self, 0);
#line 115 "../src/window.vala"
	_tmp53_ = self->priv->stack;
#line 115 "../src/window.vala"
	g_signal_connect_data ((GtkWidget*) _tmp53_, "destroy", (GCallback) ___lambda55__gtk_widget_destroy, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
#line 122 "../src/window.vala"
	_tmp54_ = alarm;
#line 122 "../src/window.vala"
	g_signal_connect_data (_tmp54_, "ring", (GCallback) ___lambda56__clocks_alarm_face_ring, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
#line 127 "../src/window.vala"
	_tmp55_ = _data8_->stopwatch;
#line 127 "../src/window.vala"
	g_signal_connect_data ((GObject*) _tmp55_, "notify::state", (GCallback) ___lambda57__g_object_notify, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
#line 131 "../src/window.vala"
	_tmp56_ = _data8_->timer;
#line 131 "../src/window.vala"
	g_signal_connect_data (_tmp56_, "ring", (GCallback) ___lambda58__clocks_timer_face_ring, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
#line 136 "../src/window.vala"
	_tmp57_ = _data8_->timer;
#line 136 "../src/window.vala"
	g_signal_connect_data ((GObject*) _tmp57_, "notify::state", (GCallback) ___lambda59__g_object_notify, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
#line 140 "../src/window.vala"
	_tmp58_ = G_OBJECT_GET_CLASS ((GObject*) self);
#line 140 "../src/window.vala"
	_tmp59_ = gtk_binding_set_by_class ((gpointer) _tmp58_);
#line 140 "../src/window.vala"
	binding_set = _tmp59_;
#line 143 "../src/window.vala"
	_tmp60_ = binding_set;
#line 143 "../src/window.vala"
	gtk_binding_entry_add_signal (_tmp60_, GDK_KEY_Page_Up, GDK_CONTROL_MASK | GDK_MOD1_MASK, "change-page", (guint) 1, G_TYPE_INT, -1, NULL);
#line 148 "../src/window.vala"
	_tmp61_ = binding_set;
#line 148 "../src/window.vala"
	gtk_binding_entry_add_signal (_tmp61_, GDK_KEY_Page_Down, GDK_CONTROL_MASK | GDK_MOD1_MASK, "change-page", (guint) 1, G_TYPE_INT, 1, NULL);
#line 154 "../src/window.vala"
	_tmp62_ = self->priv->stack;
#line 154 "../src/window.vala"
	_tmp63_ = self->priv->panels;
#line 154 "../src/window.vala"
	_tmp63__length1 = self->priv->panels_length1;
#line 154 "../src/window.vala"
	_tmp64_ = self->priv->settings;
#line 154 "../src/window.vala"
	_tmp65_ = _tmp63_[g_settings_get_enum (_tmp64_, "panel-id")];
#line 154 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp62_, _tmp65_);
#line 156 "../src/window.vala"
	_tmp66_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 156 "../src/window.vala"
	_tmp67_ = _g_object_ref0 (_tmp66_);
#line 156 "../src/window.vala"
	style = _tmp67_;
#line 157 "../src/window.vala"
	if (g_strcmp0 (PROFILE, "Devel") == 0) {
#line 1173 "window.c"
		GtkStyleContext* _tmp68_;
#line 158 "../src/window.vala"
		_tmp68_ = style;
#line 158 "../src/window.vala"
		gtk_style_context_add_class (_tmp68_, "devel");
#line 1179 "window.c"
	}
#line 161 "../src/window.vala"
	clocks_window_update_header_bar (self);
#line 163 "../src/window.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 55 "../src/window.vala"
	_g_object_unref0 (style);
#line 55 "../src/window.vala"
	_g_object_unref0 (alarm);
#line 55 "../src/window.vala"
	block8_data_unref (_data8_);
#line 55 "../src/window.vala"
	_data8_ = NULL;
#line 55 "../src/window.vala"
	return self;
#line 1195 "window.c"
}

ClocksWindow*
clocks_window_new (ClocksApplication* app)
{
#line 55 "../src/window.vala"
	return clocks_window_construct (CLOCKS_TYPE_WINDOW, app);
#line 1203 "window.c"
}

static void
clocks_window_on_show_primary_menu_activate (ClocksWindow* self,
                                             GSimpleAction* action)
{
	gboolean state = FALSE;
	GVariant* _tmp0_;
	GVariant* _tmp1_;
	gboolean _tmp2_;
	GVariant* _tmp3_;
	GVariant* _tmp4_;
#line 179 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 179 "../src/window.vala"
	g_return_if_fail (action != NULL);
#line 180 "../src/window.vala"
	_tmp0_ = g_action_get_state ((GAction*) action);
#line 180 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 180 "../src/window.vala"
	_tmp2_ = g_variant_get_boolean (_tmp1_);
#line 180 "../src/window.vala"
	_g_variant_unref0 (_tmp1_);
#line 180 "../src/window.vala"
	state = _tmp2_;
#line 181 "../src/window.vala"
	_tmp3_ = g_variant_new_boolean (!state);
#line 181 "../src/window.vala"
	g_variant_ref_sink (_tmp3_);
#line 181 "../src/window.vala"
	_tmp4_ = _tmp3_;
#line 181 "../src/window.vala"
	g_simple_action_set_state (action, _tmp4_);
#line 181 "../src/window.vala"
	_g_variant_unref0 (_tmp4_);
#line 1240 "window.c"
}

static void
clocks_window_on_new_activate (ClocksWindow* self)
{
	GtkStack* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
#line 184 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 185 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 185 "../src/window.vala"
	_tmp1_ = gtk_stack_get_visible_child (_tmp0_);
#line 185 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 185 "../src/window.vala"
	clocks_clock_activate_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 1259 "window.c"
}

static void
clocks_window_on_select_all_activate (ClocksWindow* self)
{
	GtkStack* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
#line 188 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 189 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 189 "../src/window.vala"
	_tmp1_ = gtk_stack_get_visible_child (_tmp0_);
#line 189 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 189 "../src/window.vala"
	clocks_clock_activate_select_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 1278 "window.c"
}

static void
clocks_window_on_select_none_activate (ClocksWindow* self)
{
	GtkStack* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
#line 192 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 193 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 193 "../src/window.vala"
	_tmp1_ = gtk_stack_get_visible_child (_tmp0_);
#line 193 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 193 "../src/window.vala"
	clocks_clock_activate_select_none (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 1297 "window.c"
}

void
clocks_window_show_world (ClocksWindow* self)
{
	GtkWidget** _tmp0_;
	gint _tmp0__length1;
	GtkWidget* _tmp1_;
	GtkStack* _tmp2_;
	GtkWidget** _tmp3_;
	gint _tmp3__length1;
	GtkWidget* _tmp4_;
#line 196 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 197 "../src/window.vala"
	_tmp0_ = self->priv->panels;
#line 197 "../src/window.vala"
	_tmp0__length1 = self->priv->panels_length1;
#line 197 "../src/window.vala"
	_tmp1_ = _tmp0_[CLOCKS_PANEL_ID_WORLD];
#line 197 "../src/window.vala"
	clocks_world_face_reset_view (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, CLOCKS_WORLD_TYPE_FACE, ClocksWorldFace));
#line 198 "../src/window.vala"
	_tmp2_ = self->priv->stack;
#line 198 "../src/window.vala"
	_tmp3_ = self->priv->panels;
#line 198 "../src/window.vala"
	_tmp3__length1 = self->priv->panels_length1;
#line 198 "../src/window.vala"
	_tmp4_ = _tmp3_[CLOCKS_PANEL_ID_WORLD];
#line 198 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp2_, _tmp4_);
#line 1330 "window.c"
}

void
clocks_window_add_world_location (ClocksWindow* self,
                                  GWeatherLocation* location)
{
	GtkWidget** _tmp0_;
	gint _tmp0__length1;
	GtkWidget* _tmp1_;
#line 201 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 201 "../src/window.vala"
	g_return_if_fail (location != NULL);
#line 202 "../src/window.vala"
	_tmp0_ = self->priv->panels;
#line 202 "../src/window.vala"
	_tmp0__length1 = self->priv->panels_length1;
#line 202 "../src/window.vala"
	_tmp1_ = _tmp0_[CLOCKS_PANEL_ID_WORLD];
#line 202 "../src/window.vala"
	clocks_world_face_add_location (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, CLOCKS_WORLD_TYPE_FACE, ClocksWorldFace), location);
#line 1352 "window.c"
}

static gboolean
clocks_window_real_key_press_event (GtkWidget* base,
                                    GdkEventKey* event)
{
	ClocksWindow * self;
	guint keyval = 0U;
	gboolean handled = FALSE;
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
	gboolean _tmp2_;
	gboolean result = FALSE;
#line 205 "../src/window.vala"
	self = (ClocksWindow*) base;
#line 205 "../src/window.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 207 "../src/window.vala"
	handled = FALSE;
#line 209 "../src/window.vala"
	_tmp2_ = gdk_event_get_keyval ((GdkEvent*) event, &_tmp1_);
#line 209 "../src/window.vala"
	keyval = _tmp1_;
#line 209 "../src/window.vala"
	if (_tmp2_) {
#line 209 "../src/window.vala"
		_tmp0_ = keyval == GDK_KEY_Escape;
#line 1380 "window.c"
	} else {
#line 209 "../src/window.vala"
		_tmp0_ = FALSE;
#line 1384 "window.c"
	}
#line 209 "../src/window.vala"
	if (_tmp0_) {
#line 1388 "window.c"
		GtkStack* _tmp3_;
		GtkWidget* _tmp4_;
		GtkWidget* _tmp5_;
#line 210 "../src/window.vala"
		_tmp3_ = self->priv->stack;
#line 210 "../src/window.vala"
		_tmp4_ = gtk_stack_get_visible_child (_tmp3_);
#line 210 "../src/window.vala"
		_tmp5_ = _tmp4_;
#line 210 "../src/window.vala"
		handled = clocks_clock_escape_pressed (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 1400 "window.c"
	}
#line 213 "../src/window.vala"
	if (handled) {
#line 214 "../src/window.vala"
		result = TRUE;
#line 214 "../src/window.vala"
		return result;
#line 1408 "window.c"
	}
#line 217 "../src/window.vala"
	result = GTK_WIDGET_CLASS (clocks_window_parent_class)->key_press_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_window_get_type (), GtkApplicationWindow), event);
#line 217 "../src/window.vala"
	return result;
#line 1414 "window.c"
}

static gboolean
clocks_window_real_button_release_event (GtkWidget* base,
                                         GdkEventButton* event)
{
	ClocksWindow * self;
#line 221 "../src/window.vala"
	static const guint BUTTON_BACK = (guint) 8;
#line 1424 "window.c"
	guint button = 0U;
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
	gboolean _tmp2_;
	gboolean result = FALSE;
#line 220 "../src/window.vala"
	self = (ClocksWindow*) base;
#line 220 "../src/window.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 224 "../src/window.vala"
	_tmp2_ = gdk_event_get_button ((GdkEvent*) event, &_tmp1_);
#line 224 "../src/window.vala"
	button = _tmp1_;
#line 224 "../src/window.vala"
	if (_tmp2_) {
#line 224 "../src/window.vala"
		_tmp0_ = button == BUTTON_BACK;
#line 1442 "window.c"
	} else {
#line 224 "../src/window.vala"
		_tmp0_ = FALSE;
#line 1446 "window.c"
	}
#line 224 "../src/window.vala"
	if (_tmp0_) {
#line 1450 "window.c"
		GtkStack* _tmp3_;
		GtkWidget* _tmp4_;
		GtkWidget* _tmp5_;
#line 225 "../src/window.vala"
		_tmp3_ = self->priv->stack;
#line 225 "../src/window.vala"
		_tmp4_ = gtk_stack_get_visible_child (_tmp3_);
#line 225 "../src/window.vala"
		_tmp5_ = _tmp4_;
#line 225 "../src/window.vala"
		clocks_clock_back (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 226 "../src/window.vala"
		result = TRUE;
#line 226 "../src/window.vala"
		return result;
#line 1466 "window.c"
	}
#line 229 "../src/window.vala"
	result = GTK_WIDGET_CLASS (clocks_window_parent_class)->button_release_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_window_get_type (), GtkApplicationWindow), event);
#line 229 "../src/window.vala"
	return result;
#line 1472 "window.c"
}

static gboolean
clocks_window_real_configure_event (GtkWidget* base,
                                    GdkEventConfigure* event)
{
	ClocksWindow * self;
	gboolean _tmp0_ = FALSE;
	gboolean result = FALSE;
#line 232 "../src/window.vala"
	self = (ClocksWindow*) base;
#line 232 "../src/window.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 233 "../src/window.vala"
	if (gtk_widget_get_realized ((GtkWidget*) self)) {
#line 1488 "window.c"
		GdkWindow* _tmp1_;
#line 233 "../src/window.vala"
		_tmp1_ = gtk_widget_get_window ((GtkWidget*) self);
#line 233 "../src/window.vala"
		_tmp0_ = !((gdk_window_get_state (_tmp1_) & GDK_WINDOW_STATE_MAXIMIZED) == GDK_WINDOW_STATE_MAXIMIZED);
#line 1494 "window.c"
	} else {
#line 233 "../src/window.vala"
		_tmp0_ = FALSE;
#line 1498 "window.c"
	}
#line 233 "../src/window.vala"
	if (_tmp0_) {
#line 1502 "window.c"
		gint width = 0;
		gint height = 0;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		GSettings* _tmp4_;
#line 236 "../src/window.vala"
		gtk_window_get_size ((GtkWindow*) self, &_tmp2_, &_tmp3_);
#line 236 "../src/window.vala"
		width = _tmp2_;
#line 236 "../src/window.vala"
		height = _tmp3_;
#line 237 "../src/window.vala"
		_tmp4_ = self->priv->settings;
#line 237 "../src/window.vala"
		g_settings_set (_tmp4_, "size", "(ii)", width, height);
#line 1518 "window.c"
	}
#line 240 "../src/window.vala"
	result = GTK_WIDGET_CLASS (clocks_window_parent_class)->configure_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_window_get_type (), GtkApplicationWindow), event);
#line 240 "../src/window.vala"
	return result;
#line 1524 "window.c"
}

static gboolean
clocks_window_real_window_state_event (GtkWidget* base,
                                       GdkEventWindowState* event)
{
	ClocksWindow * self;
	GSettings* _tmp0_;
	GdkWindowState _tmp1_;
	gboolean result = FALSE;
#line 243 "../src/window.vala"
	self = (ClocksWindow*) base;
#line 243 "../src/window.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 244 "../src/window.vala"
	_tmp0_ = self->priv->settings;
#line 244 "../src/window.vala"
	_tmp1_ = event->new_window_state;
#line 244 "../src/window.vala"
	g_settings_set_int (_tmp0_, "state", (gint) _tmp1_);
#line 245 "../src/window.vala"
	result = GTK_WIDGET_CLASS (clocks_window_parent_class)->window_state_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_window_get_type (), GtkApplicationWindow), event);
#line 245 "../src/window.vala"
	return result;
#line 1549 "window.c"
}

static void
clocks_window_on_help_activate (ClocksWindow* self)
{
	GError* _inner_error0_ = NULL;
#line 248 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 1558 "window.c"
	{
		GdkScreen* _tmp0_;
#line 250 "../src/window.vala"
		_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
#line 250 "../src/window.vala"
		gtk_show_uri (_tmp0_, "help:gnome-clocks", gtk_get_current_event_time (), &_inner_error0_);
#line 250 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1567 "window.c"
			goto __catch10_g_error;
		}
	}
	goto __finally10;
	__catch10_g_error:
	{
		GError* e = NULL;
		GError* _tmp1_;
		const gchar* _tmp2_;
#line 249 "../src/window.vala"
		e = _inner_error0_;
#line 249 "../src/window.vala"
		_inner_error0_ = NULL;
#line 252 "../src/window.vala"
		_tmp1_ = e;
#line 252 "../src/window.vala"
		_tmp2_ = _tmp1_->message;
#line 252 "../src/window.vala"
		g_warning (_ ("Failed to show help: %s"), _tmp2_);
#line 249 "../src/window.vala"
		_g_error_free0 (e);
#line 1589 "window.c"
	}
	__finally10:
#line 249 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 249 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 249 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 249 "../src/window.vala"
		return;
#line 1600 "window.c"
	}
}

static void
clocks_window_on_about_activate (ClocksWindow* self)
{
#line 257 "../src/window.vala"
	static const char copyright[] = "Copyright \xc2\xa9 2011 Collabora Ltd.\n" "Copyright \xc2\xa9 2012-2013 Collabora Ltd., Seif Lotfy, Emily Gonyer\n" "Eslam Mostafa, Paolo Borelli, Volker Sobek\n";
#line 261 "../src/window.vala"
	static const gchar* authors[14] = {"Alex Anthony", "Paolo Borelli", "Allan Day", "Piotr Drąg", "Emily Gonyer", "Evgeny Bobkin", "Maël Lavault", "Seif Lotfy", "William Jon McCann", "Eslam Mostafa", "Bastien Nocera", "Volker Sobek", "Jakub Steiner", NULL};
#line 1611 "window.c"
	gchar* program_name = NULL;
	gchar* _tmp0_;
#line 256 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 278 "../src/window.vala"
	_tmp0_ = g_strconcat (NAME_PREFIX, _ ("Clocks"), NULL);
#line 278 "../src/window.vala"
	program_name = _tmp0_;
#line 279 "../src/window.vala"
	gtk_show_about_dialog ((GtkWindow*) self, "program-name", program_name, "logo-icon-name", APP_ID, "version", VERSION, "comments", _ ("Utilities to help you with the time."), "copyright", copyright, "authors", authors, "license-type", GTK_LICENSE_GPL_2_0, "wrap-license", FALSE, "translator-credits", _ ("translator-credits"), NULL, NULL);
#line 256 "../src/window.vala"
	_g_free0 (program_name);
#line 1624 "window.c"
}

static void
clocks_window_update_header_bar (ClocksWindow* self)
{
	ClocksClock* clock = NULL;
	GtkStack* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
	ClocksClock* _tmp3_;
	ClocksClock* _tmp4_;
	ClocksHeaderBar* _tmp11_;
	ClocksHeaderBarMode _tmp12_;
	ClocksHeaderBarMode _tmp13_;
	ClocksHeaderBar* _tmp15_;
	ClocksHeaderBar* _tmp16_;
	ClocksHeaderBarMode _tmp17_;
	ClocksHeaderBarMode _tmp18_;
#line 292 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 294 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 294 "../src/window.vala"
	_tmp1_ = gtk_stack_get_visible_child (_tmp0_);
#line 294 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 294 "../src/window.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, CLOCKS_TYPE_CLOCK, ClocksClock));
#line 294 "../src/window.vala"
	clock = _tmp3_;
#line 295 "../src/window.vala"
	_tmp4_ = clock;
#line 295 "../src/window.vala"
	if (_tmp4_ != NULL) {
#line 1659 "window.c"
		GSettings* _tmp5_;
		ClocksClock* _tmp6_;
		ClocksPanelId _tmp7_;
		ClocksPanelId _tmp8_;
		ClocksClock* _tmp9_;
		ClocksClock* _tmp10_;
#line 296 "../src/window.vala"
		_tmp5_ = self->priv->settings;
#line 296 "../src/window.vala"
		_tmp6_ = clock;
#line 296 "../src/window.vala"
		_tmp7_ = clocks_clock_get_panel_id (_tmp6_);
#line 296 "../src/window.vala"
		_tmp8_ = _tmp7_;
#line 296 "../src/window.vala"
		g_settings_set_enum (_tmp5_, "panel-id", (gint) _tmp8_);
#line 297 "../src/window.vala"
		_tmp9_ = clock;
#line 297 "../src/window.vala"
		clocks_clock_update_header_bar (_tmp9_);
#line 298 "../src/window.vala"
		_tmp10_ = clock;
#line 298 "../src/window.vala"
		gtk_widget_grab_focus (G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, gtk_widget_get_type (), GtkWidget));
#line 1684 "window.c"
	}
#line 301 "../src/window.vala"
	_tmp11_ = self->priv->header_bar;
#line 301 "../src/window.vala"
	_tmp12_ = clocks_header_bar_get_mode (_tmp11_);
#line 301 "../src/window.vala"
	_tmp13_ = _tmp12_;
#line 301 "../src/window.vala"
	if (_tmp13_ == CLOCKS_HEADER_BAR_MODE_NORMAL) {
#line 1694 "window.c"
		GtkMenuButton* _tmp14_;
#line 303 "../src/window.vala"
		_tmp14_ = self->priv->menu_button;
#line 303 "../src/window.vala"
		gtk_widget_show ((GtkWidget*) _tmp14_);
#line 1700 "window.c"
	}
#line 306 "../src/window.vala"
	_tmp15_ = self->priv->header_bar;
#line 306 "../src/window.vala"
	_tmp16_ = self->priv->header_bar;
#line 306 "../src/window.vala"
	_tmp17_ = clocks_header_bar_get_mode (_tmp16_);
#line 306 "../src/window.vala"
	_tmp18_ = _tmp17_;
#line 306 "../src/window.vala"
	gtk_header_bar_set_show_close_button ((GtkHeaderBar*) _tmp15_, _tmp18_ != CLOCKS_HEADER_BAR_MODE_SELECTION);
#line 292 "../src/window.vala"
	_g_object_unref0 (clock);
#line 1714 "window.c"
}

static void
clocks_window_real_change_page (ClocksWindow* self,
                                gint offset)
{
	gint page = 0;
	GtkStack* _tmp0_;
	GtkStack* _tmp1_;
	GtkWidget* _tmp2_;
	GtkWidget* _tmp3_;
	gint _tmp4_ = 0;
	gboolean _tmp5_ = FALSE;
#line 170 "../src/window.vala"
	_tmp0_ = self->priv->stack;
#line 170 "../src/window.vala"
	_tmp1_ = self->priv->stack;
#line 170 "../src/window.vala"
	_tmp2_ = gtk_stack_get_visible_child (_tmp1_);
#line 170 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 170 "../src/window.vala"
	gtk_container_child_get ((GtkContainer*) _tmp0_, _tmp3_, "position", &_tmp4_, NULL);
#line 170 "../src/window.vala"
	page = _tmp4_;
#line 171 "../src/window.vala"
	page += offset;
#line 172 "../src/window.vala"
	if (page >= 0) {
#line 1744 "window.c"
		GtkWidget** _tmp6_;
		gint _tmp6__length1;
#line 172 "../src/window.vala"
		_tmp6_ = self->priv->panels;
#line 172 "../src/window.vala"
		_tmp6__length1 = self->priv->panels_length1;
#line 172 "../src/window.vala"
		_tmp5_ = page < _tmp6__length1;
#line 1753 "window.c"
	} else {
#line 172 "../src/window.vala"
		_tmp5_ = FALSE;
#line 1757 "window.c"
	}
#line 172 "../src/window.vala"
	if (_tmp5_) {
#line 1761 "window.c"
		GtkStack* _tmp7_;
		GtkWidget** _tmp8_;
		gint _tmp8__length1;
		GtkWidget* _tmp9_;
#line 173 "../src/window.vala"
		_tmp7_ = self->priv->stack;
#line 173 "../src/window.vala"
		_tmp8_ = self->priv->panels;
#line 173 "../src/window.vala"
		_tmp8__length1 = self->priv->panels_length1;
#line 173 "../src/window.vala"
		_tmp9_ = _tmp8_[page];
#line 173 "../src/window.vala"
		gtk_stack_set_visible_child (_tmp7_, _tmp9_);
#line 1776 "window.c"
	} else {
		GtkStack* _tmp10_;
#line 175 "../src/window.vala"
		_tmp10_ = self->priv->stack;
#line 175 "../src/window.vala"
		gtk_widget_error_bell ((GtkWidget*) _tmp10_);
#line 1783 "window.c"
	}
}

static void
clocks_window_class_init (ClocksWindowClass * klass,
                          gpointer klass_data)
{
#line 22 "../src/window.vala"
	clocks_window_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/window.vala"
	g_type_class_adjust_private_offset (klass, &ClocksWindow_private_offset);
#line 22 "../src/window.vala"
	((GtkWidgetClass *) klass)->key_press_event = (gboolean (*) (GtkWidget*, GdkEventKey*)) clocks_window_real_key_press_event;
#line 22 "../src/window.vala"
	((GtkWidgetClass *) klass)->button_release_event = (gboolean (*) (GtkWidget*, GdkEventButton*)) clocks_window_real_button_release_event;
#line 22 "../src/window.vala"
	((GtkWidgetClass *) klass)->configure_event = (gboolean (*) (GtkWidget*, GdkEventConfigure*)) clocks_window_real_configure_event;
#line 22 "../src/window.vala"
	((GtkWidgetClass *) klass)->window_state_event = (gboolean (*) (GtkWidget*, GdkEventWindowState*)) clocks_window_real_window_state_event;
#line 22 "../src/window.vala"
	((ClocksWindowClass *) klass)->change_page = clocks_window_real_change_page;
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (klass)->finalize = clocks_window_finalize;
#line 22 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/clocks/ui/window.ui");
#line 22 "../src/window.vala"
	clocks_window_signals[CLOCKS_WINDOW_CHANGE_PAGE_SIGNAL] = g_signal_new ("change-page", CLOCKS_TYPE_WINDOW, G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION, G_STRUCT_OFFSET (ClocksWindowClass, change_page), NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "header_bar", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, header_bar));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stack", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, stack));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, menu_button));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switcher_bar", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, switcher_bar));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "squeezer", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, squeezer));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "title_wide_switcher", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, title_wide_switcher));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "title_narrow_switcher", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, title_narrow_switcher));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "title_text", FALSE, ClocksWindow_private_offset + G_STRUCT_OFFSET (ClocksWindowPrivate, title_text));
#line 1827 "window.c"
}

static void
clocks_window_instance_init (ClocksWindow * self,
                             gpointer klass)
{
#line 22 "../src/window.vala"
	self->priv = clocks_window_get_instance_private (self);
#line 22 "../src/window.vala"
	g_type_ensure (CLOCKS_TYPE_HEADER_BAR);
#line 22 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1840 "window.c"
}

static void
clocks_window_finalize (GObject * obj)
{
	ClocksWindow * self;
#line 22 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CLOCKS_TYPE_WINDOW, ClocksWindow);
#line 36 "../src/window.vala"
	_g_object_unref0 (self->priv->header_bar);
#line 38 "../src/window.vala"
	_g_object_unref0 (self->priv->stack);
#line 40 "../src/window.vala"
	_g_object_unref0 (self->priv->menu_button);
#line 42 "../src/window.vala"
	_g_object_unref0 (self->priv->switcher_bar);
#line 44 "../src/window.vala"
	_g_object_unref0 (self->priv->squeezer);
#line 46 "../src/window.vala"
	_g_object_unref0 (self->priv->title_wide_switcher);
#line 48 "../src/window.vala"
	_g_object_unref0 (self->priv->title_narrow_switcher);
#line 50 "../src/window.vala"
	_g_object_unref0 (self->priv->title_text);
#line 52 "../src/window.vala"
	_g_object_unref0 (self->priv->settings);
#line 53 "../src/window.vala"
	self->priv->panels = (_vala_array_free (self->priv->panels, self->priv->panels_length1, (GDestroyNotify) g_object_unref), NULL);
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (clocks_window_parent_class)->finalize (obj);
#line 1871 "window.c"
}

GType
clocks_window_get_type (void)
{
	static volatile gsize clocks_window_type_id__volatile = 0;
	if (g_once_init_enter (&clocks_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClocksWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) clocks_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ClocksWindow), 0, (GInstanceInitFunc) clocks_window_instance_init, NULL };
		GType clocks_window_type_id;
		clocks_window_type_id = g_type_register_static (gtk_application_window_get_type (), "ClocksWindow", &g_define_type_info, 0);
		ClocksWindow_private_offset = g_type_add_instance_private (clocks_window_type_id, sizeof (ClocksWindowPrivate));
		g_once_init_leave (&clocks_window_type_id__volatile, clocks_window_type_id);
	}
	return clocks_window_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

