/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APP_ID "org.gnome.clocksDevel"

#define DATADIR "/app/share"

#define GETTEXT_PACKAGE "gnome-clocks"

#define GNOMELOCALEDIR "/app/share/locale"

#define G_LOG_DOMAIN "org.gnome.ClocksDevel"

#define HAVE__NL_TIME_FIRST_WEEKDAY 1

#define NAME_PREFIX "(Development) "

#define PACKAGE_NAME "gnome-clocks"

#define PACKAGE_VERSION "3.34.0"

#define PROFILE "Devel"

#define VERSION "3.34.0"

