name: gnome-clocks
version: git
summary: Simple GNOME app with stopwatch, timer, and world clock support
description: |
  GNOME Clocks is a simple application to show the time and date in multiple
  locations and set alarms or timers. A stopwatch is also included.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: GNOME Clocks

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-clocks:
    interface: dbus
    bus: session
    name: org.gnome.clocks

apps:
  gnome-clocks:
    command: desktop-launch gnome-clocks
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - unity7
      - location-observe
      - wayland
    desktop: usr/share/applications/org.gnome.clocks.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-clocks

parts:
  libgweather:
    source: https://git.gnome.org/browse/libgweather
    source-type: git
    plugin: meson
    meson-parameters: 
      - --prefix=/usr
      - --datadir=../snap/gnome-clocks/current/usr/share
    organize:
      snap/gnome-clocks/current/usr: usr
    build-packages:
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libxml2-utils
      - gtk-doc-tools
      - libglib2.0-doc
      - libgtk-3-doc
      - libgirepository1.0-dev
      - gobject-introspection
      - tzdata
      - valac
      - libgeocode-glib-dev
      - libgladeui-dev

  gnome-clocks:
    after: [libgweather, desktop-gnome-platform]
    source: .
    source-type: git
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-clocks/current/usr]
    organize:
      snap/gnome-clocks/current/usr: usr
    override-build: |
      sed -i.bak -e 's|=org.gnome.clocks$|=${SNAP}/meta/gui/org.gnome.clocks.svg|g' data/org.gnome.clocks.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.clocks.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp snapbuild/data/org.gnome.clocks.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libgeoclue-2-dev
      - libgeocode-glib-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgsound-dev
      - libgtk-3-dev
      - valac

  libraries:
    plugin: nil
    stage-packages:
      - libgsound0
      - libgeocode-glib0
      - libgeoclue-2-0
    prime:
      - "usr/lib/*/libgsound.so.*"
      - "usr/lib/*/libgeocode-glib.so.*"
      - "usr/lib/*/libgeoclue-2.so.*"
