name: gnome-clocks
version: git
summary: Simple GNOME app with stopwatch, timer, and world clock support
description: |
  GNOME Clocks is a simple application to show the time and date in multiple
  locations and set alarms or timers. A stopwatch is also included.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604

slots:
  # for GtkApplication registration
  gnome-clocks:
    interface: dbus
    bus: session
    name: org.gnome.clocks

apps:
  gnome-clocks:
    command: desktop-launch gnome-clocks
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - unity7
      - location-observe
      - wayland
    desktop: usr/share/applications/org.gnome.clocks.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-clocks

parts:
  libgweather:
    source: https://git.gnome.org/browse/libgweather
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gnome-clocks/current/usr]
    organize:
      snap/gnome-clocks/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - gnome-common
      - gnome-pkg-tools
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - intltool
      - pkg-config
      - libxml2-utils
      - gtk-doc-tools
      - libglib2.0-doc
      - libgtk-3-doc
      - libgirepository1.0-dev
      - gobject-introspection
      - tzdata
      - valac
      - libgeocode-glib-dev
      - libgladeui-dev

  gnome-clocks:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gnome-clocks/current/usr]
    organize:
      snap/gnome-clocks/current/usr: usr
    prepare:
      sed -i.bak -e 's|=org.gnome.clocks$|=${SNAP}/meta/gui/org.gnome.clocks.png|g' data/org.gnome.clocks.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/apps/org.gnome.clocks.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp _build/data/org.gnome.clocks.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-attributes: ['no-system-libraries']
    build-packages:
      - meson
      - desktop-file-utils
      - gettext
      - gnome-common
      - gsettings-desktop-schemas-dev
      - appstream-util
      - gnome-pkg-tools
      - libgeoclue-2-dev
      - libgeocode-glib-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgsound-dev
      - libgtk-3-dev
      - libgweather-3-dev
      - pkg-config
      - valac
      - yelp-tools

  libraries:
    plugin: nil
    stage-packages:
      - libgsound0
      - libgeocode-glib0
      - libgeoclue-2-0
    prime:
      - "usr/lib/*/libgsound.so.*"
      - "usr/lib/*/libgeocode-glib.so.*"
      - "usr/lib/*/libgeoclue-2.so.*"
