name: gnome-clocks
version: git
summary: Simple GNOME app with stopwatch, timer, and world clock support
description: |
  GNOME Clocks is a simple application to show the time and date in multiple
  locations and set alarms or timers. A stopwatch is also included.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

layout:
  /usr/share/libgweather:
    bind: $SNAP/usr/share/libgweather

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-2.0+
  title: GNOME Clocks

slots:
  # for GtkApplication registration
  gnome-clocks:
    interface: dbus
    bus: session
    name: org.gnome.clocks

apps:
  gnome-clocks:
    command: usr/bin/gnome-clocks
    extensions: [gnome-3-28]
    plugs:
      - gsettings
      - pulseaudio
      - location-observe
    desktop: usr/share/applications/org.gnome.clocks.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-clocks

parts:
  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/gnome-clocks/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/gnome-clocks/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - gtk-doc-tools

  gsound:
    after: [libcanberra]
    source: https://gitlab.gnome.org/GNOME/gsound.git
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/gnome-clocks/current/usr, --disable-Werror]
    organize:
      snap/gnome-clocks/current/usr: usr
    build-packages:
      - autoconf-archive
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - valac

  libgweather:
    source: https://git.gnome.org/browse/libgweather
    source-type: git
    plugin: meson
    meson-parameters: 
      - --prefix=/usr
    build-packages:
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libxml2-utils
      - gtk-doc-tools
      - libglib2.0-doc
      - libgtk-3-doc
      - libgirepository1.0-dev
      - gobject-introspection
      - tzdata
      - valac
      - libgeocode-glib-dev
      - libgladeui-dev

  gnome-clocks:
    after: [gsound, libgweather]
    source: .
    source-type: git
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-clocks/current/usr]
    organize:
      snap/gnome-clocks/current/usr: usr
    override-build: |
      sed -i.bak -e "s|'--vapidir'|'--vapidir', '$SNAPCRAFT_STAGE/usr/share/vala/vapi', '--vapidir'|g" src/meson.build
      sed -i.bak -e 's|=org.gnome.clocks$|=${SNAP}/meta/gui/org.gnome.clocks.svg|g' data/org.gnome.clocks.desktop.in.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.clocks.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp snapbuild/data/org.gnome.clocks.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libgeoclue-2-dev
      - libgeocode-glib-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgsound-dev
      - libgtk-3-dev
      - valac

  libraries:
    plugin: nil
    stage-packages:
      - libgsound0
      - libgeocode-glib0
      - libgeoclue-2-0
    prime:
      - "usr/lib/*/libgsound.so.*"
      - "usr/lib/*/libgeocode-glib.so.*"
      - "usr/lib/*/libgeoclue-2.so.*"
